### ISSUE TITLE
[Bug]: WSL2 Ubuntu CLI 3 Gem error nokogiri

### ISSUE THREAD

**Issue by hoektoe** [Shopify/cli#1033]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

shopify theme dev should have served my theme successfully and create localhost + editor linkgs

### Actual behavior

Got error for nokogiri failure of gem file.

### Stack trace

```shell
An error occurred while installing nokogiri (1.13.10), and Bundler cannot
continue.

In Gemfile:
  shopify-cli was resolved to 2.33.0, which depends on
    theme-check was resolved to 1.12.1, which depends on
      nokogiri
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using ast 2.4.2
Using concurrent-ruby 1.1.10
Using bundler 2.4.2
Using ffi 1.15.5
Using liquid 5.4.0
Using rb-fsevent 0.11.2
Using mini_portile2 2.8.1
Using racc 1.6.2
Using parser 3.2.0.0
Using bugsnag 6.25.1
Using rb-inotify 0.10.1
Using listen 3.7.1
Installing nokogiri 1.13.10 with native extensions
    at makeError (file:///home/linuxbrew/.linuxbrew/lib/node_modules/@shopify/theme/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/linuxbrew/.linuxbrew/lib/node_modules/@shopify/theme/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.exec (file:///home/linuxbrew/.linuxbrew/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/system.js:41:9)
    at async bundleInstallShopifyCLI (file:///home/linuxbrew/.linuxbrew/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:197:5)
    at async Task.task (file:///home/linuxbrew/.linuxbrew/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:131:21)
    at async Task.run (file:///home/linuxbrew/.linuxbrew/lib/node_modules/@shopify/theme/node_modules/listr2/dist/index.js:960:11)
    at async /home/linuxbrew/.linuxbrew/lib/node_modules/@shopify/theme/node_modules/p-map/index.js:57:22 {
  tryMessage: null,
  type: 0,
  nextSteps: undefined,
  command: 'bundle',
  args: [ 'install' ]
```

### Reproduction steps

1. npm install -g @shopify/cli @shopify/theme in ubuntu 20 on windows machines WSL2
2. shopify theme dev
3. failure

### Operating System

Windows, WSL 2, Ubuntu

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.31.1

### Shell

Terminal 

### Node version (run `node -v` if you're not sure)

v16.19.0

### What language and version are you using in your application?

ruby 3.2

**Comment by EvonuX** [comment]
Got the same issue on node 19.4.0. Super annoying

**Comment by matteodepalo** [comment]
@Shopify/theme-developer-tools

**Comment by karreiro** [comment]
@matteodepalo Actually, the fix for this issue seems to live at CLI UI kit level (so, I've updated the area)

**Comment by hoektoe** [comment]
I see to have solved the issue by changing node version for the project and using a single ruby package installer. Somehow had multiple configured. 

So just check which ruby and ruby -v on your machine. 

I really dislike WSL, mac setup is so much easier
