### ISSUE TITLE
[Bug]: Password flag error with `shopify theme dev` and `push` commands

### ISSUE THREAD

**Issue by kenji-twp** [Shopify/cli#1150]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The password flag should work for push and dev commands (`dev` as per v3.29.0 if I'm not mistaken).

### Actual behavior

When passing the `--password` flag, shopify cli ends abruptly with an error:

```
bundler: failed to load command: shopify (/Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/bin/shopify)
✗ An unexpected error occured.
```

If I don't pass the password flag, it runs normally.

This started to happen after I updated the cli to v3.34.0, it was working on v.3.33.0. Updated via homebrew update + upgrade.

NoteL the stack trace is saying node.js v19.4.0, but I'm using node v16 with nvm.

### Stack trace

```shell
bundler: failed to load command: shopify (/Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/bin/shopify)
✗ An unexpected error occured.
        To submit an issue include the stack trace.

/Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/api.rb:78:in `block in request': 429 (ShopifyCLI::API::APIRequestThrottledError)
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/api.rb:89:in `request'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/theme_access_api.rb:43:in `rest_request'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/theme_admin_api.rb:38:in `rest_request'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/theme_admin_api.rb:18:in `get'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/development_theme.rb:48:in `exists?'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/development_theme.rb:34:in `ensure_exists!'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/development_theme.rb:71:in `find_or_create!'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/dev_server.rb:192:in `theme'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/dev_server.rb:289:in `syncing_theme_message'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/dev_server.rb:170:in `block in sync_theme'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/dev_server.rb:169:in `sync_theme'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/dev_server.rb:102:in `start'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/theme/dev_server.rb:64:in `start'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/project_types/theme/commands/serve.rb:49:in `call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/command.rb:27:in `call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/executor.rb:15:in `call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/monorail.rb:26:in `log'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/entry_point.rb:16:in `call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/bin/shopify:49:in `block in <top (required)>'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/bin/shopify:59:in `<top (required)>'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/bin/shopify:25:in `load'
        from /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/bin/shopify:25:in `<top (required)>'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:45:in `block in <top (required)>'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:33:in `<top (required)>'
        from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
        from /opt/homebrew/opt/ruby/bin/bundle:25:in `<main>'
/opt/homebrew/Cellar/shopify-cli/3.34.0/libexec/lib/node_modules/@shopify/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

AbortSilent [Error]
    at execCLI2 (file:///opt/homebrew/Cellar/shopify-cli/3.34.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:47:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  tryMessage: null,
  type: 1,
  nextSteps: undefined
}

Node.js v19.4.0
```

### Reproduction steps

1. Install shopify cli v3.34.0 via homebrew
2. Try a `shopify theme dev` or `shopify theme push` command with the flags `--path=<PATH> --store=<YOUR_STORE> --password=<THEME_ACCESS_PASSWORD> --theme=<THEME_ID>`

In my case I used `--path=src` and a theme ID (not theme name)

### Operating System

Mac OS Ventura 13.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

v3.34.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.19.0

**Comment by nikitaourazbaev** [comment]
Also seeing this issue. For us it seems to be store-specific as another development store is unaffected.

**Comment by kenji-twp** [comment]
Some interesting logs when using the `--verbose` flag:

<img width="1428" alt="Screenshot 2023-01-24 at 5 21 49 pm" src="https://user-images.githubusercontent.com/111416569/214233777-d9a0cc65-3bc1-4ead-8857-92363cbe38ec.png">

... and this when using a custom app password, instead of theme access password:

<img width="989" alt="Screenshot 2023-01-24 at 5 16 03 pm" src="https://user-images.githubusercontent.com/111416569/214233445-07a57732-831e-495a-aa2a-13c81ea4c5d1.png">

**Comment by nikitaourazbaev** [comment]
Updated to 3.38.0 and this is still happening. Seems to be some kind of throttling issue?

![CleanShot 2023-01-26 at 16 13 57@2x](https://user-images.githubusercontent.com/41582891/214951999-5d46c3fb-bc4c-4306-9b20-c9b271629d6e.png)

This error code can be found in the log attached to @kenji-twp’s original report above, too.

There’s quite a delay after the initial “Viewing theme…” output so perhaps something is making multiple attempts at something and getting throttled as a result?

This is still isolated to (so far) one of our development stores. There does not seem to be a way to downgrade to an earlier version with `homebrew` – are there any other workarounds (other than not using the `--pasword` flag, which we’re already having to do due to this)?

**Comment by kenji-twp** [comment]
This seems to be fixed in the latest release v3.40.2
