### ISSUE TITLE
shopify theme dev error

### ISSUE THREAD

**Issue by hedgehog90** [Shopify/cli#1182]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Success.

### Actual behavior

Failure.

### Stack trace

```shell
>shopify theme dev --store=************************

C:\Dev\nvm\v18.2.0\node_modules\@shopify\cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

ExternalError: Command failed with exit code 5: bundle install
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Users/Tom/AppData/Local/shopify-cli-nodejs/Cache/vendor/ruby-cli/2.34.0/ruby/3.1.0/gems/racc-1.6.2/ext/racc/cparse
C:/tools/ruby31/bin/ruby.exe -I C:/tools/ruby31/lib/ruby/3.1.0 extconf.rb
checking for rb_block_call()... yes
checking for rb_ary_subseq()... yes
creating Makefile

current directory:
C:/Users/Tom/AppData/Local/shopify-cli-nodejs/Cache/vendor/ruby-cli/2.34.0/ruby/3.1.0/gems/racc-1.6.2/ext/racc/cparse
make DESTDIR\= sitearchdir\=./.gem.20230121-34932-nv0r6u
sitelibdir\=./.gem.20230121-34932-nv0r6u clean
current directory:
C:/Users/Tom/AppData/Local/shopify-cli-nodejs/Cache/vendor/ruby-cli/2.34.0/ruby/3.1.0/gems/racc-1.6.2/ext/racc/cparse
make DESTDIR\= sitearchdir\=./.gem.20230121-34932-nv0r6u
sitelibdir\=./.gem.20230121-34932-nv0r6u
make failedNo such file or directory - make

Gem files will remain installed in
C:/Users/Tom/AppData/Local/shopify-cli-nodejs/Cache/vendor/ruby-cli/2.34.0/ruby/3.1.0/gems/racc-1.6.2
for inspection.
Results logged to
C:/Users/Tom/AppData/Local/shopify-cli-nodejs/Cache/vendor/ruby-cli/2.34.0/ruby/3.1.0/extensions/x64-mingw-ucrt/3.1.0/racc-1.6.2/gem_make.out

  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:77:in `rescue in run'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:74:in `run'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:51:in `block in make'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:43:in `each'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:43:in `make'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:171:in
`build_extension'
C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:205:in `block in
build_extensions'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `each'
C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in
`build_extensions'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/installer.rb:843:in `build_extensions'
C:/tools/ruby31/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
C:/tools/ruby31/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:28:in
`install'
  C:/tools/ruby31/lib/ruby/3.1.0/bundler/source/rubygems.rb:207:in `install'
C:/tools/ruby31/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:54:in
`install'
C:/tools/ruby31/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/tools/ruby31/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in
`do_install'
C:/tools/ruby31/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  C:/tools/ruby31/lib/ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
C:/tools/ruby31/lib/ruby/3.1.0/bundler/worker.rb:57:in `block in
process_queue'
  C:/tools/ruby31/lib/ruby/3.1.0/bundler/worker.rb:54:in `loop'
  C:/tools/ruby31/lib/ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
C:/tools/ruby31/lib/ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in
create_threads'

An error occurred while installing racc (1.6.2), and Bundler cannot continue.

In Gemfile:
  shopify-cli was resolved to 2.34.0, which depends on
    theme-check was resolved to 1.14.0, which depends on
      nokogiri was resolved to 1.14.0, which depends on
        racc
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using bundler 2.3.26
Fetching concurrent-ruby 1.1.10
Fetching ffi 1.15.5 (x64-mingw-ucrt)
Fetching rb-fsevent 0.11.2
Fetching liquid 5.4.0
Fetching wdm 0.1.1
Fetching racc 1.6.2
Fetching ast 2.4.2
Installing ast 2.4.2
Installing wdm 0.1.1 with native extensions
Installing liquid 5.4.0
Installing racc 1.6.2 with native extensions
Installing rb-fsevent 0.11.2
Installing ffi 1.15.5 (x64-mingw-ucrt)
Fetching parser 3.2.0.0
Installing concurrent-ruby 1.1.10
Installing parser 3.2.0.0
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching listen 3.7.1
Fetching bugsnag 6.25.1
Installing listen 3.7.1
Installing bugsnag 6.25.1
    at makeError (file:///C:/Dev/nvm/v18.2.0/node_modules/@shopify/theme/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///C:/Dev/nvm/v18.2.0/node_modules/@shopify/theme/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exec (file:///C:/Dev/nvm/v18.2.0/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/system.js:53:9)
    at async bundleInstallShopifyCLI (file:///C:/Dev/nvm/v18.2.0/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:223:5)
    at async Object.task (file:///C:/Dev/nvm/v18.2.0/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:125:21)
    at async runTasks (file:///C:/Dev/nvm/v18.2.0/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/ui/components/Tasks.js:24:28) {
  tryMessage: null,
  type: 0,
  nextSteps: undefined,
  command: 'bundle',
  args: [ 'install' ]
}
```

### Reproduction steps

Run `shopify theme dev` for my store.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.36.1

### Shell

Windows Command Prompt

### Node version (run `node -v` if you're not sure)

18.2

### What language and version are you using in your application?

Node 18.2, ruby 3.1.3p185

**Comment by hedgehog90** [comment]
Sorry, worked it out.
I installed ruby with choco. I uninstalled it and instead installed ruby with devkit here:
https://rubyinstaller.org/downloads/
