### ISSUE TITLE
[Bug]: Couldn't find ngrok tunnel plugin after 3.36.2 upgrade

### ISSUE THREAD

**Issue by 0x-buidl** [Shopify/cli#1201]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

`shopify app dev` should start up ngrok tunnel without errors

`shopify ngrok auth [token]` should authenticate ngrok without errors

### Actual behavior

`shopify app dev` fails with `We couldn't find the ngrok tunnel plugin`

`shopify ngrok auth [token]` fails with `command not found`

### Stack trace

```shell
We couldn't find the ngrok tunnel plugin                              │
│                                                                        │
│  To investigate the issue, examine this stack trace:                   │
│  at mapRunTunnelPluginError                                            │
│  (@shopify/app/src/cli/services/dev/urls.ts:173)                       │
│   return new BugError(`We couldn't find the                            │
│   ${tunnelPluginError.provider} tunnel plugin`)                        │
│  at mapError (@shopify/cli-kit/src/public/common/result.ts:120)        │
│   return err(mapper(this.error))                                       │
│  at generateURL (@shopify/app/src/cli/services/dev/urls.ts:96)         │
│   .mapError(mapRunTunnelPluginError)                                   │
│  at processTicksAndRejections (node:internal/process/task_queues:95)   │
│  at async generateFrontendURL                                          │
│  (@shopify/app/src/cli/services/dev/urls.ts:80)                        │
│   frontendUrl = await generateURL(options.commandConfig,               │
│   frontendPort)                                                        │
│  at async dev (@shopify/app/src/cli/services/dev.ts:66)                │
│   const {frontendUrl, frontendPort, usingLocalhost} = await            │
│   generateFrontendURL({                                                │
│  at run (@shopify/app/src/cli/commands/app/dev.ts:100)                 │
│   await dev({
```

### Reproduction steps

1. `shopify app dev` or `shopify app dev --reset`
2.  `shopify ngrok auth [token]`
3.

### Operating System

Mac OS Ventura 13.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.36.2

### Shell

iterm2

### Node version (run `node -v` if you're not sure)

v19.0.0

### Ruby version (run `ruby -v` if you're not sure)
ruby 3.2.0

### What language and version are you using in your application?

Typescript

**Comment by 0x-buidl** [comment]
Verbose log is quite long, not much helping logs probably 

```
plugin: @shopify/cli
root: /node_modules/@shopify/cli
See more details with DEBUG=*
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/node_modules/@shopify/cli',
  name: '@shopify/cli-hydrogen'
}
    at Plugin.load (/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/plugin.js:106:19)
    at async /node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:438:17
    at async Promise.all (index 2)
    at async Config.loadPlugins (/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:426:9)
    at async Config.loadCorePlugins (/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:149:13)
    at async Config.load (/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:140:9)
    at async Config.load (/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:79:9)
    at async run (node_modules/@shopify/cli/node_modules/@oclif/core/lib/main.js:42:20)
module: @oclif/core@1.21.0
task: loadPlugins
plugin: @shopify/cli
root: node_modules/@shopify/cli
See more details with DEBUG=*
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/scaffold/extension.js +532ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/build.js +0ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/info.js +0ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/env/pull.js +0ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/env/show.js +0ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/generate/extension.js +0ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/event/trigger.js +1ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/generate/schema.js +329ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/deploy.js +0ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/dev.js +0ms
  config config done +900ms
  config start init hook +0ms
  config init hook done +1ms
  config runCommand app:dev [] +0ms
  config:@shopify/app (import) node_modules/@shopify/app/dist/cli/commands/app/dev.js +2ms
  config start prerun hook +0ms
  shopify:@shopify/cli:hooks:prerun start (import) node_modules/@shopify/cli/node_modules/@shopify/cli-kit/dist/public/node/hooks/prerun.js +0ms
  shopify:@shopify/cli:hooks:prerun done +1ms
  config prerun hook done +4ms

```

**Comment by 0x-buidl** [comment]
Yeah the plugin was working fine before the upgrade, but the session for authenticated account expires too quickly which slows down development time. Saw a comment [https://github.com/Shopify/shopify-cli/issues/2385](here)  that says it's been fix in later releases. I upgraded using `yarn upgrade @shopify/cli`, haven't been able to do anything since then. I do not know what exact version i was running prior to this

**Comment by 0x-buidl** [comment]
Thanks, upgraded both packages and everything works fine now. 
Closing the issue with this comment
