### ISSUE TITLE
[Bug]: Ngrok "Failed to start the tunnel"

### ISSUE THREAD

**Issue by usrx-rob** [Shopify/cli#1217]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension, Theme

### Expected behavior

Be able to start ngrok tunnel after running through README steps

### Actual behavior

Throwing an error on yarn dev and erroring out.  

### Stack trace

```shell
/Users/robert/Desktop/usrx-custom-app/us-rx/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: failed to start the tunnel
    at connectRetry (/Users/robert/Desktop/usrx-custom-app/us-rx/node_modules/@shopify/ngrok/index.js:45:11)
    at async /Users/robert/Desktop/usrx-custom-app/us-rx/node_modules/@shopify/ngrok/index.js:30:17

Node.js v18.9.1
error Command failed with exit code 7.
```

### Reproduction steps

1. Complete README steps 
2. Run `yarn dev`

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.37.0

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.9.1

### What language and version are you using in your application?

Node v18.9.1

**Comment by matteodepalo** [comment]
Hi @usrx-rob have you tried to kill any potentially running ngrok process wth `killall ngrok` and running `dev` again?

**Comment by usrx-rob** [comment]
@matteodepalo I did try that, no luck unfortunately :(
`No matching processes belonging to you were found`

**Comment by matteodepalo** [comment]
@usrx-rob could you try again on the latest version? We've added some fixes related to theme extensions and `dev`.

**Comment by alexandrosk** [comment]
I have the same issue on latest 
`pnpm create @shopify/app@latest --template php`

**Comment by matteodepalo** [comment]
@usrx-rob apologies but without more information on your setup it's hard for me to debug the issue. 
- Was `dev` ever working for you with any previous version?
- What about choosing a different template during creation?
- Does ngrok successfully start a tunnel if used with its own CLI?

The last item especially is important to understand if this is a Shopify CLI issue or an Ngrok issue.

**Comment by hmthang96** [comment]
`/home/thanghm@aht.local/Documents/NB_AHT/CK_Learning/App/appshop/moneyapp/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: failed to start the tunnel
    at connectRetry (/home/thanghm@aht.local/Documents/NB_AHT/CK_Learning/App/appshop/moneyapp/node_modules/@shopify/ngrok/index.js:45:11)
    at async /home/thanghm@aht.local/Documents/NB_AHT/CK_Learning/App/appshop/moneyapp/node_modules/@shopify/ngrok/index.js:30:17
`

I have same problem

**Comment by usrx-rob** [comment]
@matteodepalo

Was dev ever working for you with any previous version? **No**
What about choosing a different template during creation? **No**
Does ngrok successfully start a tunnel if used with its own CLI? **Yes**

**Comment by sachinnair26** [comment]
I went to 

`/project/node_modules/@shopify/ngrok/src/client.js`

and went into the function that starts the tunnel and realized the package was throwing an error if ngrok didnt connect in first 10 tries 

`async function connectRetry(opts, retryCount = 0) {
  if (!processUrl || !ngrokClient) {
    return;
  }
  opts.name = String(opts.name || uuid.v4());
  const response = await ngrokClient.startTunnel(opts);
  if (response) {
    return response.public_url;
  }
  if (retryCount >= 10) { // this will throw error if retires goes more than 10  so I just changed it to 20 
    throw new Error('failed to start the tunnel');
  }
  await sleep(0.2);
  return connectRetry(opts, ++retryCount);
}`

so I changed the retryCount to 20 and it worked 

Hope it helps in debugging

**Comment by vvasylkovskyi** [comment]
I still need help getting it to work for me. Since my first initialization of the app, the ngrok old URL got stuck somewhere.
Even though I add a new URL and started the app using 
`npm run shopify:dev -- --tunnel-url "https://f838-79-169-61-226.eu.ngrok.io:8988"` 

When I am trying to call my endpoints from my shopify extension I receive this error: 

![image](https://user-images.githubusercontent.com/25831789/221365740-802d0fde-aca6-4e5c-878d-a600910b091d.png)

**Comment by vvasylkovskyi** [comment]
@isaacroldan I keep getting `acba-2001-8a0-7ad0-5901-9d1e-fea8-d049-ecdb.ngrok.io` stuck somewhere, how do I clean up this from cache?

**Comment by vvasylkovskyi** [comment]
I figured out what was the issue. I changed the proxy URL on the partner's website and then it worked. It seems that for some reason old proxy URL was stuck 🤔

**Comment by james-julius** [comment]
> so I changed the retryCount to 20 and it worked

Thank you! Spent quite a lot of time on this and this finally made it work. So weird developing in somebody else's walled garden

**Comment by webrexRavi** [comment]
https://github.com/Shopify/cli/issues/1217#issuecomment-1417046779

Worked for me.

Find `connectRetry` function and increase count to 20
```
 if (retryCount >= 20) {
    throw new Error('failed to start the tunnel');
  }

```
Thank you @sachinnair26

**Comment by blanklob** [comment]
I have updated to latest CLI `3.46.0` But still getting the error with Cloudflare quick tunnels @Arkham ?

```bash
error ────────────────────────────────────────────────────────────────╮
│                                                                        │
│  Could not start tunnel, max retries reached                           │
│                                                                        │
│  To investigate the issue, examine this stack trace:                   │
│    at pollTunnelStatus [as _onTimeout]                                 │
│    (@shopify/app/src/cli/services/dev/urls.ts:106)                     │
│      if (result.status === 'error') return reject(new                  │
│      BugError(result.message))                                         │
│    at listOnTimeout (node:internal/timers:569)                         │
│    at processTimers (node:internal/timers:512)                         │
│                                                                        │
╰────────────────────────────────────────────────────────────────────────
```

**Comment by isaacroldan** [comment]
Seems like the cloudflared binary is crashing trying to create the tunnel connection 🤔 
Does it happen always?

Could you try to run cloudflared in a separate terminal to see if it works?
- Find the cloudflared binary in your node modules folder. Is usually at `./node_modules/@shopify/plugin-cloudflare/cloudflared` (if you can't find it you can also install cloudflared globally, instructions [here](https://github.com/cloudflare/cloudflared#installing-cloudflared))
- run it with: `cloudflared --url http://localhost:3000`

It should print a URL and a message like `INF Registered tunnel connection`. If that works but the Shopify CLI doesn't, you can use that URL with `dev` like:
```
pnpm shopify dev --tunnel-url {cloudflare_url}:3000
```

Let me know how it goes :)

**Comment by Tomtom1410** [comment]
> Seems like the cloudflared binary is crashing trying to create the tunnel connection 🤔 Does it happen always?
> 
> Could you try to run cloudflared in a separate terminal to see if it works?
> 
> * Find the cloudflared binary in your node modules folder. Is usually at `./node_modules/@shopify/plugin-cloudflare/bin/cloudflared` (if you can't find it you can also install cloudflared globally, instructions [here](https://github.com/cloudflare/cloudflared#installing-cloudflared))
> * run it with: `cloudflared --url http://localhost:3000`
> 
> It should print a URL and a message like `INF Registered tunnel connection`. If that works but the Shopify CLI doesn't, you can use that URL with `dev` like:
> 
> ```
> pnpm shopify dev --tunnel-url {cloudflare_url}:3000
> ```
> 
> Let me know how it goes :)

Hi there,
I init a shopify app and run it, but i have an error, so i can't run my project, I use latest CLI 3.46.0. Can you have me resolve it?
tôi cũng đã thử với cloudflared, but it still doesn't work
This is my error:
1. npm run dev
=> error
![image](https://github.com/Shopify/cli/assets/87224702/633138f3-62df-4712-b294-69b2563b220d)

**Comment by joeainsworth** [comment]
Also experiencing same issue as @Tomtom1410

**Comment by joeainsworth** [comment]
```
shopify --version
@shopify/cli/3.46.1 darwin-x64 node-v20.2.0
```

`npm run dev`

Then I get this error

![Screenshot 2023-05-31 at 12 38 52](https://github.com/Shopify/cli/assets/5084107/a26a1eef-c004-49bb-9061-4fad7cb71762)

**Comment by isaacroldan** [comment]
@Tomtom1410 @joeainsworth , this is a different issue, related with cloudflare not ngrok.
Could you open a new issue so that we can track it properly? Please include as much info as possible: OS, terminal, node version, and if possible, run the same command with `--verbose` and attach it.
