### ISSUE TITLE
[Bug]: Shopify CLI error on shopify theme dev

### ISSUE THREAD

**Issue by petercampanelli** [Shopify/cli#1303]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Should have prompted me to log in or should have started the dev server if I was already authorized.

### Actual behavior

Got this error. Have not modified the CLI locally at all.

### Stack trace

```shell
$ shopify theme dev --store=storename.myshopify.com

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- listen
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- listen
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- listen
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- listen
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

✗ An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

? Send an anonymized error report to Shopify? (You chose: Yes, send)
[Note] You cannot use gems with Shopify CLI.                                                     
[LoadError] cannot load such file -- bugsnag                                                     
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bugsnag (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/exception_reporter.rb:32:in `report_to_bugsnag'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/exception_reporter.rb:27:in `report'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:31:in `handle_exception'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:71:in `block in install!'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- listen (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/file_system_listener.rb:2:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/watcher.rb:2:in `<top (required)>'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:18:in `require_relative'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:18:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/serve.rb:2:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:63:in `const_get'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:63:in `block in subcommand'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:87:in `resolve_class'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:70:in `resolve_global_command'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:64:in `resolve_command'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:41:in `lookup_command'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:42:in `full_command'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:20:in `log'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:50:in `block (2 levels) in <main>'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:49:in `block in <main>'
        from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:59:in `<main>'
/opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

AbortSilentError
    at execCLI2 (file:///opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:51:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  tryMessage: null,
  type: 1,
  nextSteps: undefined
}
```

### Reproduction steps

Just updated shopify-cli via Homebrew to start the week and then ran `shopify theme dev --store=storename.myshopify.com` 

### Operating System

macOS 13.2 (Apple Silicon/ARM)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.40.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.13.0

### What language and version are you using in your application?

NA - theme development

**Comment by MichaelPrecel** [comment]
Also experiencing this. All was good until I upgraded to the latest version of the CLI.
```
TOOLING AND SYSTEM                 
Shopify CLI    3.40.1
OS             darwin-arm64
Shell          /bin/zsh
Node version   v19.6.0
Ruby version   3.2.0
```

**Comment by gonzaloriestra** [comment]
Version 3.40.2 should fix it. Could you please upgrade and try again? Thanks!

**Comment by petercampanelli** [comment]
Working! Thank you so much for fixing this so quickly!!!

**Comment by bpenno** [comment]
Yes - this worked for me as well. Thanks for the prompt fix!
