### ISSUE TITLE
[Bug]: Newest version does not work from homebrew

### ISSUE THREAD

**Issue by ekwoka** [Shopify/cli#1306]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It should work

### Actual behavior

After updating to newest version on homebrew, `theme serve` no longer works.

```
Command failed with exit code 1: /opt/homebrew/opt/ruby/bin/bundle install
/opt/homebrew/opt/ruby/bin/bundle:25:in `load': cannot load such file -- /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.20/exe/bundle (LoadError)
```

This is where I'm at now freshly reinstalling everything.

first it complained I didn't have `bundler` so to install it it with gem, so I did, and then it complains it's the wrong version, so then I install the right version...

Now I'm back where I was after updating where it complains about not having this file

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- listen (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

oddly going back to using the system version, not the homebrew version it was using before which is strange...

even trying to send the bug report fails:

```
You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- bugsnag
```

forcing it to use the homebrew ruby gives

```
/opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem shopify-cli (>= 0.a) with executable shopify
```

It's like the shopify cli from `homebrew` installs itself to the local version of ruby but then tries to only use the homebrew version but doesn't do it completely...

and you can't install the version 3 cli directly as a gem so it's like some awful cross dependency issue.

Hopefully there is a plan to just scrap ruby from the process entirely...

### Stack trace

```shell
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/file_system_listener.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/watcher.rb:2:in `<top (required)>'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:18:in `require_relative'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/serve.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:63:in `const_get'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:63:in `block in subcommand'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:87:in `resolve_class'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:70:in `resolve_global_command'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:64:in `resolve_command'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/command_registry.rb:41:in `lookup_command'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:42:in `full_command'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:20:in `log'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:50:in `block (2 levels) in <main>'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:49:in `block in <main>'
	from /opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:59:in `<main>'
/opt/homebrew/Cellar/shopify-cli/3.40.1/libexec/lib/node_modules/@shopify/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
```

### Reproduction steps

1. have any theme
2. run `shopify theme serve [args]`
3. profit?

### Operating System

MacOS 13.2 (22D49)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.40.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.6.0

**Comment by ekwoka** [comment]
okay...it started working after I have ruby using homebrew's version with 

```
if [ -d "/opt/homebrew/opt/ruby/bin" ]; then
  export PATH=/opt/homebrew/opt/ruby/bin:$PATH
  export PATH=`gem environment gemdir`/bin:$PATH
fi
```
in my `.zshrc`

I installed the version 2 cli then uninstalled it

and now it works again...

**Comment by gonzaloriestra** [comment]
Could you please upgrade to 3.42 and try again? There are a couple of additional related fixes. If it doesn't work, can you try with `SHOPIFY_CLI_BUNDLED_THEME_CLI=1 shopify theme dev`?

**Comment by lsorese** [comment]
Seems similar to https://github.com/Shopify/cli/issues/1320

**Comment by chouck-pthreemedia** [comment]
True, Isorese, though since that issue is closed and this one more closely matches the errors I received I opted to add here.

**Comment by gonzaloriestra** [comment]
The latest release (3.43.0) should fix this issue. Sorry for the inconvenience!

**Comment by gonzaloriestra** [comment]
Yes, please. In v3.43 we temporarily disabled some stuff to avoid this
issue, and we would like to ensure that it's now fixed before enabling it
again. It can be checked with that flag (note it's a new one). Thanks a lot!
