### ISSUE TITLE
[Bug]: `shopify theme push` shows interactive "send error report" prompt even with SHOPIFY_CLI_TTY=0

### ISSUE THREAD

**Issue by illarionvk** [Shopify/cli#1573]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The `shopify theme push` command should skip interactive prompts like "Send an anonymized error report to Shopify?" when SHOPIFY_CLI_TTY environment variable is set to zero and immediately exit on error.

<img width="540" alt="Screenshot 2023-03-07 at 17 59 06" src="https://user-images.githubusercontent.com/5012724/223493977-fa96dd3a-1c01-408d-bb2d-7ab5a70e46f6.png">

### Actual behavior

The `shopify theme push` command was waiting for interactive input for 15 minutes while running in a GitHub Action workflow until the CI task timed out.

<img width="1857" alt="Screenshot 2023-03-07 at 17 53 05" src="https://user-images.githubusercontent.com/5012724/223494016-59fbc02a-61f3-4c0a-972b-3b31c4a5d2ba.png">

### Verbose output

```shell
2023-03-07T17:00:25.309Z: Running command theme push
2023-03-07T17:00:25.322Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-03-07T17:00:25.335Z:
Running system process:
  · Command: ruby -v
  · Working directory: /app

2023-03-07T17:00:25.357Z:
Running system process:
  · Command: bundle -v
  · Working directory: /app

2023-03-07T17:00:25.478Z: Reading the content of file at /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2023-03-07T17:00:25.488Z:
Running system process:
  · Command: bundle install
  · Working directory: /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-03-07T17:00:25.747Z:
Running system process:
  · Command: bundle exec ruby /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme push . --unpublished --theme Preview Test
  · Working directory: /app

DEBUG POST https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes.json with X-Request-Id: 753d72e8-91d0-423d-bb18-dab7072c2ff4
✗ An unexpected error occurred.
        To submit an issue include the stack trace.

? Send an anonymized error report to Shopify? (You chose: No, don't send)
/mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/api.rb:80:in `block in request': 422 (ShopifyCLI::API::APIRequestClientError)
{"errors":{"base":["A shop may only have 20 themes"]}}
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/api.rb:89:in `request'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme_access_api.rb:43:in `rest_request'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme_admin_api.rb:38:in `rest_request'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme_admin_api.rb:26:in `post'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme.rb:74:in `create'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme.rb:130:in `create_unpublished'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/push.rb:124:in `find_theme'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/push.rb:50:in `call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:27:in `call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:15:in `call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:26:in `log'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:50:in `block (2 levels) in <main>'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:49:in `block in <main>'
        from /mnt/tmp/node_modules/.pnpm/@shopify+cli-kit@3.44.1_@types+react@17.0.37/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:59:in `<main>'
```

### Reproduction steps

1. Set SHOPIFY_CLI_TTY=0 environment variable
2. Run `shopify theme push -u -t 'My Theme'` command on a store that has reached the max theme limit
3. Expect the command to exit immediately with no additional user input.

### Operating System

Debian Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

Bash

### Node version (run `node -v` if you're not sure)

v16.19.0

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by Arkham** [comment]
Hi, thanks for reporting this! I'll ping @Shopify/theme-developer-tools so they can take a look at this.

**Comment by illarionvk** [comment]
This issue is still relevant to our day to day work.

**Comment by benoitmidon** [comment]
same issue here

**Comment by mgmanzella** [comment]
> It looks like there is no --force flag for shopify theme push.

this isn't expected, force should work with theme push

ik it's unrelated to this specific issue but in the future can you try using` --force` with the `--stable` flag and let us know if that skips a prompt?? weve been working to remove the ruby dependency from the CLI and there may still be parity issues.

> My original bug report shows that the command crashed with an unexpected error, but the CLI was holding up the automation with an interactive prompt.

ahhh ic ic thanks for bump/clarification. have you seen this behavior with all errors from the CLI or just 422s??


> I'd be happy to see a --ci flag that indicates the command is going to run in a non-interactive environment.

definitely, feel free to +1 in [this issue](https://github.com/Shopify/cli/issues/3734) so we can track community interest for this enhancement

**Comment by jamesmengo** [comment]
@illarionvk 
Thanks for your report :) 
This should be fixed in the upcoming release - if you still experience this issue after upgrading, please let us know!
