### ISSUE TITLE
[Bug]: TypeError: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by ulziibat-n** [Shopify/cli#1574]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

I don't know.

### Actual behavior

when writing the `Shopify theme dev --store "storeurl"` command, can't sync the Shopify theme. It getting this error:

```
✗ An unexpected error occurred.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

```

### Verbose output

```shell
2023-03-07T18:24:24.065Z: Running command theme dev
  shopify:theme:dev init version: @oclif/core@2.1.4 argv: [ '--store', 'https://club-builder-testing.myshopify.com', '--verbose' ] +0ms
2023-03-07T18:24:24.077Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-03-07T18:24:24.077Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store club-builder-testing.myshopify.com:
[]

2023-03-07T18:24:24.077Z: Getting session store...
2023-03-07T18:24:24.079Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "club-builder-testing.myshopify.com"
  }
}

2023-03-07T18:24:24.079Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-03-07T18:24:24.079Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-03-07T18:24:24.739Z: Request to https://accounts.shopify.com/oauth/introspection completed in 654 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"c029af1749c48389d6939b60dc28b4e0"
 - x-request-id: e243142c-95f7-4fb1-a1ea-d375ddf392bb
    
2023-03-07T18:24:24.743Z: The identity token is valid: true
2023-03-07T18:24:24.743Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-03-07T18:24:24.743Z: The current session is valid but needs refresh. Refreshing...
2023-03-07T18:24:24.745Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_bfdab265737ed4bb73c85a6cc7b02a5fb6a734459947159050d7e3ea11524a31&refresh_token=atkn_0804777e5ed443217ccee41b4a71b3af4745cd7dd42f16e1272e95ee1c5c97d7&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-03-07T18:24:25.302Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_bfdab265737ed4bb73c85a6cc7b02a5fb6a734459947159050d7e3ea11524a31&refresh_token=atkn_0804777e5ed443217ccee41b4a71b3af4745cd7dd42f16e1272e95ee1c5c97d7&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 555 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"8409d8553fbe737a16a231418485436e"
 - x-request-id: 3a1fb6f9-138f-4a7b-8f1f-b1690b78e206
    
2023-03-07T18:24:25.305Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=atkn_c9e8bdd70d22fbc55cee8b82db2cc0067dd83cab3eaa8940eabc9a890cb38b82
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-03-07T18:24:25.306Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=atkn_c9e8bdd70d22fbc55cee8b82db2cc0067dd83cab3eaa8940eabc9a890cb38b82
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-03-07T18:24:25.720Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=atkn_c9e8bdd70d22fbc55cee8b82db2cc0067dd83cab3eaa8940eabc9a890cb38b82 completed in 412 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"a0475d0fbf5e8d641a07ff8c5e224347"
 - x-request-id: b67cb7f5-6bc2-4716-9a17-79da4aaeb1dd
    
2023-03-07T18:24:25.956Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=atkn_c9e8bdd70d22fbc55cee8b82db2cc0067dd83cab3eaa8940eabc9a890cb38b82 completed in 647 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"8687f5c1ba96a7d94578b6a3029054d3"
 - x-request-id: 3946babb-3eb9-46bc-948c-15b23d3358f3
    
2023-03-07T18:24:25.959Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=atkn_c9e8bdd70d22fbc55cee8b82db2cc0067dd83cab3eaa8940eabc9a890cb38b82&destination=https%3A%2F%2Fclub-builder-testing.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-03-07T18:24:26.440Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=atkn_c9e8bdd70d22fbc55cee8b82db2cc0067dd83cab3eaa8940eabc9a890cb38b82&destination=https%3A%2F%2Fclub-builder-testing.myshopify.com%2Fadmin completed in 479 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"2362646f37ca75c504dcdd3725ae1414"
 - x-request-id: cd6c48fa-949c-4df8-b71b-2a08b711c48d
    
2023-03-07T18:24:26.443Z: Setting session store...
2023-03-07T18:24:26.450Z: Getting development theme...
2023-03-07T18:24:27.213Z: Request to https://club-builder-testing.myshopify.com/admin/api/unstable/themes/129076690996.json?fields=id completed in 759 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: 551c279c-0e69-4f09-b313-84ff84a97a8d
    
2023-03-07T18:24:27.218Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2023-03-07T18:24:27.218Z: Getting session store...
2023-03-07T18:24:27.220Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2023-03-07T18:24:27.220Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-03-07T18:24:27.220Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-03-07T18:24:27.231Z: Obtaining the dependency manager in directory /Users/Mac-Mini/Shopify/the-clubroom-shopify-theme...
2023-03-07T18:24:27.238Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Users/Mac-Mini/Shopify/the-clubroom-shopify-theme

2023-03-07T18:24:27.579Z: Request to https://accounts.shopify.com/oauth/introspection completed in 357 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"8c998fd3bf4abba86f7ff5db8ae897b5"
 - x-request-id: ca7be5bd-b879-4dcd-9692-2e82ba044996
    
2023-03-07T18:24:27.581Z: The identity token is valid: true
2023-03-07T18:24:27.581Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-03-07T18:24:27.589Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Users/Mac-Mini/Shopify/the-clubroom-shopify-theme

2023-03-07T18:24:27.605Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle -v
  · Working directory: /Users/Mac-Mini/Shopify/the-clubroom-shopify-theme

2023-03-07T18:24:27.708Z: Reading the content of file at /opt/homebrew/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2023-03-07T18:24:27.709Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle install
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-03-07T18:24:27.743Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 490 ms
With response headers:
 - x-request-id: d84e615c-493b-4665-b7cf-735e89c84678
    
2023-03-07T18:24:27.743Z: Analytics event sent: {
  "command": "theme dev",
  "time_start": 1678213464066,
  "time_end": 1678213467226,
  "total_time": 3160,
  "success": true,
  "cli_version": "3.44.1",
  "ruby_version": "3.2.1",
  "node_version": "19.7.0",
  "is_employee": false,
  "uname": "darwin arm64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "env_shell": "zsh",
  "env_device_id": "5b718c8dc6c226c8c4a6367f78856093065b32dc",
  "env_cloud": "localhost",
  "env_package_manager": "pnpm",
  "cmd_all_launcher": "unknown",
  "cmd_all_topic": "theme",
  "cmd_all_plugin": "@shopify/theme",
  "args": "--store https://club-builder-testing.myshopify.com --verbose",
  "env_plugin_installed_all": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-03-07T18:24:27.743Z: Completed command theme dev
2023-03-07T18:24:27.885Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle exec /opt/homebrew/opt/ruby/bin/ruby /opt/homebrew/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme serve . --live-reload hot-reload --theme 129076690996
  · Working directory: /Users/Mac-Mini/Shopify/the-clubroom-shopify-theme

┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ DEBUG GET https://club-builder-testing.myshopify.com/admin/api/unstable/themes.json with X-Request-Id: 8f292023-d3a6-4454-9bce-082f0ba1552c
┃ * Syncing theme #129076690996 on club-builder-testing.myshopify.com
┃ DEBUG GET https://club-builder-testing.myshopify.com/admin/api/unstable/themes/129076690996/assets.json with X-Request-Id: d0bbc6ce-c566-4f38-96e8-c6073faba1df
┃ DEBUG ignore package-lock.json
┃ DEBUG ignore package.json
┃                                                   0%  
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.88s) ━━
✗ An unexpected error occurred.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

Error
    at execCLI2 (file:///opt/homebrew/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:55:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Reproduction steps

1. It worked fine 10 mins before. 
2. I updated the Shopify CLI, restarted my mac
3. Tried again, can't get success

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.44.1 darwin-arm64 node-v19.7.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.7.0

**Comment by ulziibat-n** [comment]
✗ An unexpected error occurred.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```
Error
    at execCLI2 (file:///opt/homebrew/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:55:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ulziibat-n** [comment]
Now it's working fine. It maybe my fault. Thanks @Arkham
