### ISSUE TITLE
[Bug]: TypeError following the "QR code example app" tutorial

### ISSUE THREAD

**Issue by nicantonoff** [Shopify/cli#1612]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

According to the tutorial everything should have worked normally.

### Actual behavior

The app was created using the CLI command "npm init @shopify/app@latest" and I continued to follow the example app tutorial step by step.
All goes well in the frontend section, but when I reach step 3 of the backend "Connect the database", especifically item 3, after saving the shopify.js file, nodemon says the app crashed. The error is "TypeError: this.db.all is not a function" on file "web/qr-codes-db.js:207".

I've contacted Shopify's support and after some back and forth with Partner Support Specialist Jean, he recommended I opened an issue here. The ticket ID was 36672094.
Here's the link to the GitHub repository in the exact moment the problem started: https://github.com/nicantonoff/shopify-blue-dew
I've already tried to create this app from zero 3 times on windows 10 and 1 time on ubuntu WSL2. Nothing changes.

### Verbose output

```shell
> npm run dev --verbose

npm verb cli C:\Program Files\nodejs\node.exe C:\Users\nicol\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@9.5.1
npm info using node@v18.14.0
npm verb title npm run dev
npm verb argv "run" "dev" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_38_619Z-
npm verb logfile C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_38_619Z-debug-0.log

> blue-dew-3@1.0.0 dev
> shopify app dev

╭─ info ───────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Using your previous dev settings:                                           │
│                                                                              │
│    • Org:          Nicolas Antonoff                                          │
│    • App:          blue-dew-3                                                │
│    • Dev store:    blue-dew-testing.myshopify.com                            │
│    • Update URLs:  Always                                                    │
│                                                                              │
│  To reset your default dev config, run `npm run dev -- --reset`              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯


2023-03-15 18:51:47 | backend  | npm
2023-03-15 18:51:47 | backend  |  verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
2023-03-15 18:51:47 | backend  | npm info using npm@9.3.1
2023-03-15 18:51:47 | backend  | npm info using node@v18.14.0
2023-03-15 18:51:47 | backend  | npm verb title npm prefix
2023-03-15 18:51:47 | backend  | npm verb argv "prefix" "--global"
2023-03-15 18:51:47 | backend  | npm verb logfile logs-max:10 dir:C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_47_274Z-
2023-03-15 18:51:47 | backend  | npm verb logfile C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_47_274Z-debug-0.log
2023-03-15 18:51:47 | backend  | npm verb exit 0
2023-03-15 18:51:47 | backend  | npm info ok 
2023-03-15 18:51:47 | frontend | npm verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
2023-03-15 18:51:47 | frontend | npm info using npm@9.3.1
2023-03-15 18:51:47 | frontend | npm info using node@v18.14.0
2023-03-15 18:51:47 | frontend | npm verb title npm prefix
2023-03-15 18:51:47 | frontend | npm verb argv "prefix" "--global"
2023-03-15 18:51:47 | frontend | npm verb logfile logs-max:10 dir:C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_47_286Z-
2023-03-15 18:51:47 | frontend | npm verb logfile C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_47_286Z-debug-0.log
2023-03-15 18:51:47 | frontend | npm verb exit 0
2023-03-15 18:51:47 | frontend | npm info ok 
2023-03-15 18:51:47 | backend  | npm
2023-03-15 18:51:47 | backend  |  verb cli C:\Program Files\nodejs\node.exe C:\Users\nicol\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
2023-03-15 18:51:47 | backend  | npm info using npm@9.5.1
2023-03-15 18:51:47 | backend  | npm info using node@v18.14.0
2023-03-15 18:51:47 | backend  | npm verb title npm run dev
2023-03-15 18:51:47 | backend  | npm verb argv "run" "dev"
2023-03-15 18:51:47 | backend  | npm verb logfile logs-max:10 dir:C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_47_854Z-
2023-03-15 18:51:47 | frontend | npm verb cli C:\Program Files\nodejs\node.exe C:\Users\nicol\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
2023-03-15 18:51:47 | frontend | npm info using npm@9.5.1
2023-03-15 18:51:47 | frontend | npm info using node@v18.14.0
2023-03-15 18:51:47 | frontend | npm verb title npm run dev
2023-03-15 18:51:47 | frontend | npm verb argv "run" "dev"
2023-03-15 18:51:47 | frontend | npm verb logfile logs-max:10 dir:C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_47_861Z-
2023-03-15 18:51:47 | backend  | npm verb logfile C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_47_854Z-debug-0.log
2023-03-15 18:51:47 | frontend | npm verb logfile C:\Users\nicol\AppData\Local\npm-cache\_logs\2023-03-15T18_51_47_861Z-debug-0.log
2023-03-15 18:51:47 | backend  |
2023-03-15 18:51:47 | backend  | > dev
2023-03-15 18:51:47 | backend  | > cross-env NODE_ENV=development nodemon index.js --ignore ./frontend
2023-03-15 18:51:47 | backend  |
2023-03-15 18:51:47 | frontend |
2023-03-15 18:51:47 | frontend | > dev
2023-03-15 18:51:47 | frontend | > vite
2023-03-15 18:51:47 | frontend |
2023-03-15 18:51:48 | backend  | [nodemon] 2.0.20
2023-03-15 18:51:48 | backend  | [nodemon] to restart at any time, enter `rs`
2023-03-15 18:51:48 | backend  | [nodemon] watching path(s): *.*
2023-03-15 18:51:48 | backend  | [nodemon] watching extensions: js,mjs,json
2023-03-15 18:51:48 | backend  | [nodemon] starting `node index.js`
2023-03-15 18:51:48 | frontend |
2023-03-15 18:51:48 | frontend |   vite v2.9.15 dev server running at:
2023-03-15 18:51:48 | frontend |
2023-03-15 18:51:48 | frontend |   > Network:  http://26.189.222.0:60532/
2023-03-15 18:51:48 | frontend |   > Network:  http://192.168.27.3:60532/
2023-03-15 18:51:48 | frontend |   > Local:    http://localhost:60532/
2023-03-15 18:51:48 | frontend |
2023-03-15 18:51:48 | frontend |   ready in 273ms.
2023-03-15 18:51:48 | frontend |
2023-03-15 18:51:48 | backend  | [shopify-api/INFO] version 6.2.0, environment Node v18.14.0
2023-03-15 18:51:48 | backend  | file:///G:/Programa%C3%A7%C3%A3o/Enfoque/blue-dew-3%20partial/web/qr-codes-db.js:207
2023-03-15 18:51:48 | backend  |       this.db.all(sql, params, (err, result) => {
2023-03-15 18:51:48 | backend  |               ^
2023-03-15 18:51:48 | backend  |
2023-03-15 18:51:48 | backend  | TypeError: this.db.all is not a function
2023-03-15 18:51:48 | backend  |     at file:///G:/Programa%C3%A7%C3%A3o/Enfoque/blue-dew-3%20partial/web/qr-codes-db.js:207:15
2023-03-15 18:51:48 | backend  |     at new Promise (<anonymous>)
2023-03-15 18:51:48 | backend  |     at Object.__query (file:///G:/Programa%C3%A7%C3%A3o/Enfoque/blue-dew-3%20partial/web/qr-codes-db.js:206:12)
2023-03-15 18:51:48 | backend  |     at Object.__hasQrCodesTable (file:///G:/Programa%C3%A7%C3%A3o/Enfoque/blue-dew-3%20partial/web/qr-codes-db.js:166:29)
2023-03-15 18:51:48 | backend  |     at Object.init (file:///G:/Programa%C3%A7%C3%A3o/Enfoque/blue-dew-3%20partial/web/qr-codes-db.js:176:40)
2023-03-15 18:51:48 | backend  |     at file:///G:/Programa%C3%A7%C3%A3o/Enfoque/blue-dew-3%20partial/web/shopify.js:12:11
2023-03-15 18:51:48 | backend  |     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
2023-03-15 18:51:48 | backend  |
2023-03-15 18:51:48 | backend  | Node.js v18.14.0
2023-03-15 18:51:48 | backend  | [nodemon] app crashed - waiting for file changes before starting...


  Press `p` to open your browser. Press `q` to quit.


Preview URL: https://0225-177-170-254-82.sa.ngrok.io?shop=blue-dew-testing.myshopify.com&host=Ymx1ZS1kZXctdGVzdGluZy5teXNob3BpZnkuY29tL2FkbWlu
```

### Reproduction steps

I'm not sure if this is reproducible, a friend of mine followed the same tutorial and on his PC all worked fine. But anyway:
1. create a new app with "npm init @shopify/app@latest"
2. follow the frontend tutorial: https://shopify.dev/docs/apps/getting-started/build-app-example/frontend
3. follow the backend tutorial until step 3 item 3: https://shopify.dev/docs/apps/getting-started/build-app-example/backend
4. just before continuing to the "Add API endpoints" part of the tutorial, run the command "npm run dev"

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

Integrated VSCode terminal or PowerShell

### Node version (run `node -v` if you're not sure)

v18.14.0

**Comment by nicantonoff** [comment]
The error is reproducible upon cloning the repository.

**Comment by paulomarg** [comment]
Hey @nicantonoff, thank you for reporting this. I believe this issue is what we fixed [in this PR](https://github.com/Shopify/shopify-app-examples/pull/138). As part of that change, we also fixed the tutorial so that it wouldn't happen any more.

To be extra sure, I just created a fresh app today and went over the tutorial instructions, and I no longer see that error. Can you please confirm that you're still seeing this issue even with that PR in place?

**Comment by nicantonoff** [comment]
Hi @paulomarg, sorry for the late reply. I've just created a new app, followed the tutorial and found no issue, all worked perfectly! Thanks!
