### ISSUE TITLE
[Bug]: After migrating from CLI V2 to V3, token invalidation frequently occurs

### ISSUE THREAD

**Issue by forwells** [Shopify/cli#163]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Other

### Expected behavior

According to the introduction of shopify.dev, the project in the web directory after V2 -> V3 should be the main program code of the embedded application front-end, which is expected to run normally, but the jwt session token is often invalid.

### Actual behavior

Frequent token invalidation
![image](https://user-images.githubusercontent.com/32950945/179436225-c384e5f8-ae6f-405b-85ba-dab56c852f22.png)

### Stack trace

```shell
InvalidJwtError: Failed to parse session token 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvbmUwNzEzLm15c2hvcGlmeS5jb21cL2FkbWluIiwiZGVzdCI6Imh0dHBzOlwvXC9uZTA3MTMubXlzaG9waWZ5LmNvbSIsImF1ZCI6ImE2YmUwZjBkNDZmNTY4MGMyNmJhMWQ3MDVjMDgxMjA4Iiwic3ViIjoiNzE4MDEwMTIzMDgiLCJleHAiOjE2NTgxMTAwMjgsIm5iZiI6MTY1ODEwOTk2OCwiaWF0IjoxNjU4MTA5OTY4LCJqdGkiOiIxZTVjMTY0ZS1hOTc2LTQyYTMtYTM1NS00OTlhOTBkY2MxNzIiLCJzaWQiOiJkNDJjNjMzMDJmMGFiYzIwZGVlNGYyOTAzMDUzYjYwOTM1MDg0YmMzZmVkNGFmYThiOTY4YjRmMDA5MTNjNmJmIn0.jAY4X_fhJ3nJ5gAOkAqJ8vxiWkkscqIvDXEhRhqLon8': jwt not active
frontend |     at InvalidJwtError.ShopifyError [as constructor] (/www/wwwroot/publicapp/ep_lens/web/node_modules/@shopify/shopify-api/dist/error.js:13:28)
frontend |     at new InvalidJwtError (/www/wwwroot/publicapp/ep_lens/web/node_modules/@shopify/shopify-api/dist/error.js:39:42)
frontend |     at decodeSessionToken (/www/wwwroot/publicapp/ep_lens/web/node_modules/@shopify/shopify-api/dist/utils/decode-session-token.js:23:15)
frontend |     at Object.getCurrentSessionId (/www/wwwroot/publicapp/ep_lens/web/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:211:69)
frontend |     at Object.<anonymous> (/www/wwwroot/publicapp/ep_lens/web/node_modules/@shopify/shopify-api/dist/utils/load-current-session.js:19:46)
frontend |     at step (/www/wwwroot/publicapp/ep_lens/web/node_modules/tslib/tslib.js:144:27)
frontend |     at Object.next (/www/wwwroot/publicapp/ep_lens/web/node_modules/tslib/tslib.js:125:57)
frontend |     at /www/wwwroot/publicapp/ep_lens/web/node_modules/tslib/tslib.js:118:75
frontend |     at new Promise (<anonymous>)
frontend |     at Object.__awaiter (/www/wwwroot/publicapp/ep_lens/web/node_modules/tslib/tslib.js:114:16)
```

### Reproduction steps

1. Develop using the vitejs project template provided in CLI V2 and deploy at least one webhook and graphql request
2. Migrate project code to CLI V3 version
3. There was a problem

### Operating System

Windows10 WSL2 (Ubuntu 20.04)

### Shopify CLI version (check your project's `package.json` if you're not sure)

V3

### Shell

bash

### Node version (run `node -v` if you're not sure)

v16.14.0

### What language and version are you using in your application?

Node 16.14.0

**Comment by forwells** [comment]
It's like realated this topic 
https://github.com/Shopify/shopify-api-node/issues/137#issue-832057736
