### ISSUE TITLE
[Bug]: Bundler not found When installing Shopify Cli 3.x

### ISSUE THREAD

**Issue by ErikZoeppig** [Shopify/cli#1634]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When running Shopify Theme dev it should redirect me to Partner Login and create Links for Development like Shopify Theme serve on CLi 2.x

### Actual behavior

Showing up following Error:
Error: Bundler not found
    at validateBundler (file:///C:/Users/ErikZ%C3%B6ppig/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:176:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validateRubyEnv (file:///C:/Users/ErikZ%C3%B6ppig/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:145:5)
    at async installCLIDependencies (file:///C:/Users/ErikZ%C3%B6ppig/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:128:5)

### Verbose output

```shell
2023-03-21T12:27:07.892Z: Running command theme dev
  shopify:theme:dev init version: @oclif/core@2.1.4 argv: [ '--verbose' ] +0ms
2023-03-21T12:27:07.919Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-03-21T12:27:07.920Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store hofmanns-shop.myshopify.com:
[]

2023-03-21T12:27:07.922Z: Getting session store...
2023-03-21T12:27:07.926Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "hofmanns-shop.myshopify.com"
  }
}

2023-03-21T12:27:07.930Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-03-21T12:27:07.931Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-03-21T12:27:08.210Z: Request to https://accounts.shopify.com/oauth/introspection completed in 268 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"eb0bf9e64d18799ea77f169dbf90d6ea"
 - x-request-id: dfea1012-b312-4dd8-8cf6-a8bc30b53a2d
    
2023-03-21T12:27:08.217Z: The identity token is valid: true
2023-03-21T12:27:08.218Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-03-21T12:27:08.219Z: The current session is valid but needs refresh. Refreshing...
2023-03-21T12:27:08.221Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_8a6388bad782824fa8ecaba1b2d36f512441a3a1a724af3d6e8516a0feef0382&refresh_token=atkn_4453731b73d7bcbfcfbb18335958b811507333a14486f9de67972feb6dbe266e&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-03-21T12:27:08.614Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_8a6388bad782824fa8ecaba1b2d36f512441a3a1a724af3d6e8516a0feef0382&refresh_token=atkn_4453731b73d7bcbfcfbb18335958b811507333a14486f9de67972feb6dbe266e&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 390 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"0a94a593870087a1526e6e7acbfa727b"
 - x-request-id: ef713800-bf81-4eb5-9a3b-8c8e245ad973
    
2023-03-21T12:27:08.619Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=atkn_8a6f7f7c818f8fcd0beb7c18065a0b90eaece9af45ae9aa85309d8002f2c3552
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-03-21T12:27:08.622Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=atkn_8a6f7f7c818f8fcd0beb7c18065a0b90eaece9af45ae9aa85309d8002f2c3552
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-03-21T12:27:08.879Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=atkn_8a6f7f7c818f8fcd0beb7c18065a0b90eaece9af45ae9aa85309d8002f2c3552 completed in 253 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"eb6024581a3265f853a8df523a3d89ba"
 - x-request-id: 48aabf80-6a50-4930-a3d7-df113ab34f14
    
2023-03-21T12:27:09.125Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=atkn_8a6f7f7c818f8fcd0beb7c18065a0b90eaece9af45ae9aa85309d8002f2c3552 completed in 500 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"6afaf017d51003188b5f2f5ca4c72cc9"
 - x-request-id: 2aee7122-b828-4577-b83d-9ae068041318
    
2023-03-21T12:27:09.130Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=atkn_8a6f7f7c818f8fcd0beb7c18065a0b90eaece9af45ae9aa85309d8002f2c3552&destination=https%3A%2F%2Fhofmanns-shop.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-03-21T12:27:09.398Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=atkn_8a6f7f7c818f8fcd0beb7c18065a0b90eaece9af45ae9aa85309d8002f2c3552&destination=https%3A%2F%2Fhofmanns-shop.myshopify.com%2Fadmin completed in 264 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"c7182e196dce253f116dfa93de380fe1"
 - x-request-id: d853afc6-2f3a-4354-900d-5dd9c331dffd
    
2023-03-21T12:27:09.403Z: Setting session store...
2023-03-21T12:27:09.417Z: Getting development theme...
2023-03-21T12:27:09.775Z: Request to https://hofmanns-shop.myshopify.com/admin/api/unstable/themes/136477606116.json?fields=id completed in 355 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: 0698990e-bfd3-430d-9203-54a93ff85bcd
    
2023-03-21T12:27:09.780Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2023-03-21T12:27:09.781Z: Getting session store...
2023-03-21T12:27:09.783Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2023-03-21T12:27:09.786Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-03-21T12:27:09.786Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-03-21T12:27:09.802Z: Obtaining the dependency manager in directory .....
2023-03-21T12:27:09.815Z: 
Running system process:
  · Command: ruby -v
  · Working directory: C:\Users\ErikZöppig\OneDrive - ABRIO GmbH\Abrio Projects\HofmannsTheme

2023-03-21T12:27:10.021Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 187 ms
With response headers:
 - x-request-id: 0aa3a131-3411-4f6b-8876-cdd11b35a424
    
2023-03-21T12:27:10.023Z: Analytics event sent: {
  "command": "theme dev",
  "time_start": 1679401627893,
  "time_end": 1679401629795,
  "total_time": 1902,
  "success": true,
  "cli_version": "3.44.1",
  "ruby_version": "3.1.3",
  "node_version": "18.15.0",
  "is_employee": false,
  "uname": "windows amd64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "env_shell": "cmd.exe",
  "env_device_id": "729ea1ae039ca906605dcd1d39afa53e5d05fcad",
  "env_cloud": "localhost",
  "env_package_manager": "npm",
  "cmd_all_launcher": "unknown",
  "cmd_all_topic": "theme",
  "cmd_all_plugin": "@shopify/theme",
  "args": "--verbose",
  "env_plugin_installed_all": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-03-21T12:27:10.030Z: Completed command theme dev
2023-03-21T12:27:10.032Z: Request to https://accounts.shopify.com/oauth/introspection completed in 243 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"2f8e89ab0c8d3da68daa9e23746d5cf3"
 - x-request-id: e2375c6d-db12-4cd3-be20-a9902b92dfc0
    
2023-03-21T12:27:10.035Z: The identity token is valid: true
2023-03-21T12:27:10.035Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-03-21T12:27:10.049Z: 
Running system process:
  · Command: ruby -v
  · Working directory: C:\Users\ErikZöppig\OneDrive - ABRIO GmbH\Abrio Projects\HofmannsTheme

Running system process:
  · Command: bundle -v
  · Working directory: C:\Users\ErikZöppig\OneDrive - ABRIO GmbH\Abrio Projects\HofmannsTheme

Error: Bundler not found
    at validateBundler (file:///C:/Users/ErikZ%C3%B6ppig/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:176:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validateRubyEnv (file:///C:/Users/ErikZ%C3%B6ppig/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:145:5)
    at async installCLIDependencies (file:///C:/Users/ErikZ%C3%B6ppig/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:128:5)
    at async execCLI2 (file:///C:/Users/ErikZ%C3%B6ppig/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:29:5)
```

### Reproduction steps

1.uninstall shopify cli 2.0 with gem uninstall shopify-cli
2.run npm install -g @shopify/cli @shopify/theme
3.open project directory
4.run shopify theme dev --> Error

5. run gem install bundler
6. gem list shows : bundler (2.4.9, default: 2.3.26)
7. run shopify theme dev --> Error

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

Current Shopify CLI version: 3.44.1

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

v18.15.0

**Comment by amcaplan** [comment]
I wonder if this has to do with Windows paths acting funny when using non-ASCII characters. I also see the path contains spaces. Can you check if a directory with standard characters and no spaces has the same problem? (Bonus points if you can isolate whether spaces or non-ASCII is the issue.)

**Comment by ErikZoeppig** [comment]
bundler -v is printing the following error;

Cuz of that i ran gem install bundler. Probably has to do something with a global variable or stuff like this.

` C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:50:in `match?': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:50:in `chop_basename'
        from C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:374:in `plus'
        from C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:354:in `+'
        from C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:420:in `join'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/settings.rb:439:in `global_config_file'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/settings.rb:93:in `initialize'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:355:in `new'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:355:in `rescue in settings'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:352:in `settings'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/env.rb:20:in `report'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:71:in `request_issue_report_for'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:50:in `log_error'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:115:in `with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `load'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `<top (required)>'
        from C:/Ruby31-x64/bin/bundler:32:in `load'
        from C:/Ruby31-x64/bin/bundler:32:in `<main>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:311:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:307:in `root'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:326:in `app_config_path'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:353:in `settings'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/env.rb:20:in `report'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:71:in `request_issue_report_for'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:50:in `log_error'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:115:in `with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `load'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `<top (required)>'
        from C:/Ruby31-x64/bin/bundler:32:in `load'
        from C:/Ruby31-x64/bin/bundler:32:in `<main>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/shared_helpers.rb:15:in `root': Could not locate Gemfile (Bundler::GemfileNotFound)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:308:in `root'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:326:in `app_config_path'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:353:in `settings'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/env.rb:20:in `report'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:71:in `request_issue_report_for'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:50:in `log_error'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:115:in `with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `load'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `<top (required)>'
        from C:/Ruby31-x64/bin/bundler:32:in `load'
        from C:/Ruby31-x64/bin/bundler:32:in `<main>'
C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:50:in `match?': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:50:in `chop_basename'
        from C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:374:in `plus'
        from C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:354:in `+'
        from C:/Ruby31-x64/lib/ruby/3.1.0/pathname.rb:420:in `join'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/settings.rb:439:in `global_config_file'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/settings.rb:93:in `initialize'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:355:in `new'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:355:in `rescue in settings'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:352:in `settings'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/feature_flag.rb:21:in `block in settings_method'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:109:in `<class:CLI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:6:in `<module:Bundler>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:5:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:35:in `require_relative'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:35:in `block in <top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `load'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `<top (required)>'
        from C:/Ruby31-x64/bin/bundler:32:in `load'
        from C:/Ruby31-x64/bin/bundler:32:in `<main>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:311:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:307:in `root'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:326:in `app_config_path'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:353:in `settings'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/feature_flag.rb:21:in `block in settings_method'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:109:in `<class:CLI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:6:in `<module:Bundler>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:5:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:35:in `require_relative'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:35:in `block in <top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `load'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `<top (required)>'
        from C:/Ruby31-x64/bin/bundler:32:in `load'
        from C:/Ruby31-x64/bin/bundler:32:in `<main>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/shared_helpers.rb:15:in `root': Could not locate Gemfile (Bundler::GemfileNotFound)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:308:in `root'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:326:in `app_config_path'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler.rb:353:in `settings'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/feature_flag.rb:21:in `block in settings_method'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:109:in `<class:CLI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:6:in `<module:Bundler>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/cli.rb:5:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:35:in `require_relative'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:35:in `block in <top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `load'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.9/exe/bundler:4:in `<top (required)>'
        from C:/Ruby31-x64/bin/bundler:32:in `load'
        from C:/Ruby31-x64/bin/bundler:32:in `<main>' `

**Comment by Arkham** [comment]
I see, I think this is related to https://github.com/Shopify/cli/issues/868. The root cause is that Ruby doesn't play well with UTF8 characters in Windows paths and I think that bundler by default tries to look up gems in your user home. If you set a `BUNDLE_USER_HOME` environment variable and make it point to `C:\dev-local\bundler-home` does the problem go away?

Also you mentioned that a colleague of yours has a `ö` in their username and it's working. Are they using the same version of Windows, terminal, ruby? do they have special environment variables setup?

**Comment by ErikZoeppig** [comment]
Do I have to install bundler seperately into that local folder? My Collegue actually didnt setup anything extra instead of installing the CLI. His User Folder has ö in it and it works fine. Thats what brought us here. Hes using an older ruby version on same windows and same terminal.

**Comment by amcaplan** [comment]
@vnimani what OS and shell are you using? And are you also using special chars in the pathname?

**Comment by vnimani** [comment]
Windows 10 and I used both GitBash and Powershell. I did not work with either one.
