### ISSUE TITLE
[Bug]: .gitkeep created by cli but not allowed when running deploy

### ISSUE THREAD

**Issue by dossy** [Shopify/cli#1752]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

`.gitkeep` files should be ignored by the deployment mechanism

### Actual behavior

`.gitkeep` files are identified as being unsupported filetypes and result in a deployment error.

### Verbose output

```shell
# yarn --verbose deploy
yarn run v1.22.19
verbose 0.138529201 Checking for configuration file "/app/.npmrc".
verbose 0.13966682 Found configuration file "/app/.npmrc".
verbose 0.141450944 Checking for configuration file "/usr/local/share/.npmrc".
verbose 0.141957384 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.142196851 Checking for configuration file "/root/.npmrc".
verbose 0.142747702 Checking for configuration file "/app/.npmrc".
verbose 0.143439704 Found configuration file "/app/.npmrc".
verbose 0.146376016 Checking for configuration file "/app/.yarnrc".
verbose 0.147066558 Checking for configuration file "/usr/local/share/.yarnrc".
verbose 0.147359598 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.147955891 Checking for configuration file "/root/.yarnrc".
verbose 0.148332801 Checking for configuration file "/app/.yarnrc".
verbose 0.157696283 current time: 2023-04-03T15:02:43.684Z
$ shopify app deploy
?  Make the following changes to your extensions in Shopify Partners?
✔  Yes, deploy to push changes


Deploying your work to Shopify Partners. It will be part of [REDACTED]

 theme_extensions | Running theme check on your Theme app extension...
 theme_extensions | Checking /app/extensions/[REDACTED]-ext ...
 theme_extensions | 1 files inspected, 0 offenses detected, 0 offenses auto-correctable


╭─ error ──────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                              │
│  Invalid filename in your theme app extension: assets/.gitkeep                               │
│  Only these filetypes are supported in assets: .jpg, .js, .css, .png, .svg                   │
│                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯

verbose 15.07119445 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/opt/yarn-v1.22.19/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/opt/yarn-v1.22.19/lib/cli.js:750:123)
    at new ProcessTermError (/opt/yarn-v1.22.19/lib/cli.js:790:113)
    at /opt/yarn-v1.22.19/lib/cli.js:34406:30
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.19/lib/cli.js:310:30)
    at /opt/yarn-v1.22.19/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction steps

1. Generate a new Theme Extension using `yarn generate` 
2. Deploy it with `yarn deploy`

### Operating System

Debian GNU/Linux 11 (bullseye)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.14.2

### What language and version are you using in your application?

ruby 2.7.5p203 (2021-11-24 revision f69aeb8314)

**Comment by Arkham** [comment]
hi @dossy, thanks for reporting this. This has been fixed in the latest `3.45.0` release. Feel free to reopen if it's still not working for you :)
