### ISSUE TITLE
[Bug]: 3.45.0 has no webhook trigger command

### ISSUE THREAD

**Issue by ACEGuiPeng** [Shopify/cli#1783]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

webhook trigger command working

### Actual behavior

![image](https://user-images.githubusercontent.com/26544186/230717247-b8d67fd5-3f78-4441-9ca8-4a1fe81080ee.png)
Command 'webhook trigger' not found.

### Verbose output

```shell
Version 8.1.1
Usage: pnpm [command] [flags]
       pnpm [ -h | --help | -v | --version ]

Manage your dependencies:
      add                  Installs a package and any packages that it depends on. By default, any new package is installed as a prod dependency
      import               Generates a pnpm-lock.yaml from an npm package-lock.json (or npm-shrinkwrap.json) file
   i, install              Install all dependencies for a project
  it, install-test         Runs a pnpm install followed immediately by a pnpm test
  ln, link                 Connect the local project to another one
      prune                Removes extraneous packages
  rb, rebuild              Rebuild a package
  rm, remove               Removes packages from node_modules and from the project's package.json
      unlink               Unlinks a package. Like yarn unlink but pnpm re-installs the dependency after removing the external link
  up, update               Updates packages to their latest version based on the specified range

Review your dependencies:
      audit                Checks for known security issues with the installed packages
      licenses             Check licenses in consumed packages
  ls, list                 Print all the versions of packages that are installed, as well as their dependencies, in a tree-structure
      outdated             Check for outdated packages

Run your scripts:
      exec                 Executes a shell command in scope of a project
      run                  Runs a defined package script
      start                Runs an arbitrary command specified in the package's "start" property of its "scripts" object
   t, test                 Runs a package's "test" script, if one was provided

Other:
      pack
      publish              Publishes a package to the registry
      root

Manage your store:
      store add            Adds new packages to the pnpm store directly. Does not modify any projects or files outside the store
      store path           Prints the path to the active store directory
      store prune          Removes unreferenced (extraneous, orphan) packages from the store
      store status         Checks for modified packages in the store

Options:
  -r, --recursive          Run the command for each project in the workspace.
```

### Reproduction steps

1. install shopify cli with version 3.45.0
2. use command : shopify webhook trigger --topic app/uninstalled
3. 

### Operating System

Linux VM-8-7-opencloudos 5.4.119-19.0010.ocrelease.6 #1 SMP Fri Jul 1 16:17:14 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.0

### Node version (run `node -v` if you're not sure)

v16.20.0

### What language and version are you using in your application?

Ruby 3.0.0

**Comment by mhstnsc** [comment]
i get this issue as well.

**Comment by mhstnsc** [comment]
the command is not listed in `shopify commands`

**Comment by peterpisarcik** [comment]
Hello @alvaro-shopify, 

same issue here. This is the output using debug flags.

`DEBUG=* shopify webhook trigger`


```
2023-05-03T16:47:22.302Z config reading core plugin /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli
2023-05-03T16:47:22.302Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/package.json
2023-05-03T16:47:22.303Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/oclif.manifest.json
2023-05-03T16:47:22.303Z config:@shopify/cli using manifest from /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/oclif.manifest.json
2023-05-03T16:47:22.310Z config reading user plugins pjson /Users/peter/.local/share/@shopify/cli/package.json
2023-05-03T16:47:22.310Z config loadJSON /Users/peter/.local/share/@shopify/cli/package.json
2023-05-03T16:47:22.310Z config loading plugins [
  '@shopify/app',
  '@shopify/theme',
  '@shopify/plugin-did-you-mean',
  '@shopify/cli-hydrogen',
  '@oclif/plugin-help',
  '@oclif/plugin-plugins',
  '@oclif/plugin-commands'
]
2023-05-03T16:47:22.311Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/package.json
2023-05-03T16:47:22.311Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/package.json
2023-05-03T16:47:22.311Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/package.json
2023-05-03T16:47:22.311Z config reading core plugin /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@shopify/plugin-did-you-mean
2023-05-03T16:47:22.311Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@shopify/plugin-did-you-mean/package.json
2023-05-03T16:47:22.311Z config reading core plugin /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-commands
2023-05-03T16:47:22.311Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-commands/package.json
2023-05-03T16:47:22.311Z config reading core plugin /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-help
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-help/package.json
2023-05-03T16:47:22.312Z config reading core plugin /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-plugins
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-plugins/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@shopify/plugin-did-you-mean/oclif.manifest.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-commands/oclif.manifest.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-help/oclif.manifest.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/package.json
2023-05-03T16:47:22.312Z config reading core plugin /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/theme
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/theme/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/package.json
2023-05-03T16:47:22.312Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/package.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/package.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/package.json
2023-05-03T16:47:22.313Z config:@shopify/plugin-did-you-mean using manifest from /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@shopify/plugin-did-you-mean/oclif.manifest.json
2023-05-03T16:47:22.313Z config:@oclif/plugin-commands using manifest from /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-commands/oclif.manifest.json
2023-05-03T16:47:22.313Z config:@oclif/plugin-help using manifest from /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-help/oclif.manifest.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/Cellar/shopify-cli/package.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/Cellar/shopify-cli/package.json
2023-05-03T16:47:22.313Z config:@oclif/plugin-plugins using manifest from /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/Cellar/package.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/Cellar/package.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/theme/oclif.manifest.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/package.json
2023-05-03T16:47:22.313Z config loadJSON /opt/homebrew/package.json
2023-05-03T16:47:22.313Z config loadJSON /opt/package.json
2023-05-03T16:47:22.313Z config loadJSON /opt/package.json
2023-05-03T16:47:22.313Z config loadJSON /package.json
2023-05-03T16:47:22.313Z config loadJSON /package.json
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli',
  name: '@shopify/app'
}
    at Plugin.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/plugin.js:106:19)
    at async /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:464:17
    at async Promise.all (index 0)
    at async Config.loadPlugins (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:452:9)
    at async Config.loadCorePlugins (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:151:13)
    at async Config.loadPluginsAndCommands (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:143:9)
    at async Config.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:137:9)
    at async Config.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:78:9)
    at async run (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/main.js:43:20)
module: @oclif/core@2.1.4
task: loadPlugins
plugin: @shopify/cli
root: /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli
See more details with DEBUG=*
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli',
  name: '@shopify/app'
}
    at Plugin.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/plugin.js:106:19)
    at async /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:464:17
    at async Promise.all (index 0)
    at async Config.loadPlugins (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:452:9)
    at async Config.loadCorePlugins (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:151:13)
    at async Config.loadPluginsAndCommands (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:143:9)
    at async Config.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:137:9)
    at async Config.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:78:9)
    at async run (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/main.js:43:20)
module: @oclif/core@2.1.4
task: loadPlugins
plugin: @shopify/cli
root: /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli
See more details with DEBUG=*
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli',
  name: '@shopify/cli-hydrogen'
}
    at Plugin.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/plugin.js:106:19)
    at async /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:464:17
    at async Promise.all (index 3)
    at async Config.loadPlugins (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:452:9)
    at async Config.loadCorePlugins (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:151:13)
    at async Config.loadPluginsAndCommands (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:143:9)
    at async Config.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:137:9)
    at async Config.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:78:9)
    at async run (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/main.js:43:20)
module: @oclif/core@2.1.4
task: loadPlugins
plugin: @shopify/cli
root: /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli
See more details with DEBUG=*
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli',
  name: '@shopify/cli-hydrogen'
}
    at Plugin.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/plugin.js:106:19)
    at async /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:464:17
    at async Promise.all (index 3)
    at async Config.loadPlugins (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:452:9)
    at async Config.loadCorePlugins (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:151:13)
    at async Config.loadPluginsAndCommands (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:143:9)
    at async Config.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:137:9)
    at async Config.load (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/config/config.js:78:9)
    at async run (/opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@oclif/core/lib/main.js:43:20)
module: @oclif/core@2.1.4
task: loadPlugins
plugin: @shopify/cli
root: /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli
See more details with DEBUG=*
2023-05-03T16:47:22.314Z config:@shopify/theme using manifest from /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/theme/oclif.manifest.json
2023-05-03T16:47:22.314Z config config done
2023-05-03T16:47:22.314Z config start init hook
2023-05-03T16:47:22.315Z config init hook done
2023-05-03T16:47:22.315Z config runCommand webhook:trigger []
2023-05-03T16:47:22.315Z config start command_not_found hook
2023-05-03T16:47:22.331Z shopify:@shopify/plugin-did-you-mean:hooks:command_not_found start (import) /opt/homebrew/Cellar/shopify-cli/3.45.3/libexec/lib/node_modules/@shopify/cli/node_modules/@shopify/plugin-did-you-mean/dist/index.js
?  Command `webhook trigger` not found. Did you mean `theme language-server`?

>  (y) Yes, confirm
   (n) No, cancel

   Press ↑↓ arrows to select, enter or a shortcut to confirm

```

**Comment by joepagan** [comment]
Confusing as shit but the issue is not that the brew's `shopify-cli` package is installed but you are NOT prefixing your commands with `npm run` like the docs tell you to, that way you use the `@shopify/cli` package with the brew one installed.

bad:

```sh
shopify webhook trigger --topic ORDERS_PAID --api-version 2023-04 --delivery-method http --client-secret=x --address http://localhost:12345/api/webhooks
```

good:

```
npm run shopify webhook trigger --topic ORDERS_PAID --api-version 2023-04 --delivery-method http --client-secret=x --address http://localhost:12345/api/webhooks
```
