### ISSUE TITLE
[Bug]: shopify theme dev errors

### ISSUE THREAD

**Issue by spinturnix** [Shopify/cli#1810]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The localhost server should launch along with links to the editor and share URLs.

### Actual behavior

I'm seeing two errors, the first case appears to work with the "success" box including preview, customize, and share URLs. Then a moment later...

> Error
>     at execCLI2 (file:///opt/homebrew/Cellar/shopify-cli/3.45.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:59:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

And the second error happens if I run 'shopify theme dev' again, I'll see the "error" box with this message inside:

> request to https://CLIENTSTORE.myshopify.com/admin/api/unstable/themes/136493760744.json?fields=id failed, reason: read ECONNRESET

### Verbose output

```shell
2023-04-13T21:58:33.876Z: Running command theme dev
  shopify:theme:dev init version: @oclif/core@2.1.4 argv: [ '--verbose' ] +0ms
2023-04-13T21:58:33.889Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-04-13T21:58:33.889Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store private.myshopify.com:
[]

2023-04-13T21:58:33.889Z: Getting session store...
2023-04-13T21:58:33.891Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "private.myshopify.com"
  }
}

2023-04-13T21:58:33.891Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-04-13T21:58:33.891Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.45.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-04-13T21:58:34.097Z: Request to https://accounts.shopify.com/oauth/introspection completed in 201 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"c21379392720acec84900e038e61f612"
 - x-request-id: b99510d3-7603-4dbf-a1c7-6f552fe53d56

2023-04-13T21:58:34.099Z: The identity token is valid: true
2023-04-13T21:58:34.100Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false

2023-04-13T21:58:34.100Z: The current session is valid but needs refresh. Refreshing...
2023-04-13T21:58:34.101Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?[...]
With request headers:
 - User-Agent: Shopify CLI; v=3.45.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-04-13T21:58:34.432Z: Request to https://accounts.shopify.com/oauth/token?[...] completed in 330 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"1f28175736a4de07be269bcec5334230"
 - x-request-id: 14208c87-3822-4831-aa89-4245e1ff27ff

2023-04-13T21:58:34.435Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?[...]
With request headers:
 - User-Agent: Shopify CLI; v=3.45.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-04-13T21:58:34.435Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?[...]
With request headers:
 - User-Agent: Shopify CLI; v=3.45.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-04-13T21:58:34.628Z: Request to https://accounts.shopify.com/oauth/token?[...] completed in 190 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"f8875c9f7027cefcc110523273436d4d"
 - x-request-id: 4ab3119a-5204-4c25-94ad-1599ed15a33f

2023-04-13T21:58:34.877Z: Request to https://accounts.shopify.com/oauth/token?[...] completed in 440 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"ada1d0198a2803b2c45258164f693458"
 - x-request-id: bedfbdb9-1c91-4636-9954-0e400696893e

2023-04-13T21:58:34.879Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?[...]
With request headers:
 - User-Agent: Shopify CLI; v=3.45.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-04-13T21:58:35.096Z: Request to https://accounts.shopify.com/oauth/token?[...] completed in 215 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"03b3b63c4b66912de014d7e4d480ac3f"
 - x-request-id: 1a24f841-b2c7-417a-bf17-58f1da20d67f

2023-04-13T21:58:35.099Z: Setting session store...
2023-04-13T21:58:35.106Z: Getting development theme...
2023-04-13T21:58:35.479Z: Request to https://private.myshopify.com/admin/api/unstable/themes/136493760744.json?fields=id completed in 368 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: 8cac45f4-00d7-469d-a6f5-21898e43c441

╭─ success ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                │
│  Preview your theme                                                                                                                            │
│    • http://127.0.0.1:9292                                                                                                                     │
│                                                                                                                                                │
│  Next steps                                                                                                                                    │
│    • Customize your theme at the theme editor                                                                                                  │
│    • Share your theme preview                                                                                                                  │
│                                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

2023-04-13T21:58:35.517Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2023-04-13T21:58:35.517Z: Getting session store...
2023-04-13T21:58:35.518Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2023-04-13T21:58:35.518Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-04-13T21:58:35.518Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.45.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-04-13T21:58:35.527Z: Obtaining the dependency manager in directory .....
2023-04-13T21:58:35.529Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Users/trevorgarner/Clients/Private/site/shopify

2023-04-13T21:58:35.675Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 136 ms
With response headers:
 - x-request-id: 13d84ee1-8166-463b-bffa-37abf72c2183

2023-04-13T21:58:35.676Z: Analytics event sent: {
  "command": "theme dev",
  "time_start": 1681423113877,
  "time_end": 1681423115524,
  "total_time": 1647,
  "success": true,
  "cli_version": "3.45.1",
  "ruby_version": "3.2.2",
  "node_version": "19.9.0",
  "is_employee": false,
  "uname": "darwin arm64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "env_shell": "zsh",
  "env_device_id": "3a3a87edae04d35ad19790c85a07b1501e3bc8c1",
  "env_cloud": "localhost",
  "env_package_manager": "npm",
  "cmd_all_launcher": "unknown",
  "cmd_all_topic": "theme",
  "cmd_all_plugin": "@shopify/theme",
  "args": "--verbose",
  "env_plugin_installed_all": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-04-13T21:58:35.676Z: Completed command theme dev
2023-04-13T21:58:35.711Z: Request to https://accounts.shopify.com/oauth/introspection completed in 192 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"96148f093e8fe36544723b0ad6043445"
 - x-request-id: 1d9c96d2-7736-4f12-a696-1e854a78279b

2023-04-13T21:58:35.712Z: The identity token is valid: true
2023-04-13T21:58:35.712Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false

2023-04-13T21:58:35.717Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Users/trevorgarner/Clients/Private/site/shopify

2023-04-13T21:58:35.729Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle -v
  · Working directory: /Users/trevorgarner/Clients/Private/site/shopify

2023-04-13T21:58:35.814Z: Reading the content of file at /opt/homebrew/Cellar/shopify-cli/3.45.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2023-04-13T21:58:35.814Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle config set --local path /Users/trevorgarner/Library/Caches/shopify-gems-nodejs
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.45.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-04-13T21:58:35.892Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle config set --local without development:test
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.45.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-04-13T21:58:35.970Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle install
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.45.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-04-13T21:58:36.118Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle exec /opt/homebrew/opt/ruby/bin/ruby /opt/homebrew/Cellar/shopify-cli/3.45.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme serve /Users/trevorgarner/Clients/Private/site/shopify --live-reload hot-reload --theme 136493760744
  · Working directory: /Users/trevorgarner/Clients/Private/site/shopify

✗ An unexpected error occurred.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

Error
    at execCLI2 (file:///opt/homebrew/Cellar/shopify-cli/3.45.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:59:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Reproduction steps

run 'shopify theme dev' from any theme directory, I've tried multiple themes and stores with the same results.

This was working a day ago, I'm not sure what changed to cause the error.

I've found a couple of similar issues, though their solutions don't seem to apply:

- https://github.com/Shopify/cli/issues/1485
- https://github.com/Shopify/cli/issues/1574

### Operating System

macOS Ventura 13.3.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.42, updated to 3.45.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18.12.0, updated to 18.16.0

**Comment by alvaro-shopify** [comment]
Hi. I'm not sure why that error is produced. Let me ping @Shopify/theme-developer-tools because they have more context about the `themes` commands errors.

Sorry for inconveniences

**Comment by HandHugs** [comment]
This issue is also happening to me.

**Comment by spinturnix** [comment]
Hey @HandHugs and @elizabeth-aplo,

I forgot to follow up here, but my issue was a misconfiguration between my router and modem. The exact solution is still vague to me, but it's since been resolved.

If you're still having issues, try using a VPN, that was my workaround.

**Comment by shayanabbas** [comment]
@alvaro-shopify 

I am getting same issue, for some reason its giving 422 error on theme.scss.css, It happend when i change the color code #ffffff to variable $white.


![Screenshot 2023-07-21 at 3 01 00 PM](https://github.com/Shopify/cli/assets/5176243/ed2351e1-e9a8-4480-a074-46e281c85ed5)

DEBUG GET https://wello2-international.myshopify.com/admin/api/unstable/themes.json with request_id: f6a6e683-9f9a-429b-befa-67c86db12512
* Syncing theme #151078043987 on test.myshopify.com
DEBUG GET https://test.myshopify.com/admin/api/unstable/themes/151078043987/assets.json with request_id: d9655ad1-20c5-4a7a-8ea7-e8d4cba23570
                                                                                                      100%
[2023-07-21 14:58:31] INFO  WEBrick 1.7.0
[2023-07-21 14:58:31] INFO  ruby 3.2.2 (2023-03-30) [x86_64-darwin22]
[2023-07-21 14:58:31] INFO  WEBrick::HTTPServer#start: pid=40167 port=9292
[2023-07-21 14:58:43] ERROR bad URI `V�㹓�ټ\x16\x12��\x01��m���'.
[2023-07-21 14:58:43] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03\x18�h߽��\x02Ns]�Dj\x01=\b�m;\x06�S��\x1AL�=��S LK�Q��NM�\x16�F\x19�%`�\x01��� �\\F9׶�\v�\x00 JJ\x13\x01\x13\x02\x13\x03�+�/�,�0̨̩�\x13�\x14\x00�\x00�\x00/\x005\x01\x00\x01�::\x00\x00\x00\x12\x00\x00\x00\x17\x00\x00\x00\r\x00\x14\x00\x12\x04\x03\b\x04\x04\x01\x05\x03\b\x05\x05\x01\b\x06\x06\x01\x02\x01\x00#\x00\x00\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\v\x00\x02\x01\x00\x00'.

**Comment by shayanabbas** [comment]
actually my fault, The variable name was wrong.
