### ISSUE TITLE
[Bug]: CLI won't run after upgrade to 3.45.2 with Ruby 3.2.2

### ISSUE THREAD

**Issue by verdant-spark** [Shopify/cli#1897]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Theme should be served locally

### Actual behavior

Local server throws error:
```
Internal Server Error
invalid name: "_ply_query_options[prefix]"
WEBrick/1.7.0 (Ruby/3.2.2/2023-03-30) at 127.0.0.1:9292
```

### Verbose output

```shell
D:\Shopify Dev\clients\grow-urban>shopify theme dev --store grow-urban-plants --verbose --password ****   
2023-05-03T07:37:22.035Z: Running command theme dev
  shopify:theme:dev init version: @oclif/core@2.1.4 argv: [ '--store', 'grow-urban-plants', '--verbose', '--password', '****' ] +0ms
2023-05-03T07:37:22.054Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-05-03T07:37:22.055Z: Getting development theme...
2023-05-03T07:37:22.501Z: Request to https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes/130399535312.json?fields=id completed in 434 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"68fbc04bd02421d3c6b1d986ba218af5"
 - x-request-id: e18fad05-d0b0-4660-b085-8518625007bd

╭─ success ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                       │
│  Preview your theme                                                                                                                                   │
│    • [1]]                                                                                                                                             │
│                                                                                                                                                       │
│  Next steps                                                                                                                                           │
│    • Customize your theme at the theme editor [2]                                                                                                     │
│    • Share your theme preview [3]                                                                                                                     │
│                                                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[1] http://127.0.0.1:9292
[2] https://grow-urban-plants.myshopify.com/admin/themes/130399535312/editor
[3] https://grow-urban-plants.myshopify.com/?preview_theme_id=130399535312

2023-05-03T07:37:22.647Z: 
Running system process:
  · Command: ruby -v
  · Working directory: D:\Shopify Dev\clients\grow-urban

2023-05-03T07:37:22.706Z: 
Running system process:
  · Command: bundle -v
  · Working directory: D:\Shopify Dev\clients\grow-urban

2023-05-03T07:37:22.708Z: Obtaining the dependency manager in directory D:/Shopify Dev/clients/grow-urban...
2023-05-03T07:37:22.755Z: 
Running system process:
  · Command: ruby -v
  · Working directory: D:\Shopify Dev\clients\grow-urban

2023-05-03T07:37:22.953Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 173 ms
With response headers:
 - x-request-id: c40ea0c1-ca98-4dde-bf8c-1685806c4b50

2023-05-03T07:37:22.954Z: Analytics event sent: {
  "command": "theme dev",
  "time_start": 1683099442036,
  "time_end": 1683099442661,
  "total_time": 625,
  "success": true,
  "cli_version": "3.45.2",
  "ruby_version": "3.2.2",
  "node_version": "16.15.0",
  "is_employee": false,
  "uname": "windows amd64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "env_shell": "cmd.exe",
  "env_device_id": "187aca5e1a79320995b1aabf0b3654ec721da0cb",
  "env_cloud": "localhost",
  "env_package_manager": "npm",
  "cmd_all_launcher": "unknown",
  "cmd_all_topic": "theme",
  "cmd_all_plugin": "@shopify/theme",
  "args": "--store grow-urban-plants --verbose --password *****",
  "env_plugin_installed_all": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-05-03T07:37:22.954Z: Completed command theme dev
2023-05-03T07:37:23.381Z: Reading the content of file at C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2023-05-03T07:37:23.415Z: 
Running system process:
  · Command: bundle config set --local path C:\Users\Gary\AppData\Local\shopify-gems-nodejs\Cache
  · Working directory: C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-05-03T07:37:24.803Z: 
Running system process:
  · Command: bundle config set --local without development:test
  · Working directory: C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-05-03T07:37:26.204Z: 
Running system process:
  · Command: bundle install
  · Working directory: C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-05-03T07:37:28.411Z: 
Running system process:
  · Command: bundle exec ruby C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme serve D:\Shopify Dev\clients\grow-urban --live-reload hot-reload --theme 130399535312
  · Working directory: D:\Shopify Dev\clients\grow-urban

DEBUG GET https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes.json with request_id: 4b2cd7df-2455-44d9-981b-2219dd1254dd
* Syncing theme #130399535312 on grow-urban-plants.myshopify.com
DEBUG GET https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes/130399535312/assets.json with request_id: 59d1db73-46e3-4422-8416-646f45868f4f
DEBUG ignore node_modules/@discoveryjs/json-ext/package.json
DEBUG ignore node_modules/@jridgewell/gen-mapping/package.json
DEBUG ignore node_modules/@jridgewell/resolve-uri/package.json
DEBUG ignore node_modules/@jridgewell/set-array/package.json
DEBUG ignore node_modules/@jridgewell/source-map/package.json
DEBUG ignore node_modules/@jridgewell/sourcemap-codec/package.json
DEBUG ignore node_modules/@jridgewell/trace-mapping/package.json
DEBUG ignore node_modules/@types/eslint/package.json
DEBUG ignore node_modules/@types/eslint-scope/package.json
DEBUG ignore node_modules/@types/estree/package.json
DEBUG ignore node_modules/@types/json-schema/package.json
DEBUG ignore node_modules/@types/node/package.json
DEBUG ignore node_modules/@webassemblyjs/ast/package.json
DEBUG ignore node_modules/@webassemblyjs/floating-point-hex-parser/package.json
DEBUG ignore node_modules/@webassemblyjs/helper-api-error/package.json
DEBUG ignore node_modules/@webassemblyjs/helper-buffer/package.json
DEBUG ignore node_modules/@webassemblyjs/helper-numbers/package.json
DEBUG ignore node_modules/@webassemblyjs/helper-wasm-bytecode/package.json
DEBUG ignore node_modules/@webassemblyjs/helper-wasm-section/package.json
DEBUG ignore node_modules/@webassemblyjs/ieee754/package.json
DEBUG ignore node_modules/@webassemblyjs/leb128/package.json
DEBUG ignore node_modules/@webassemblyjs/utf8/package.json
DEBUG ignore node_modules/@webassemblyjs/wasm-edit/package.json
DEBUG ignore node_modules/@webassemblyjs/wasm-gen/package.json
DEBUG ignore node_modules/@webassemblyjs/wasm-opt/package.json
DEBUG ignore node_modules/@webassemblyjs/wasm-parser/package.json
DEBUG ignore node_modules/@webassemblyjs/wast-printer/package.json
DEBUG ignore node_modules/@webpack-cli/configtest/package.json
DEBUG ignore node_modules/@webpack-cli/info/package.json
DEBUG ignore node_modules/@webpack-cli/serve/package.json
DEBUG ignore node_modules/@xtuc/ieee754/package.json
DEBUG ignore node_modules/@xtuc/long/package.json
DEBUG ignore node_modules/acorn/package.json
DEBUG ignore node_modules/acorn-import-assertions/package.json
DEBUG ignore node_modules/ajv/lib/refs/data.json
DEBUG ignore node_modules/ajv/lib/refs/json-schema-draft-04.json
DEBUG ignore node_modules/ajv/lib/refs/json-schema-draft-06.json
DEBUG ignore node_modules/ajv/lib/refs/json-schema-draft-07.json
DEBUG ignore node_modules/ajv/lib/refs/json-schema-secure.json
DEBUG ignore node_modules/ajv/package.json
DEBUG ignore node_modules/ajv-keywords/package.json
DEBUG ignore node_modules/browserslist/package.json
DEBUG ignore node_modules/buffer-from/package.json
DEBUG ignore node_modules/caniuse-lite/package.json
DEBUG ignore node_modules/chrome-trace-event/package.json
DEBUG ignore node_modules/clone-deep/package.json
DEBUG ignore node_modules/colorette/package.json
DEBUG ignore node_modules/commander/package.json
DEBUG ignore node_modules/cross-spawn/package.json
DEBUG ignore node_modules/electron-to-chromium/chromium-versions.json
DEBUG ignore node_modules/electron-to-chromium/full-chromium-versions.json
DEBUG ignore node_modules/electron-to-chromium/full-versions.json
DEBUG ignore node_modules/electron-to-chromium/package.json
DEBUG ignore node_modules/electron-to-chromium/versions.json
DEBUG ignore node_modules/enhanced-resolve/package.json
DEBUG ignore node_modules/envinfo/package.json
DEBUG ignore node_modules/es-module-lexer/package.json
DEBUG ignore node_modules/escalade/package.json
DEBUG ignore node_modules/eslint-scope/package.json
DEBUG ignore node_modules/esrecurse/node_modules/estraverse/package.json
DEBUG ignore node_modules/esrecurse/package.json
DEBUG ignore node_modules/estraverse/package.json
DEBUG ignore node_modules/events/package.json
DEBUG ignore node_modules/fast-deep-equal/package.json
DEBUG ignore node_modules/fast-json-stable-stringify/benchmark/test.json
DEBUG ignore node_modules/fast-json-stable-stringify/package.json
DEBUG ignore node_modules/fastest-levenshtein/package.json
DEBUG ignore node_modules/find-up/package.json
DEBUG ignore node_modules/function-bind/package.json
DEBUG ignore node_modules/glob-to-regexp/package.json
DEBUG ignore node_modules/graceful-fs/package.json
DEBUG ignore node_modules/has/package.json
DEBUG ignore node_modules/has-flag/package.json
DEBUG ignore node_modules/import-local/package.json
DEBUG ignore node_modules/interpret/package.json
DEBUG ignore node_modules/is-core-module/core.json
DEBUG ignore node_modules/is-core-module/package.json
DEBUG ignore node_modules/is-plain-object/package.json
DEBUG ignore node_modules/isexe/package.json
DEBUG ignore node_modules/isobject/package.json
DEBUG ignore node_modules/jest-worker/package.json
DEBUG ignore node_modules/json-parse-even-better-errors/package.json
DEBUG ignore node_modules/json-schema-traverse/package.json
DEBUG ignore node_modules/kind-of/package.json
DEBUG ignore node_modules/loader-runner/package.json
DEBUG ignore node_modules/locate-path/package.json
DEBUG ignore node_modules/merge-stream/package.json
DEBUG ignore node_modules/mime-db/db.json
DEBUG ignore node_modules/mime-db/package.json
DEBUG ignore node_modules/mime-types/package.json
DEBUG ignore node_modules/neo-async/package.json
DEBUG ignore node_modules/node-releases/data/processed/envs.json
DEBUG ignore node_modules/node-releases/data/release-schedule/release-schedule.json
DEBUG ignore node_modules/node-releases/package.json
DEBUG ignore node_modules/p-limit/package.json
DEBUG ignore node_modules/p-locate/package.json
DEBUG ignore node_modules/p-try/package.json
DEBUG ignore node_modules/path-exists/package.json
DEBUG ignore node_modules/path-key/package.json
DEBUG ignore node_modules/path-parse/package.json
DEBUG ignore node_modules/picocolors/package.json
DEBUG ignore node_modules/pkg-dir/package.json
DEBUG ignore node_modules/punycode/package.json
DEBUG ignore node_modules/randombytes/package.json
DEBUG ignore node_modules/rechoir/package.json
DEBUG ignore node_modules/resolve/lib/core.json
DEBUG ignore node_modules/resolve/package.json
DEBUG ignore node_modules/resolve/test/module_dir/zmodules/bbb/package.json
DEBUG ignore node_modules/resolve/test/resolver/baz/package.json
DEBUG ignore node_modules/resolve/test/resolver/browser_field/package.json
DEBUG ignore node_modules/resolve/test/resolver/dot_main/package.json
DEBUG ignore node_modules/resolve/test/resolver/dot_slash_main/package.json
DEBUG ignore node_modules/resolve/test/resolver/false_main/package.json
DEBUG ignore node_modules/resolve/test/resolver/incorrect_main/package.json
DEBUG ignore node_modules/resolve/test/resolver/invalid_main/package.json
DEBUG ignore node_modules/resolve/test/resolver/malformed_package_json/package.json
DEBUG ignore node_modules/resolve/test/resolver/multirepo/lerna.json
DEBUG ignore node_modules/resolve/test/resolver/multirepo/package.json
DEBUG ignore node_modules/resolve/test/resolver/multirepo/packages/package-a/package.json
DEBUG ignore node_modules/resolve/test/resolver/multirepo/packages/package-b/package.json
DEBUG ignore node_modules/resolve/test/resolver/nested_symlinks/mylib/package.json
DEBUG ignore node_modules/resolve/test/resolver/symlinked/package/package.json
DEBUG ignore node_modules/resolve-cwd/package.json
DEBUG ignore node_modules/resolve-from/package.json
DEBUG ignore node_modules/safe-buffer/package.json
DEBUG ignore node_modules/schema-utils/package.json
DEBUG ignore node_modules/serialize-javascript/package.json
DEBUG ignore node_modules/shallow-clone/package.json
DEBUG ignore node_modules/shebang-command/package.json
DEBUG ignore node_modules/shebang-regex/package.json
DEBUG ignore node_modules/source-map/package.json
DEBUG ignore node_modules/source-map-support/package.json
DEBUG ignore node_modules/supports-color/package.json
DEBUG ignore node_modules/supports-preserve-symlinks-flag/package.json
DEBUG ignore node_modules/tapable/package.json
DEBUG ignore node_modules/terser/bin/package.json
DEBUG ignore node_modules/terser/dist/package.json
DEBUG ignore node_modules/terser/package.json
DEBUG ignore node_modules/terser-webpack-plugin/dist/options.json
DEBUG ignore node_modules/terser-webpack-plugin/package.json
DEBUG ignore node_modules/update-browserslist-db/package.json
DEBUG ignore node_modules/uri-js/package.json
DEBUG ignore node_modules/watchpack/package.json
DEBUG ignore node_modules/webpack/package.json
DEBUG ignore node_modules/webpack/schemas/WebpackOptions.json
DEBUG ignore node_modules/webpack/schemas/_container.json
DEBUG ignore node_modules/webpack/schemas/_sharing.json
DEBUG ignore node_modules/webpack/schemas/plugins/BannerPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/DllPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/DllReferencePlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/HashedModuleIdsPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/IgnorePlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/JsonModulesPluginParser.json
DEBUG ignore node_modules/webpack/schemas/plugins/LoaderOptionsPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/ProgressPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/SourceMapDevToolPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/WatchIgnorePlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/asset/AssetGeneratorOptions.json
DEBUG ignore node_modules/webpack/schemas/plugins/asset/AssetInlineGeneratorOptions.json
DEBUG ignore node_modules/webpack/schemas/plugins/asset/AssetParserOptions.json
DEBUG ignore node_modules/webpack/schemas/plugins/asset/AssetResourceGeneratorOptions.json
DEBUG ignore node_modules/webpack/schemas/plugins/container/ContainerPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/container/ContainerReferencePlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/container/ExternalsType.json
DEBUG ignore node_modules/webpack/schemas/plugins/container/ModuleFederationPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/css/CssGeneratorOptions.json
DEBUG ignore node_modules/webpack/schemas/plugins/css/CssParserOptions.json
DEBUG ignore node_modules/webpack/schemas/plugins/debug/ProfilingPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/ids/OccurrenceChunkIdsPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/ids/OccurrenceModuleIdsPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/optimize/AggressiveSplittingPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/optimize/LimitChunkCountPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/optimize/MinChunkSizePlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/schemes/HttpUriPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/sharing/ConsumeSharedPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/sharing/ProvideSharedPlugin.json
DEBUG ignore node_modules/webpack/schemas/plugins/sharing/SharePlugin.json
DEBUG ignore node_modules/webpack-cli/node_modules/commander/package-support.json
DEBUG ignore node_modules/webpack-cli/node_modules/commander/package.json
DEBUG ignore node_modules/webpack-cli/package.json
DEBUG ignore node_modules/webpack-merge/package.json
DEBUG ignore node_modules/webpack-sources/package.json
DEBUG ignore node_modules/which/package.json
DEBUG ignore node_modules/wildcard/docs.json
DEBUG ignore node_modules/wildcard/package.json
DEBUG ignore package-lock.json
DEBUG ignore package.json
DEBUG ignore assets/cursor-zoom-in-2x.svg
DEBUG ignore assets/cursor-zoom-in.svg
                                                                            100%
[2023-05-03 08:37:36] INFO  WEBrick 1.7.0
[2023-05-03 08:37:36] INFO  ruby 3.2.2 (2023-03-30) [x64-mingw-ucrt]
[2023-05-03 08:37:36] INFO  WEBrick::HTTPServer#start: pid=10752 port=9292
DEBUG Refreshing preview _secure_session_id cookie
DEBUG Proxying HEAD https://theme-kit-access.shopifyapps.com/cli/sfr/?preview_theme_id=130399535312&_fd=0&pb=0
DEBUG `-> 302 request_id: 7a340d7d-f799-4df5-9ed9-2c41eee9d67c
[2023-05-03 08:37:36] ERROR ArgumentError: invalid name: "_ply_query_options[prefix]"
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:108:in `name='
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:79:in `initialize'
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:195:in `new'
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:195:in `block in parse'
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:187:in `each'
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:187:in `parse'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy_param_builder.rb:57:in `cookie_sections'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy_param_builder.rb:51:in `request_templates'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy_param_builder.rb:13:in `build'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb:250:in `build_replacement_param'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb:57:in `call'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/cdn_fonts.rb:23:in `call'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/local_assets.rb:38:in `call'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/hot_reload.rb:23:in `call'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/web_server.rb:100:in `service'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/webrick/lib/webrick/httpserver.rb:140:in `service'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/webrick/lib/webrick/httpserver.rb:96:in `run'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/webrick/lib/webrick/server.rb:310:in `block in start_thread'
[2023-05-03 08:37:36] ERROR ArgumentError: invalid name: "_ply_query_options[prefix]"
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:108:in `name='
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:79:in `initialize'
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:195:in `new'
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:195:in `block in parse'
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:187:in `each'
        D:/Ruby32-x64/lib/ruby/3.2.0/cgi/cookie.rb:187:in `parse'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy_param_builder.rb:57:in `cookie_sections'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy_param_builder.rb:51:in `request_templates'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy_param_builder.rb:13:in `build'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb:250:in `build_replacement_param'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb:57:in `call'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/cdn_fonts.rb:23:in `call'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/local_assets.rb:38:in `call'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/hot_reload.rb:23:in `call'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/web_server.rb:100:in `service'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/webrick/lib/webrick/httpserver.rb:140:in `service'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/webrick/lib/webrick/httpserver.rb:96:in `run'
        C:/Users/Gary/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/webrick/lib/webrick/server.rb:310:in `block in start_thread'
```

### Reproduction steps

1. Install Ruby 3.2.2
2. Upgrade CLI to latest
3. Try to run shopify theme dev...

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.2

### Node version (run `node -v` if you're not sure)

v16.15.0

**Comment by bluedge** [comment]
Shopify CLi / shopify Theme @2.45.2
uninitialized constant ShopifyCLI::Theme::DevServer::CdnFonts::Rack response = Rack::Response.new(nil, status, headers) ^^^^
when running `shopify theme dev --store=xxxx.myshopify.com`
