### ISSUE TITLE
[Bug]:  An unexpected error occurred.

### ISSUE THREAD

**Issue by blockmood** [Shopify/cli#1917]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

run success

### Actual behavior

```
╭─ success ────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Preview your theme                                                          │
│    • http://127.0.0.1:9292                                                   │
│                                                                              │
│  Next steps                                                                  │
│    • Customize your theme at the theme editor                                │
│    • Share your theme preview                                                │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

✗ An unexpected error occurred.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

** [Bugsnag] 2023-05-05 17:43:32 +0800: Unable to send information to Bugsnag (https://notify.bugsnag.com), #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=35.186.205.6:443 state=error: certificate verify failed (self-signed certificate in certificate chain)>
** [Bugsnag] 2023-05-05 17:43:32 +0800: ["/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:1089:in `connect'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:995:in `do_start'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:984:in `start'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:1564:in `request'", "/Users/takehoshi/Library/Caches/shopify-gems-nodejs/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/delivery/synchronous.rb:51:in `request'", "/Users/takehoshi/Library/Caches/shopify-gems-nodejs/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/delivery/synchronous.rb:12:in `deliver'", "/Users/takehoshi/Library/Caches/shopify-gems-nodejs/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/delivery/thread_queue.rb:38:in `block in serialize_and_deliver'", "/Users/takehoshi/Library/Caches/shopify-gems-nodejs/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/delivery/thread_queue.rb:55:in `block (2 levels) in start_once!'"]
Error
    at execCLI2 (file:///usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:59:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Verbose output

```shell
2023-05-05T10:59:17.120Z:
Running system process:
  · Command: bundle exec ruby /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme serve /Users/takehoshi/Desktop/my-new-theme --live-reload hot-reload --theme 148999635226
  · Working directory: /Users/takehoshi/Desktop/my-new-theme

✗ An unexpected error occurred.
	To submit an issue include the stack trace.

** [Bugsnag] 2023-05-05 18:59:20 +0800: Unable to send information to Bugsnag (https://notify.bugsnag.com), #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=35.186.205.6:443 state=error: certificate verify failed (self-signed certificate in certificate chain)>
** [Bugsnag] 2023-05-05 18:59:20 +0800: ["/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:1089:in `connect'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:995:in `do_start'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:984:in `start'", "/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:1564:in `request'", "/Users/takehoshi/Library/Caches/shopify-gems-nodejs/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/delivery/synchronous.rb:51:in `request'", "/Users/takehoshi/Library/Caches/shopify-gems-nodejs/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/delivery/synchronous.rb:12:in `deliver'", "/Users/takehoshi/Library/Caches/shopify-gems-nodejs/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/delivery/thread_queue.rb:38:in `block in serialize_and_deliver'", "/Users/takehoshi/Library/Caches/shopify-gems-nodejs/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/delivery/thread_queue.rb:55:in `block (2 levels) in start_once!'"]
/usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=23.227.38.74:443 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:1089:in `connect'
	from /usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:995:in `do_start'
	from /usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:984:in `start'
	from /usr/local/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/net/http.rb:1564:in `request'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/http_request.rb:39:in `request'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/http_request.rb:19:in `get'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/api.rb:63:in `block in request'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/api.rb:89:in `request'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/admin_api.rb:95:in `rest_request'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme_admin_api.rb:38:in `rest_request'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme_admin_api.rb:18:in `get'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme.rb:182:in `fetch_themes'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme.rb:160:in `find'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/theme.rb:154:in `find_by_identifier'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:187:in `theme'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:287:in `syncing_theme_message'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:173:in `sync_theme'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:106:in `start'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:66:in `start'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/serve.rb:48:in `call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command/sub_command.rb:16:in `call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:27:in `call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui.rb:177:in `log_output_to'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:26:in `log'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:50:in `block (2 levels) in <main>'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:49:in `block in <main>'
	from /usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:59:in `<main>'
Error
    at execCLI2 (file:///usr/local/share/.config/yarn/global/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:59:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```


### Reproduction steps

1. shopify theme dev --store https://yp-yxtest1.myshopify.com/

### Operating System

macos

### Shopify CLI version (check your project's `package.json` if you're not sure)

 3.45.4

### Shell

iTerm2

### Node version (run `node -v` if you're not sure)

v16.13.0

### What language and version are you using in your application?

node

**Comment by gonzaloriestra** [comment]
Hi! Sorry for the delay.

It looks like an issue with your OpenSSL certificate. Could you try this? https://github.com/Shopify/shopify-cli/issues/1673#issuecomment-1026077210
