### ISSUE TITLE
[Bug]: Creating payment extension command with Javascript fails. Command failed with exit code 1: npm exec -- graphql-code-generator --config package.json

### ISSUE THREAD

**Issue by crudenorway** [Shopify/cli#2031]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension, Function

### Expected behavior

The extension should have been created

### Actual behavior

When trying to generate a extension, Function - Payment customization with Javascript, this error occures after a few sec, using `npm run generate extension`

```shell
── external error ────────────────────────────────────────────────────────

Error coming from `npm exec -- graphql-code-generator --config package.json`

Command failed with exit code 1: npm exec -- graphql-code-generator --config package.json
Cannot convert undefined or null to object
[13:52:53] Parse configuration [started]
[13:52:53] Parse configuration [failed]
[13:52:53] → Cannot convert undefined or null to object
```
The extension is not created. Doing it in Rust works fine.

This is a fresh app, no changes done. Done straight after npm init @shopify/app@latest

### Verbose output

```shell
> xxxx-checkout-customize@1.0.0 generate
> shopify app generate "extension" "--verbose"

2023-05-30T11:57:44.485Z: Running command app generate extension
2023-05-30T11:57:44.493Z: Ensuring that the user is authenticated with the Partners API with the following scopes:
[]

2023-05-30T11:57:44.494Z: Getting session store...
2023-05-30T11:57:44.496Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "partnersApi": {
    "scopes": []
  }
}

2023-05-30T11:57:44.496Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-05-30T11:57:44.497Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-05-30T11:57:44.765Z: Request to https://accounts.shopify.com/oauth/introspection completed in 260 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"1d2b1711dc0655f29c6673a5dbacf198"
 - x-request-id: b5c9d9d1-83ee-4bb5-acee-37d48cd0c965
    
2023-05-30T11:57:44.774Z: The identity token is valid: true
2023-05-30T11:57:44.776Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-05-30T11:57:44.777Z: Verifying that the user has a Partner organization
2023-05-30T11:57:44.778Z: Sending "Partners" GraphQL request:
  {
    organizations(first: 1) {
      nodes {
        id
      }
    }
  }

With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-05-30T11:57:45.076Z: Request to https://partners.shopify.com/api/cli/graphql completed in 288 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"f0b4eea922d7b8d43660f57ec8fdcc2b"
 - x-request-id: 6b56f94d-51c2-4943-b87d-1a250215f6f7
    
2023-05-30T11:57:45.081Z: Reading cached app information for directory /Users/xxxxxx/Websites/xxxx-checkout-customize...
2023-05-30T11:57:45.083Z: Sending "Partners" GraphQL request:
  query FindOrganization($id: ID!) {
    organizations(id: $id, first: 1) {
      nodes {
        id
        businessName
        website
        betas {
          cliTunnelAlternative
        }
      }
    }
  }

With variables:
{
  "id": "819258"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-05-30T11:57:45.332Z: Request to https://partners.shopify.com/api/cli/graphql completed in 242 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"c3845e8c6b1c57f010dc37197c1d3928"
 - x-request-id: 3acf59e5-4baa-494a-a1e0-188b6dea1b89
    
2023-05-30T11:57:45.334Z: Sending "Partners" GraphQL request:
  query FindApp($apiKey: String!) {
    app(apiKey: $apiKey) {
      id
      title
      apiKey
      organizationId
      apiSecretKeys {
        secret
      }
      appType
      grantedScopes
      betas {
        unifiedAppDeployment
      }
    }
  }

With variables:
{
  "apiKey": "2ce3f2e121543699d4ed5bf7158c1472"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-05-30T11:57:46.072Z: Request to https://partners.shopify.com/api/cli/graphql completed in 729 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"6479b841a13f8bbc8fac69edbb961d0f"
 - x-request-id: d0fa9f5d-e16f-4c3b-8b5d-61ee021eb82d
    
2023-05-30T11:57:46.078Z: Obtaining the dependency manager in directory /Users/xxxxxx/Websites/xxxx-checkout-customize...
╭─ info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                              │
│  Using your previous dev settings:                                                                                                                           │
│                                                                                                                                                              │
│    • Org:          XXXX AS                                                                                                                                  │
│    • App:          Checkout Customize                                                                                                                        │
│                                                                                                                                                              │
│  To reset your default dev config, run `npm run dev -- --reset`                                                                                              │
│                                                                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

2023-05-30T11:57:46.226Z: Sending "Partners" GraphQL request:
  query fetchSpecifications($api_key: String!) {
    extensionSpecifications(apiKey: $api_key) {
      name
      externalName
      externalIdentifier
      identifier
      gated
      options {
        managementExperience
        registrationLimit
      }
      features {
        argo {
          surface
        }
      }
    }
  }

With variables:
{
  "api_key": "2ce3f2e121543699d4ed5bf7158c1472"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-05-30T11:57:46.504Z: Request to https://partners.shopify.com/api/cli/graphql completed in 274 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"322a5351ec1bd789eaeb197ab62ff682"
 - x-request-id: f9dc2770-1765-4267-8021-9f6b1806a5e2
    
2023-05-30T11:57:46.576Z: Reading the content of file at shopify.app.toml...
2023-05-30T11:57:46.584Z: Reading the content of file at package.json...
2023-05-30T11:57:46.584Z: Reading the content of file at package.json...
2023-05-30T11:57:46.585Z: Obtaining the dependency manager in directory /Users/xxxxxx/Websites/xxxx-checkout-customize...
2023-05-30T11:57:46.784Z: Reading the content of file at web/shopify.web.toml...
2023-05-30T11:57:46.785Z: Reading the content of file at web/frontend/shopify.web.toml...
2023-05-30T11:57:46.785Z: Reading the content of file at node_modules/shopify-app-template-node/shopify.web.toml...
2023-05-30T11:57:46.786Z: Reading the content of file at node_modules/shopify-frontend-template-react/shopify.web.toml...
2023-05-30T11:57:46.786Z: Reading the content of file at node_modules/shopify-app-template-node/frontend/shopify.web.toml...
2023-05-30T11:57:46.834Z: Reading the content of file at package.json...
2023-05-30T11:57:46.835Z: Unable to decide project type as multiple web backends
2023-05-30T11:57:46.836Z: Sending "Partners" GraphQL request:
  query RemoteTemplateSpecifications($version: String) {
    templateSpecifications(version: $version) {
      identifier
      name
      group
      supportLinks
      types {
        url
        type
        extensionPoints
        supportedFlavors {
          name
          value
          path
        }
      }
    }
  }

With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-05-30T11:57:47.063Z: Request to https://partners.shopify.com/api/cli/graphql completed in 224 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"39badd4f1dd93674ecdcab3a0ed7776a"
 - x-request-id: 1ce1f7f3-2b29-425e-a736-7bd7031597ca
    
?  Type of extension?
✔  Function - Payment customization

?  Extension name (internal only):
✔  lucrative-portfolio-ext

?  What would you like to work in?
✔  JavaScript

2023-05-30T11:57:52.424Z: Creating directory at extensions/lucrative-portfolio-ext...
2023-05-30T11:57:52.447Z: Creating directory at /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download...
2023-05-30T11:57:52.451Z: Git-cloning repository https://github.com/Shopify/function-examples into /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download...
2023-05-30T11:57:52.471Z: 
Running system process:
  · Command: git --version
  · Working directory: /Users/xxxxxx/Websites/xxxx-checkout-customize

2023-05-30T11:57:53.508Z: Copying template from directory /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default to extensions/lucrative-portfolio-ext
2023-05-30T11:57:53.522Z: Checking if /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/src/index.test.liquid is a directory...
2023-05-30T11:57:53.522Z: Checking if /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/src/index.liquid is a directory...
2023-05-30T11:57:53.522Z: Checking if /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/shopify.function.extension.toml.liquid is a directory...
2023-05-30T11:57:53.523Z: Checking if /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/schema.graphql is a directory...
2023-05-30T11:57:53.524Z: Checking if /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/package.json.liquid is a directory...
2023-05-30T11:57:53.524Z: Checking if /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/input.graphql.liquid is a directory...
2023-05-30T11:57:53.524Z: Checking if /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/.gitignore is a directory...
2023-05-30T11:57:53.525Z: Creating directory at extensions/lucrative-portfolio-ext/src...
2023-05-30T11:57:53.525Z: Creating directory at extensions/lucrative-portfolio-ext/src...
2023-05-30T11:57:53.526Z: Creating directory at extensions/lucrative-portfolio-ext...
2023-05-30T11:57:53.527Z: Copying file from /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/schema.graphql to extensions/lucrative-portfolio-ext/schema.graphql...
2023-05-30T11:57:53.527Z: Creating directory at extensions/lucrative-portfolio-ext...
2023-05-30T11:57:53.528Z: Creating directory at extensions/lucrative-portfolio-ext...
2023-05-30T11:57:53.528Z: Copying file from /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/.gitignore to extensions/lucrative-portfolio-ext/.gitignore...
2023-05-30T11:57:53.529Z: Reading the content of file at /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/src/index.test.liquid...
2023-05-30T11:57:53.530Z: Reading the content of file at /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/src/index.liquid...
2023-05-30T11:57:53.531Z: Reading the content of file at /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/shopify.function.extension.toml.liquid...
2023-05-30T11:57:53.531Z: Reading the content of file at /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/package.json.liquid...
2023-05-30T11:57:53.532Z: Reading the content of file at /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/input.graphql.liquid...
2023-05-30T11:57:53.537Z: Copying file from /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/src/index.test.liquid to extensions/lucrative-portfolio-ext/src/index.test...
2023-05-30T11:57:53.545Z: Copying file from /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/src/index.liquid to extensions/lucrative-portfolio-ext/src/index...
2023-05-30T11:57:53.546Z: Copying file from /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/shopify.function.extension.toml.liquid to extensions/lucrative-portfolio-ext/shopify.function.extension.toml...
2023-05-30T11:57:53.546Z: Copying file from /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/package.json.liquid to extensions/lucrative-portfolio-ext/package.json...
2023-05-30T11:57:53.547Z: Copying file from /private/var/folders/s5/tzk5d3fs4pgcjym71w4vgrvh0000gn/T/2bc92fb9519dde6b7f835e39a5d38727/download/checkout/javascript/payment-customization/default/input.graphql.liquid to extensions/lucrative-portfolio-ext/input.graphql...
2023-05-30T11:57:53.550Z: Writing some content to file at extensions/lucrative-portfolio-ext/src/index.test...
2023-05-30T11:57:53.550Z: Writing some content to file at extensions/lucrative-portfolio-ext/package.json...
2023-05-30T11:57:53.551Z: Writing some content to file at extensions/lucrative-portfolio-ext/shopify.function.extension.toml...
2023-05-30T11:57:53.551Z: Writing some content to file at extensions/lucrative-portfolio-ext/src/index...
2023-05-30T11:57:53.551Z: Writing some content to file at extensions/lucrative-portfolio-ext/input.graphql...
2023-05-30T11:57:53.605Z: Adding the following dependencies if needed:
[
  {
    "name": "@shopify/shopify_function",
    "version": "0.0.3"
  },
  {
    "name": "javy",
    "version": "0.1.0"
  }
]
With options:
{
  "packageManager": "npm",
  "type": "prod",
  "directory": "/Users/xxxxxx/Websites/xxxx-checkout-customize/extensions/lucrative-portfolio-ext"
}
  
2023-05-30T11:57:53.606Z: Reading the content of file at extensions/lucrative-portfolio-ext/package.json...
2023-05-30T11:57:53.624Z: 
Running system process:
  · Command: npm install @shopify/shopify_function@0.0.3 --save-prod --save-exact
  · Working directory: /Users/xxxxxx/Websites/xxxx-checkout-customize/extensions/lucrative-portfolio-ext

2023-05-30T11:57:55.892Z: 
Running system process:
  · Command: npm install javy@0.1.0 --save-prod --save-exact
  · Working directory: /Users/xxxxxx/Websites/xxxx-checkout-customize/extensions/lucrative-portfolio-ext

2023-05-30T11:57:58.679Z: 
Running system process:
  · Command: npm exec -- graphql-code-generator --config package.json
  · Working directory: /Users/xxxxxx/Websites/xxxx-checkout-customize/extensions/lucrative-portfolio-ext

▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

2023-05-30T11:58:00.959Z: Removing file at extensions/lucrative-portfolio-ext...
── external error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `npm exec -- graphql-code-generator --config package.json`

Command failed with exit code 1: npm exec -- graphql-code-generator --config package.json
2023-05-30T11:57:59.123Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms
2023-05-30T11:57:59.923Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free
Cannot convert undefined or null to object
[13:58:00] Parse configuration [started]
[13:58:00] Parse configuration [failed]
[13:58:00] → Cannot convert undefined or null to object

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

2023-05-30T11:58:00.977Z: Obtaining the dependency manager in directory /Users/xxxxxx/Websites/xxxx-checkout-customize...
2023-05-30T11:58:00.993Z: 
Running system process:
  · Command: ruby -v
  · Working directory: /Users/xxxxxx/Websites/xxxx-checkout-customize

2023-05-30T11:58:01.000Z: Obtaining the dependency manager in directory /Users/xxxxxx/Websites/xxxx-checkout-customize...
2023-05-30T11:58:01.016Z: 
Running system process:
  · Command: ruby -v
  · Working directory: /Users/xxxxxx/Websites/xxxx-checkout-customize

2023-05-30T11:58:01.699Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 185 ms
With response headers:
 - x-request-id: cde84963-aff8-4ffc-84e8-104db7e89856
    
2023-05-30T11:58:01.702Z: Analytics event sent: {
  "command": "app scaffold extension",
  "time_start": 1685447864486,
  "time_end": 1685447880967,
  "total_time": 16481,
  "success": false,
  "cli_version": "3.46.1",
  "ruby_version": "3.2.1",
  "node_version": "16.14.2",
  "is_employee": false,
  "uname": "darwin amd64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/app\",\"@shopify/cli\",\"@shopify/plugin-cloudflare\",\"@shopify/plugin-did-you-mean\",\"@shopify/plugin-ngrok\"]",
  "env_shell": "zsh",
  "env_device_id": "f9921779259cabe075aab4efc62a24f1e943534c",
  "env_cloud": "localhost",
  "env_package_manager": "npm",
  "cmd_scaffold_required_auth": true,
  "cmd_scaffold_template_custom": false,
  "cmd_scaffold_type_owner": "@shopify/app",
  "app_extensions_any": false,
  "app_extensions_breakdown": "{}",
  "app_extensions_count": 0,
  "app_extensions_custom_layout": false,
  "app_extensions_function_any": false,
  "app_extensions_function_count": 0,
  "app_extensions_function_custom_layout": false,
  "app_extensions_theme_any": false,
  "app_extensions_theme_count": 0,
  "app_extensions_theme_custom_layout": false,
  "app_extensions_ui_any": false,
  "app_extensions_ui_count": 0,
  "app_extensions_ui_custom_layout": false,
  "app_name_hash": "4ee0e8c67c20dc94e194616b65bc44ffc6ac8b3c",
  "app_path_hash": "e065264388f14b465aa01bd417ad1a6e8e827eca",
  "app_scopes": "[\"write_products\"]",
  "app_web_backend_any": true,
  "app_web_backend_count": 2,
  "app_web_custom_layout": true,
  "app_web_frontend_any": true,
  "app_web_frontend_count": 3,
  "env_package_manager_workspaces": true,
  "cmd_scaffold_template_flavor": "vanilla-js",
  "cmd_scaffold_type": "payment_customization",
  "cmd_scaffold_used_prompts_for_type": true,
  "cmd_all_launcher": "npm",
  "cmd_all_topic": "app generate",
  "cmd_all_plugin": "@shopify/app",
  "cmd_all_verbose": true,
  "cmd_all_path_override": true,
  "cmd_all_path_override_hash": "e065264388f14b465aa01bd417ad1a6e8e827eca",
  "args": "--verbose",
  "error_message": "Command failed with exit code 1: npm exec -- graphql-code-generator --config package.json\n2023-05-30T11:57:59.123Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms\n2023-05-30T11:57:59.923Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free\nCannot convert undefined or null to object\n\u001b[2m[13:58:00]\u001b[22m Parse configuration [started]\n\u001b[2m[13:58:00]\u001b[22m Parse configuration [failed]\n\u001b[2m[13:58:00]\u001b[22m → Cannot convert undefined or null to object",
  "app_name": "xxxx-checkout-customize",
  "env_plugin_installed_all": "[\"@shopify/app\",\"@shopify/cli\",\"@shopify/plugin-cloudflare\",\"@shopify/plugin-did-you-mean\",\"@shopify/plugin-ngrok\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
```

### Reproduction steps

1. Create a new app `npm init @shopify/app@latest`
2. Create a new extension `npm run generate extension`

### Operating System

Macbook Pro M1 Max, Ventura 13.3.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

v16.14.2

### What language and version are you using in your application?

Node 16.14.2

**Comment by lamttq97** [comment]
I have the same exact problem and I have to add extra package from [Function example](https://github.com/Shopify/function-examples). After that run the code again and it work. However I don't think this is the correct way

**Comment by aamandeep1991** [comment]
Same with me, please help to get this issue resolved.

**Comment by crudenorway** [comment]
FINALLY worked it out, it was fixed by just adding javy and @shopify/shopify_function to the root package.json:

```
"dependencies": {
    "@shopify/app": "^3.45.0",
    "@shopify/cli": "^3.45.0",
    "@shopify/shopify_function": "0.0.3",
    "javy": "0.0.3"
  },
```

And running a `npm install`

But this was just me shooting in the dark, there should at least be some errors pointing in this direction.

**Comment by aamandeep1991** [comment]
oh is it, then what are the possible options to take decisions basis non-shopify data there? @crudenorway 

Do I need to add external data in shopify database using meta-objects?
or
There is a some way to reach out to a shopify backend from there which can internally call an external system?

Or any other system.

Is there any design/tech documentation around all this which we can read?

**Comment by Arkham** [comment]
This should be fixed by `3.46.2`, thanks for reporting!

**Comment by tranquangkhai1996** [comment]
I got this problem today with version 3.46.2, the package.json include @shopify/shopify_function and javy. Is there any solutions to solve it?

**Comment by tranquangkhai1996** [comment]
Here is what I got on the log file. Please help me to take a look and give me some advice. I am not familiar with Rust and Webassembly coding.

13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
