### ISSUE TITLE
[Bug]: CLI V3 - theme dev not working on Windows machines 

### ISSUE THREAD

**Issue by JoshMealing** [Shopify/cli#2034]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

We expect the **theme dev --store=storename** command to start a local server on port 9292 and serve the theme files.

### Actual behavior

The shopify CLI appears to be creating the development theme and providing the correct terminal output, however when viewing in the browser were are met with the following screen in the browser

![image](https://github.com/Shopify/cli/assets/91449114/2c1ab766-4320-46e8-add7-01e2f18ef554)

In addition to this, when viewing the dev theme we are presented with the following error message 
![image](https://github.com/Shopify/cli/assets/91449114/ac260f89-7cde-491c-b13f-3a591cb727af)

When checking the specified files, they definitely exist in the theme directory.

### Verbose output

```shell
PS C:\Users\User\Desktop\Projects\MCM-House-2023> yarn start --verbose
yarn run v1.22.18
warning ..\..\..\package.json: No license field
$ reflect start --verbose
☕ Running Reflect with; {
  args: [ 'start', '--verbose' ],
  settings: {
    BRANCH_DEPLOY: 'shopify-production',
    BRANCH_MASTER: 'master',
    BRANCH_CURRENT: 'master',
    DEPLOY_EMAIL: 'email-address',
    DEPLOY_NAME: 'Process-Admin'
  },
  env: {
    BRANCH_DEPLOY: undefined,
    BRANCH_MASTER: undefined,
    BRANCH_CURRENT: undefined,
    GITHUB_BASE_REF: undefined,
    GITHUB_HEAD_REF: undefined,
    GITHUB_REF: undefined
  }
}
🚮 Deleting old build.
🍌 Starting web server in background.
(node:1888) [DEP_WEBPACK_DEV_SERVER_HTTPS] DeprecationWarning: 'https' option is deprecated. Please use the 'server' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
<i> [webpack-dev-server] SSL certificate: C:\Users\User\Desktop\Projects\MCM-House-2023\node_modules\.cache\webpack-dev-server\server.pem
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: https://localhost:3000/, https://127.0.0.1:3000/
<i> [webpack-dev-server] Content not from webpack is served from 'C:\Users\User\Desktop\Projects\MCM-House-2023\public' directory
Compile Done
🛍 Starting Shopify CLI in background.
assets by path ../ 392 KiB 156 assets
assets by path *.js 3.14 MiB
  asset vendor.js 1.1 MiB [emitted] (name: vendor) (id hint: vendor)
  + 37 assets
assets by path *.css 322 KiB
  asset sections.product-main.css 60.5 KiB [emitted] (name: sections.product-main)
  + 35 assets
assets by chunk 966 KiB (auxiliary name: layouts.password)
  assets by path *.ttf 743 KiB 3 assets
  assets by path *.woff 223 KiB 3 assets
  assets by path *.svg 358 bytes 2 assets
assets by chunk 398 bytes (auxiliary name: sections.carousel-section)
  asset icon.left.svg 199 bytes [emitted] [from: assets/icon.left.svg] (auxiliary name: sections.carousel-section)
  asset icon.right.svg 199 bytes [emitted] [from: assets/icon.right.svg] (auxiliary name: sections.carousel-section)
asset .gitkeep 0 bytes [emitted] [from: assets/.gitkeep] [copied]
runtime modules 86.7 KiB 258 modules
orphan modules 395 KiB (javascript) 967 KiB (asset) [orphan] 49 modules
javascript modules 789 KiB
  modules by path ./node_modules/ 311 KiB 296 modules
  modules by path ./scripts/ 415 KiB 43 modules
  modules by path ./styles/ 63.2 KiB
    modules by path ./styles/sections/*.scss 53.1 KiB 31 modules
    modules by path ./styles/layouts/*.scss 9.73 KiB 3 modules
    modules by path ./styles/settings/*.scss 426 bytes 2 modules
css modules 294 KiB
  modules by path ./styles/sections/*.scss 210 KiB 31 modules
  modules by path ./styles/layouts/*.scss 84.3 KiB 3 modules
  modules by path ./styles/settings/*.scss 0 bytes
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[3]!./styles/settings/animation.scss 0 bytes [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[3]!./styles/settings/responsive.scss 0 bytes [built] [code generated]

WARNING in ./styles/sections/collection-hero.scss (./styles/sections/collection-hero.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[3]!./styles/sections/collection-hero.scss)
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(125:5) autoprefixer: end value has mixed support, consider using flex-end instead
 @ ./styles/sections/collection-hero.scss

webpack 5.84.1 compiled with 1 warning in 8761 ms
2023-05-31T02:41:26.433Z: Running command theme dev
2023-05-31T02:41:26.449Z shopify:theme:dev init version: @oclif/core@2.1.4 argv: [ '--path', 'C:\\Users\\User\\Desktop\\Projects\\MCM-House-2023\\dist', '--verbose' ]

2023-05-31T02:41:26.471Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-05-31T02:41:26.473Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store mcm-house-dev.myshopify.com:
[]

2023-05-31T02:41:26.475Z: Getting session store...
2023-05-31T02:41:26.480Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "mcm-house-dev.myshopify.com"
  }
}

2023-05-31T02:41:26.485Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-05-31T02:41:26.486Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-05-31T02:41:27.008Z: Request to https://accounts.shopify.com/oauth/introspection completed in 512 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"6a3b47c0e45ccaa6f18ce11bc3675976"
 - x-request-id: 5a440f0e-fc2b-4ca7-a3c4-1b356cdda505

2023-05-31T02:41:27.012Z: The identity token is valid: true
2023-05-31T02:41:27.013Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false

2023-05-31T02:41:27.014Z: The current session is valid but needs refresh. Refreshing...
2023-05-31T02:41:27.016Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=ACCESS_TOKEN&refresh_token=REFRESH_TOKEN&client_id=CLIENT_ID
With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-05-31T02:41:27.600Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=ACCESS_TOKEN&refresh_token=REFRESH_TOKEN completed in 581 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"f3b10833e0cbea19d1997beec9b55284"
 - x-request-id: e40a36c2-ac8d-419a-a720-79ac213d7879

2023-05-31T02:41:27.605Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=CLIENT_ID&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=SUBJECT_TOKEN
With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-05-31T02:41:27.607Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=CLIENT_ID&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=SUBJECT_TOKEN
With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-05-31T02:41:28.067Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=SUBJECT_TOKEN completed in 456 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"bfc6402a71bf354d17c5d59a9061df4f"
 - x-request-id: 32b4d7b0-6042-481b-9c29-a01ccd04c48a

2023-05-31T02:41:28.345Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=SUBJECT_TOKEN completed in 735 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"9b9fe8683f35dbf5f25b6640e97c5423"
 - x-request-id: 98e31b4d-8b60-49e4-907e-343d305bcd6b

2023-05-31T02:41:28.351Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=SUBJECT_TOKEN&destination=https%3A%2F%2Fmcm-house-dev.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-05-31T02:41:28.879Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=SUBJECT_TOKEN&destination=https%3A%2F%2Fmcm-house-dev.myshopify.com%2Fadmin completed in 524 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"97a01744ae8b150a33902ab2dacf035b"
 - x-request-id: 5b3f0838-9753-4f42-add1-8bd28bf9039c

2023-05-31T02:41:28.884Z: Setting session store...
2023-05-31T02:41:28.893Z: Getting development theme...
2023-05-31T02:41:29.580Z: Request to https://mcm-house-dev.myshopify.com/admin/api/unstable/themes/151245652268.json?fields=id completed in 678 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: 986f7120-b7ee-49e4-8159-fbe72c4d9a4e

╭─ success ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                       │
│  Preview your theme                                                                                                                                                   │
│    • http://127.0.0.1:9292 [1]                                                                                                                                        │
│                                                                                                                                                                       │
│  Next steps                                                                                                                                                           │
│    • Customize your theme at the theme editor [2]                                                                                                                     │
│    • Share your theme preview [3]                                                                                                                                     │
│                                                                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[1] http://127.0.0.1:9292
[2] https://mcm-house-dev.myshopify.com/admin/themes/151245652268/editor
[3] https://mcm-house-dev.myshopify.com/?preview_theme_id=151245652268

2023-05-31T02:41:29.719Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2023-05-31T02:41:29.720Z: Getting session store...
2023-05-31T02:41:29.722Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2023-05-31T02:41:29.726Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-05-31T02:41:29.726Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.46.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2023-05-31T02:41:29.773Z: Obtaining the dependency manager in directory C:/Users/User/Desktop/Projects/MCM-House-2023...
2023-05-31T02:41:29.798Z: 
Running system process:
  · Command: ruby -v
  · Working directory: C:/Users/User/Desktop/Projects/MCM-House-2023

2023-05-31T02:41:30.261Z: Request to https://accounts.shopify.com/oauth/introspection completed in 531 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"a5fb4018c1eb6b24d64a1c0b5e3f0169"
 - x-request-id: 9056e5e4-acbf-4c1f-bfcf-af770ebf9012

2023-05-31T02:41:30.265Z: The identity token is valid: true
2023-05-31T02:41:30.265Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false

2023-05-31T02:41:30.278Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 419 ms
With response headers:
 - x-request-id: f5b9e7b0-fc23-41b1-9297-934262465697

2023-05-31T02:41:30.280Z: Analytics event sent: {
  "command": "theme dev",
  "time_start": 1685500886435,
  "time_end": 1685500889759,
  "total_time": 3324,
  "success": true,
  "cli_version": "3.46.1",
  "ruby_version": "3.1.2",
  "node_version": "14.19.1",
  "is_employee": false,
  "uname": "windows amd64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "env_shell": "cmd.exe",
  "env_device_id": "4ee1c66a848c12586b5cb70b8dcbee20e423b71b",
  "env_cloud": "localhost",
  "env_package_manager": "yarn",
  "cmd_all_launcher": "yarn",
  "cmd_all_topic": "theme",
  "cmd_all_plugin": "@shopify/theme",
  "args": "--path C:\\Users\\User\\Desktop\\Projects\\MCM-House-2023\\dist --verbose",
  "env_plugin_installed_all": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-05-31T02:41:30.284Z: Completed command theme dev
2023-05-31T02:41:30.317Z: 
Running system process:
  · Command: ruby -v
  · Working directory: C:/Users/User/Desktop/Projects/MCM-House-2023

2023-05-31T02:41:30.378Z: 
Running system process:
  · Command: bundle -v
  · Working directory: C:/Users/User/Desktop/Projects/MCM-House-2023

UnhandledPromiseRejectionWarning: Error: Bundler version 2.3.7 is not supported
    at validateBundler (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:188:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async validateRubyEnv (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:153:5)
    at async installCLIDependencies (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:136:5)
    at async execCLI2 (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:34:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
UnhandledPromiseRejectionWarning: Error: Bundler version 2.3.7 is not supported
    at validateBundler (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:188:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async validateRubyEnv (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:153:5)
    at async installCLIDependencies (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:136:5)
    at async execCLI2 (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:34:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
Error: Bundler version 2.3.7 is not supported
    at validateBundler (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:188:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async validateRubyEnv (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:153:5)
    at async installCLIDependencies (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:136:5)
    at async execCLI2 (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:34:5)
Error: Bundler version 2.3.7 is not supported
    at validateBundler (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:188:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async validateRubyEnv (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:153:5)
    at async installCLIDependencies (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:136:5)
    at async execCLI2 (file:///C:/Users/User/AppData/Roaming/nvm/v14.19.1/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:34:5)
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

### Reproduction steps

1. Install Shopify CLI version 3 on a windows machine
2. Run shopify theme dev --store=storename command

### Operating System

Windows 11 Pro

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.1

### Shell

Powershell

### Node version (run `node -v` if you're not sure)

14.19.1

### What language and version are you using in your application?

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt], Node 14.19.1

**Comment by Christoph-AK** [comment]
Having the same problem. The server gets started, but the theme files don't actually get synced to shopify. 

On one machine leaving the task running for 5+ minutes finally started the sync. 

Performance of 3.x is so stupidly bad... I wonder if it's an antivirus problem, windows sometimes struggles with apps accessing many small files quickly.

**Comment by amcaplan** [comment]
```
Error: Bundler version 2.3.7 is not supported
```

Have you tried upgrading bundler? 2.3.11 or above is required.
