### ISSUE TITLE
[Bug]: NameError: uninitialized constant ShopifyCLI::IdentityAuth::Servlet

### ISSUE THREAD

**Issue by shawnsan-apollo** [Shopify/cli#2154]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

`shopify theme dev` should load dev environment

### Actual behavior

dev environment doesnt load and terminal log error

### Verbose output

```shell
2023-06-12T20:17:27.658Z: Running command theme dev
  shopify:theme:dev init version: @oclif/core@2.1.4 argv: [ '--verbose' ] +0ms
2023-06-12T20:17:27.675Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-06-12T20:17:27.675Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store ****.myshopify.com:
[]

2023-06-12T20:17:27.676Z: Getting session store...
2023-06-12T20:17:27.677Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "****.myshopify.com"
  }
}

2023-06-12T20:17:27.677Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-06-12T20:17:27.678Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.46.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-06-12T20:17:27.943Z: Request to https://accounts.shopify.com/oauth/introspection completed in 259 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"7b5aaffa760d4ea8e4a3e6c0d69c138d"
 - x-request-id: a13dfcb5-3089-48bf-bafd-ac9ba84ce749
    
2023-06-12T20:17:27.946Z: The identity token is valid: true
2023-06-12T20:17:27.947Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-06-12T20:17:27.947Z: The current session is valid but needs refresh. Refreshing...
2023-06-12T20:17:27.947Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_6beb0a9c46b37d9a4b5e1550eb5483765479d0295f7573ed29adbef0b043bc46&refresh_token=atkn_d94aff16cba1c452d4aac931c8027fa6e1ddbb054cd3ff693836a8d9d8583fb7&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.46.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-06-12T20:17:28.323Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_6beb0a9c46b37d9a4b5e1550eb5483765479d0295f7573ed29adbef0b043bc46&refresh_token=atkn_d94aff16cba1c452d4aac931c8027fa6e1ddbb054cd3ff693836a8d9d8583fb7&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 374 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"1f77cf72cbc1bb20ac67abf64303d981"
 - x-request-id: 4b10f52c-c0ec-4afc-b2e9-62d20326289e
    
2023-06-12T20:17:28.327Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=atkn_78c036d81836667c7f039a960e93fb8b6daaddbc7641b627ad30d7b3a0be2e40
With request headers:
 - User-Agent: Shopify CLI; v=3.46.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-06-12T20:17:28.327Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=atkn_78c036d81836667c7f039a960e93fb8b6daaddbc7641b627ad30d7b3a0be2e40
With request headers:
 - User-Agent: Shopify CLI; v=3.46.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-06-12T20:17:28.558Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=atkn_78c036d81836667c7f039a960e93fb8b6daaddbc7641b627ad30d7b3a0be2e40 completed in 227 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"e48a11487bc045cd242775ffaeeeaf69"
 - x-request-id: 8bcf2468-e776-4cdb-932b-0a9ec7625de3
    
2023-06-12T20:17:28.808Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=atkn_78c036d81836667c7f039a960e93fb8b6daaddbc7641b627ad30d7b3a0be2e40 completed in 479 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"7c271d37ef0452b4c9812b64739440eb"
 - x-request-id: 91761311-b55d-4df3-9bb0-7f5ce56733c0
    
2023-06-12T20:17:28.811Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=atkn_78c036d81836667c7f039a960e93fb8b6daaddbc7641b627ad30d7b3a0be2e40&destination=https%3A%2F%2F****.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.46.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-06-12T20:17:29.054Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=atkn_78c036d81836667c7f039a960e93fb8b6daaddbc7641b627ad30d7b3a0be2e40&destination=https%3A%2F%2F****.myshopify.com%2Fadmin completed in 242 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"544c5c2d278c5e03cb610b8d53eccf0b"
 - x-request-id: e526b2c5-8842-4ce7-aa48-82d5c9ab2c50
    
2023-06-12T20:17:29.056Z: Setting session store...
2023-06-12T20:17:29.063Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2023-06-12T20:17:29.063Z: Getting session store...
2023-06-12T20:17:29.065Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2023-06-12T20:17:29.065Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-06-12T20:17:29.065Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.46.4
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-06-12T20:17:29.247Z: Request to https://accounts.shopify.com/oauth/introspection completed in 180 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"ed1d9ab378c2fbaede80bfe826f1b3bc"
 - x-request-id: b465ef62-6166-4497-ab38-f4662d06ac87
    
2023-06-12T20:17:29.250Z: The identity token is valid: true
2023-06-12T20:17:29.251Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-06-12T20:17:29.251Z: Getting development theme...
2023-06-12T20:17:29.606Z: Request to https://****.myshopify.com/admin/api/unstable/themes/132179427522.json?fields=id completed in 349 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: 31ab0d1b-1bf9-473f-8baa-b6c1ba5c6063
    
╭─ success ──────────────────────────────────────────────────────────────────────────────╮
│                                                                                        │
│  Preview your theme                                                                    │
│    • http://127.0.0.1:9292                                                             │
│                                                                                        │
│  Next steps                                                                            │
│    • Customize your theme at the theme editor                                          │
│    • Share your theme preview                                                          │
│                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────╯

2023-06-12T20:17:29.659Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Users/****/Documents/apollo-projects/New Theme/apollo-scooters-cli

2023-06-12T20:17:29.690Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle -v
  · Working directory: /Users/****/Documents/apollo-projects/New Theme/apollo-scooters-cli

2023-06-12T20:17:29.800Z: Reading the content of file at /opt/homebrew/Cellar/shopify-cli/3.46.4/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2023-06-12T20:17:29.801Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle config set --local path /Users/****/Library/Caches/shopify-gems-nodejs
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.46.4/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-06-12T20:17:29.879Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle config set --local without development:test
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.46.4/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-06-12T20:17:29.955Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle install
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.46.4/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-06-12T20:17:30.129Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle exec /opt/homebrew/opt/ruby/bin/ruby /opt/homebrew/Cellar/shopify-cli/3.46.4/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme serve /Users/****/Documents/apollo-projects/New Theme/apollo-scooters-cli --live-reload hot-reload --theme 132179427522
  · Working directory: /Users/****/Documents/apollo-projects/New Theme/apollo-scooters-cli

✗ An unexpected error occurred.
        To submit an issue include the stack trace.

/opt/homebrew/Cellar/shopify-cli/3.46.4/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/identity_auth.rb:141:in `server': uninitialized constant ShopifyCLI::IdentityAuth::Servlet (NameError)

        server.mount("/", Servlet, self, state_token)
                          ^^^^^^^
        from /opt/homebrew/Cellar/shopify-cli/3.46.4/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/identity_auth.rb:154:in `block in initiate_authentication'
```

### Reproduction steps

1. Run `shopify theme dev --verbose`

### Operating System

Mac OS Ventura 13.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.4

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.3.0

### What language and version are you using in your application?

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

**Comment by isaacroldan** [comment]
Hi @shawnsan-apollo! This should be fixed with the latest CLI version (3.46.5), please update and try again :)
