### ISSUE TITLE
[Bug]: Theme Check Erroring out 

### ISSUE THREAD

**Issue by shawnsan-apollo** [Shopify/cli#2163]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

Running ``shopify theme check`` should complete with out errors

### Actual behavior

Theme check failed with error

### Verbose output

```shell
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Theme check failed with error:
┃ /Users/shawnsantiago/Library/Caches/shopify-gems-nodejs/ruby/3.2.0/gems/theme-check-1.15.0/lib/theme_check/cli.rb:204:in `check': ThemeCheck::Cli::Abort
┃       from /Users/shawnsantiago/Library/Caches/shopify-gems-nodejs/ruby/3.2.0/gems/theme-check-1.15.0/lib/theme_check/cli.rb:128:in `run!'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/check.rb:27:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command/sub_command.rb:15:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:26:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui.rb:177:in `log_output_to'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:15:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:26:in `log'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:50:in `block (2 levels) in <main>'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:49:in `block in <main>'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:59:in `<main>'
┃
```

### Reproduction steps

1. Ran ````shopify theme check```` in terminal

### Operating System

Mac OS Ventura 13.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.5

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.15.0

### What language and version are you using in your application?

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

**Comment by jamieboullt** [comment]
I am having the exact same issue but it is only showing the errors in a repository I made today and not in existing repositories.
```

```  Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Theme check failed with error:
┃ /Users/jamieboullt/Library/Caches/shopify-gems-nodejs/ruby/3.2.0/gems/theme-check-1.15.0/lib/theme_check/cli.rb:204:in `check': ThemeCheck::Cli::Abort
┃       from /Users/jamieboullt/Library/Caches/shopify-gems-nodejs/ruby/3.2.0/gems/theme-check-1.15.0/lib/theme_check/cli.rb:128:in `run!'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/check.rb:27:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command/sub_command.rb:15:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:26:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui.rb:177:in `log_output_to'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:15:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:26:in `log'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:50:in `block (2 levels) in <main>'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:49:in `block in <main>'
┃       from /opt/homebrew/Cellar/shopify-cli/3.46.5/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:59:in `<main>'
