### ISSUE TITLE
[Bug]: Shopify-cli is up to date but many commands are missing

### ISSUE THREAD

**Issue by webyze** [Shopify/cli#2884]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

when writing
`shopify app`
it should list the commands that are available:
https://shopify.dev/docs/apps/tools/cli/commands

### Actual behavior

Only some of the commands are available:
```
> shopify app

Build Shopify apps.

USAGE
  $ shopify app COMMAND

TOPICS
  app env       Manage environment variables.
  app function  Manage Shopify Functions.
  app generate  Scaffold an Extension.

COMMANDS
  app build       Build the app.
  app deploy      Deploy your Shopify app.
  app dev         Run the app.
  app info        Print basic information about your app and extensions.
  app update-url  Update your app and redirect URLs in the Partners Dashboard.
```

Of course running `shopify app release` and any other command like that doesn't work which is preventing us from pushing a new app extension. (Especially that it's no longer possible to do so in the partner dashboard, so we're totally stuck)

### Reproduction steps

1. shopify upgrade
2. shopify app

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.7.0

### What language and version are you using in your application?

Node

**Comment by gonzaloriestra** [comment]
Hi! Thanks for creating the issue.

How have you installed the CLI? Are you actually running it with a package manager (like `npm run shopify app`)?

Could you share the output of these commands?
- `npm run shopify version`
- `DEBUG=* npm run shopify app --verbose`

**Comment by gonzaloriestra** [comment]
It looks like you have a global installation via Homebrew which is missing some packages.

The recommended way to use the Shopify CLI for apps is as a dependency of your project, as explained here: https://shopify.dev/docs/apps/tools/cli#getting-started

So I'd recommend you to:
- Uninstall your Homebrew version with: `brew uninstall shopify-cli`
- Ensure you have these dependencies in your package json:
```
    "@shopify/app": "3.49.3",
    "@shopify/cli": "3.49.3",
```

**Comment by gonzaloriestra** [comment]
Hmm. To ensure there's no global installation, you should run:
- `npm uninstall -g @shopify/cli`
- `npm uninstall -g @shopify/app`

And how did you install it? You should do it from the root of your project with:
- `npm add @shopify/cli`
- `npm add @shopify/app`

If it doesn't work, could you share again the output of `DEBUG=* npm run shopify app --verbose`?

**Comment by webyze** [comment]
Unfortunately still the same:
```
webyze@Webyzes-Mac-Studio live-preview-options % DEBUG=* npm run shopify app --verbose
npm verb cli /Users/webyze/.nvm/versions/node/v20.7.0/bin/node /Users/webyze/.nvm/versions/node/v20.7.0/bin/npm
npm info using npm@10.1.0
npm info using node@v20.7.0
npm verb title npm run shopify app
npm verb argv "run" "shopify" "app" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/Users/webyze/.npm/_logs/2023-09-29T14_12_00_628Z-
npm verb logfile /Users/webyze/.npm/_logs/2023-09-29T14_12_00_628Z-debug-0.log

> live-preview-options@1.0.0 shopify
> shopify app

  config reading core plugin /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/oclif.manifest.json +0ms
  config:@shopify/cli using manifest from /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/oclif.manifest.json +0ms
  config reading user plugins pjson /Users/webyze/.local/share/@shopify/cli/package.json +0ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/package.json +0ms
  config loading plugins [ { name: '@shopify/app', tag: 'latest', type: 'user' } ] +0ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/package.json/package.json +0ms
  config reading user plugin /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/app +0ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/app/package.json +0ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/app/oclif.manifest.json +0ms
  config:@shopify/app using manifest from /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/app/oclif.manifest.json +0ms
  config loading plugins [ '@shopify/plugin-ngrok' ] +2ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/app/package.json +0ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/package.json +0ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/node_modules/package.json +0ms
  config reading user plugin /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/plugin-ngrok +0ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/plugin-ngrok/package.json +0ms
  config loadJSON /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/plugin-ngrok/oclif.manifest.json +0ms
  config:@shopify/plugin-ngrok using manifest from /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/plugin-ngrok/oclif.manifest.json +0ms
  config loading plugins [
  '@shopify/app',
  '@shopify/theme',
  '@shopify/plugin-did-you-mean',
  '@shopify/cli-hydrogen',
  '@oclif/plugin-help',
  '@oclif/plugin-plugins',
  '@oclif/plugin-commands'
] +1ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/package.json +0ms
  config reading core plugin /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-help +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-help/package.json +0ms
  config reading core plugin /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-plugins +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-plugins/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/package.json +0ms
  config reading core plugin /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/app +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/app/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/package.json +0ms
  config reading core plugin /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/plugin-did-you-mean +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/plugin-did-you-mean/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/package.json +0ms
  config reading core plugin /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-commands +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-commands/package.json +0ms
  config:@oclif/plugin-plugins using manifest from /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  config:@oclif/plugin-help using manifest from /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/plugin-did-you-mean/oclif.manifest.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-commands/oclif.manifest.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/app/oclif.manifest.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/Webyze/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/package.json +0ms
  config loadJSON /Volumes/ExternalSSD/package.json +0ms
  config loadJSON /Volumes/package.json +0ms
  config:@shopify/plugin-did-you-mean using manifest from /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/plugin-did-you-mean/oclif.manifest.json +0ms
  config loadJSON /Volumes/package.json +0ms
  config:@oclif/plugin-commands using manifest from /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-commands/oclif.manifest.json +0ms
  config:@shopify/app using manifest from /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/app/oclif.manifest.json +0ms
  config loadJSON /package.json +0ms
  config loadJSON /package.json +0ms
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli',
  name: '@shopify/theme'
}
    at Plugin.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/plugin.js:114:19)
    at async /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:525:17
    at async Promise.all (index 1)
    at async Config.loadPlugins (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:512:9)
    at async Config.loadCorePlugins (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:169:13)
    at async Config.loadPluginsAndCommands (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:160:9)
    at async Config.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:146:9)
    at async Config.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:83:9)
    at async run (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/main.js:53:20)
module: @oclif/core@2.11.7
task: loadPlugins
plugin: @shopify/cli
root: /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli
See more details with DEBUG=*
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli',
  name: '@shopify/theme'
}
    at Plugin.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/plugin.js:114:19)
    at async /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:525:17
    at async Promise.all (index 1)
    at async Config.loadPlugins (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:512:9)
    at async Config.loadCorePlugins (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:169:13)
    at async Config.loadPluginsAndCommands (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:160:9)
    at async Config.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:146:9)
    at async Config.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:83:9)
    at async run (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/main.js:53:20)
module: @oclif/core@2.11.7
task: loadPlugins
plugin: @shopify/cli
root: /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli
See more details with DEBUG=*
  config config done +5ms
  config start init hook +1ms
  config init hook done +0ms
  config runCommand help [ 'app' ] +0ms
  config:@oclif/plugin-help (require) /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/plugin-help/lib/commands/help.js +6ms
  config start prerun hook +3ms
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli',
  name: '@shopify/cli-hydrogen'
}
    at Plugin.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/plugin.js:114:19)
    at async /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:525:17
    at async Promise.all (index 3)
    at async Config.loadPlugins (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:512:9)
    at async Config.loadCorePlugins (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:169:13)
    at async Config.loadPluginsAndCommands (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:160:9)
    at async Config.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:146:9)
    at async Config.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:83:9)
    at async run (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/main.js:53:20)
module: @oclif/core@2.11.7
task: loadPlugins
plugin: @shopify/cli
root: /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli
See more details with DEBUG=*
Error Plugin: @shopify/cli: could not find package.json with {
  type: 'core',
  root: '/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli',
  name: '@shopify/cli-hydrogen'
}
    at Plugin.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/plugin.js:114:19)
    at async /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:525:17
    at async Promise.all (index 3)
    at async Config.loadPlugins (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:512:9)
    at async Config.loadCorePlugins (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:169:13)
    at async Config.loadPluginsAndCommands (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:160:9)
    at async Config.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:146:9)
    at async Config.load (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/config/config.js:83:9)
    at async run (/Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@oclif/core/lib/main.js:53:20)
module: @oclif/core@2.11.7
task: loadPlugins
plugin: @shopify/cli
root: /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli
See more details with DEBUG=*
  shopify:@shopify/cli:hooks:prerun start (import) /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/dist/hooks/prerun.js +0ms
  shopify:@shopify/cli:hooks:prerun done +1ms
  config prerun hook done +4ms
  shopify:help init version: @oclif/core@2.11.7 argv: [ 'app' ] +0ms
Build Shopify apps.

USAGE
  $ shopify app COMMAND

TOPICS
  app env       Manage environment variables.
  app function  Manage Shopify Functions.
  app generate  Scaffold an Extension.

COMMANDS
  app build       Build the app.
  app deploy      Deploy your Shopify app.
  app dev         Run the app.
  app info        Print basic information about your app and extensions.
  app update-url  Update your app and redirect URLs in the Partners Dashboard.

  config start postrun hook +5ms
  shopify:@shopify/cli:hooks:postrun start (import) /Volumes/ExternalSSD/Webyze/InfiniteLivePreviewOptions/shopify-node-app/live-preview-options/node_modules/@shopify/cli/dist/hooks/postrun.js +0ms
  config start public_command_metadata hook +2ms
  shopify:@shopify/app:hooks:public_command_metadata start (import) /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/app/dist/cli/hooks/public_metadata.js +0ms
  shopify:@shopify/app:hooks:public_command_metadata done +0ms
  config public_command_metadata hook done +212ms
  config start sensitive_command_metadata hook +0ms
  shopify:@shopify/app:hooks:sensitive_command_metadata start (import) /Users/webyze/.local/share/@shopify/cli/node_modules/@shopify/app/dist/cli/hooks/sensitive_metadata.js +0ms
  shopify:@shopify/app:hooks:sensitive_command_metadata done +0ms
  config sensitive_command_metadata hook done +1ms
  shopify:@shopify/cli:hooks:postrun done +346ms
  config postrun hook done +133ms
npm verb exit 0
npm info ok
```

I really don't understand why it doesn't work. It's the exact same set up as my laptop... I reinstalled NodeJS, even reinstalled ruby, deleted the `node_modules` folders and reinstalled from scratch. Deleted the package-lock.json...

**Comment by webyze** [comment]
Woohoo! You found the root cause!!
I removed that folder and it's working perfectly fine now! Thank you for your help, I appreciate that!

It was probably a folder created at some point by brew but that was never deleted even after uninstalling!

Thanks again Gonzalo!
