### ISSUE TITLE
[Bug]: "TypeError: JSON.stringify(...).replaceAll is not a function" when accessing app's shareable link, on new app created using "yarn create @shopify/app"

### ISSUE THREAD

**Issue by nickjanssen** [Shopify/cli#301]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

App should load normally without errors

### Actual behavior

Right after creating a new app using the latest CLI, then when running `yarn dev` the following error shows in the browser when accessing the shareable app link :

```
TypeError: JSON.stringify(...).replaceAll is not a function
    at topLevelAuthRedirect (file:///Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/helpers/top-level-auth-redirect.js:21:48)
    at file:///Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/middleware/auth.js:51:7
    at Layer.handle [as handle_request] (/Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/node_modules/express/lib/router/layer.js:95:5)
    at /Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/node_modules/express/lib/router/index.js:280:10)
    at cookieParser (/Users/nickjanssen/dev/shopify/cli/el-nick-test-app-cliv3/web/node_modules/cookie-parser/index.js:71:5)
```

### Stack trace

```shell
See above
```

### Reproduction steps

1. Delete any old dev apps in your store
2. yarn create @shopify/app
3. cd [name-of-app]
4. yarn dev
5. Open app's shareable link

### Operating System

macOS Monterey 12.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.7.1

### Shell

iTerm2

### Node version (run `node -v` if you're not sure)

v14.19.1

### What language and version are you using in your application?

Node v14.19.1

**Comment by nickjanssen** [comment]
Solved when using latest stable node version 16 (was using v14.19.1)
