### ISSUE TITLE
[Bug]: Local Null JSON template breaks theme pull

### ISSUE THREAD

**Issue by notkurt** [Shopify/cli#3043]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Running theme pull where the local file is set to null, overwrites null'ed file with the JSON of the new file. 

Somehow, along the way, certain templates were null'ed. As far as I can tell, this occurred during another theme pull. 

Seems to related to #1810 #1485 

### Actual behavior

Breaks theme pull. 

### Verbose output

```shell
/opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/prompt/interactive_options.rb:256:in `wait_for_user_input': Interrupt (Interrupt)
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/prompt/interactive_options.rb:246:in `process_input_until_redraw_required'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/prompt/interactive_options.rb:74:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/prompt/interactive_options.rb:27:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:230:in `interactive_prompt'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:203:in `ask_interactive'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/exception_reporter.rb:68:in `report_error?'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/exception_reporter.rb:57:in `report?'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/exception_reporter.rb:26:in `report'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:31:in `handle_exception'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:71:in `block in install!'
/opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/file.rb:129:in `visit_document': undefined method `[]' for nil:NilClass (NoMethodError)

          visit_hash(value["sections"])
                          ^^^^^^^^^^^^
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/file.rb:118:in `normalize_json'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/file.rb:82:in `checksum'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer.rb:189:in `enqueueable?'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer.rb:267:in `enqueue'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer.rb:91:in `block in enqueue_get'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer.rb:91:in `each'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer.rb:91:in `enqueue_get'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/forwardable.rb:240:in `enqueue_get'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer/downloader.rb:34:in `download!'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer.rb:173:in `download_theme!'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `public_send'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `block in progress'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/ui/sync_progress_bar.rb:10:in `progress'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/pull.rb:64:in `block in call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/pull.rb:63:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command/sub_command.rb:15:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/command.rb:26:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui.rb:177:in `log_output_to'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/executor.rb:15:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:26:in `log'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:50:in `block (2 levels) in <main>'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:49:in `block in <main>'
        from /opt/homebrew/Cellar/shopify-cli/3.48.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:59:in `<main>'
```

### Reproduction steps

1. Set a template's JSON contents within the directory to be null. 
2. Attempt to pull that specific JSON file from an external theme, or all files. 
3. Theme pull will break. 

### Operating System

Darwin Kurt-10SQ.local 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.48.0

### Shell

bash, fish

### Node version (run `node -v` if you're not sure)

v18, v20

**Comment by shauns** [comment]
cc @Shopify/theme-code-tools
