### ISSUE TITLE
[Bug]: Shopify CLI is not working - Command failed with exit code 5: bundle install

### ISSUE THREAD

**Issue by Haris014** [Shopify/cli#3125]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Shopify theme preview on local host successfully.

### Actual behavior

An explosion of Gem errors.

### Verbose output

```shell
An explosion of Gem errors.

$ shopify theme dev
── external error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `bundle install`

Command failed with exit code 5: bundle install
Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/ast-2.4.2.gem`. It is likely that you need to
grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/rb-fsevent-0.11.2.gem`. It is likely that you
need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/racc-1.7.3.gem`. It is likely that you need to
 grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/ast-2.4.2.gem`. It is likely that you need to
grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/liquid-5.4.0.gem`. It is likely that you need
to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/ast-2.4.2.gem`. It is likely that you need to
grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/racc-1.7.3.gem`. It is likely that you need to
 grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/rb-fsevent-0.11.2.gem`. It is likely that you
need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/concurrent-ruby-1.2.2.gem`. It is likely that
you need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/liquid-5.4.0.gem`. It is likely that you need
to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/racc-1.7.3.gem`. It is likely that you need to
 grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/rb-fsevent-0.11.2.gem`. It is likely that you
need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/concurrent-ruby-1.2.2.gem`. It is likely that
you need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/liquid-5.4.0.gem`. It is likely that you need
to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/concurrent-ruby-1.2.2.gem`. It is likely that
you need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/ffi-1.16.3.gem`. It is likely that you need to
 grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/ffi-1.16.3.gem`. It is likely that you need to
 grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/var/lib/gems/3.0.0/cache/ffi-1.16.3.gem`. It is likely that you need to
 grant write permissions for that path.
Bundler::PermissionError: There was an error while trying to write to
`/var/lib/gems/3.0.0/cache/ast-2.4.2.gem`. It is likely that you need to grant
write permissions for that path.
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/shared_helpers.rb:105:in
`rescue in filesystem_access'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/shared_helpers.rb:102:in
`filesystem_access'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/rubygems_integration.rb:483:in
`block in download_gem'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/retry.rb:40:in `run'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/retry.rb:30:in `attempt'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/rubygems_integration.rb:474:in
`download_gem'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:481:in
`download_gem'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:443:in
`fetch_gem'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:427:in
`fetch_gem_if_possible'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:161:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:130:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:121:in
`block in worker_pool'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:62:in
`apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:90:in `block (2
levels) in create_threads'

An error occurred while installing ast (2.4.2), and Bundler cannot continue.

In Gemfile:
  theme-check was resolved to 1.15.0, which depends on
    parser was resolved to 3.2.2.4, which depends on
      ast
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Fetching ffi 1.16.3
Fetching liquid 5.4.0
Fetching racc 1.7.3
Fetching concurrent-ruby 1.2.2
Fetching rb-fsevent 0.11.2
Fetching ast 2.4.2



────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                          │
│  getaddrinfo EAI_AGAIN notify.bugsnag.com                                                                                                │
│                                                                                                                                          │
│  To investigate the issue, examine this stack trace:                                                                                     │
│    at onlookupall [as oncomplete] (node:dns:118)                                                                                         │
│                                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

    Error: getaddrinfo EAI_AGAIN notify.bugsnag.com
    Code: EAI_AGAIN
```

### Reproduction steps

I am using Ubuntu 22.04.3 LTS. I have installed shopify cli and all prerequisite again.
But its still not working.

Node-v: 20.9.0
npm-v: 10.1.0
shopify --version: @shopify/cli/3.51.0 linux-x64 
node-v: 20.9.0
ruby-v: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

Use all above versions and run : Shopify theme pull --store=xx.myshopify.com 

### Operating System

Ubuntu 22.04.3 LTS

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.51.0 linux-x64

### Shell

bash

### Node version (run `node -v` if you're not sure)

20.9.0

### What language and version are you using in your application?

ruby 3.0.2p107 - node 20.9.0

**Comment by amcaplan** [comment]
I suspect this is a recurrence of #3102 which I'm working on at the moment.

**Comment by Haris014** [comment]
> @Haris014 can you please try 3.50.2 and see if it works for you?

What about the ruby and node version? As you can see all the erros are related ruby/gems/bundle. So i think so i should have change ruby version instead of shopify cli version. Please let me know how much you will take to resolve these error?

**Comment by amcaplan** [comment]
@Haris014 the CLI's invocation of Ruby changed in 3.50. We are fixing, but in the meantime 3.50 should have the correct (previous) behavior.

**Comment by DungNgDinh** [comment]
I am facing the same issue. Did you solve it?
Windows 11
Shopify cli 3.59.1
Ruby 3.2.4
Gem 3.4.19
Bundle 2.5.10
npm 10.7.0
node 22.2.0

**Comment by navdeep-soni** [comment]
Hi @DungNgDinh 

Were you able to resolve it?

**Comment by devatshopify** [comment]
I am a windows user and I am facing the same type of issue
node version : 20.14.0
npm - 10.7.0
shopify cli version : 3.61.0
ruby : 3.3.2
gem : 3.5.11
bundler version: 2.5.11

I am stuck at this issue from a long time . I need an immediate and permanent solution on this please assist me @DungNgDinh @amcaplan @navdeep-soni @Smush1 @Haris014

**Comment by navdeep-soni** [comment]
sorry @devatshopify .. no luck but in my research some were able to get a breakthrough by removing space from urls (eg: c:\users\steve martin\"

**Comment by Inument-Dev1** [comment]
> @devatshopify @amcaplan @DungNgDinh @Haris014 @navdeep-soni I got it working finally (for windows). Here are the steps I followed. It might help someone.
> 
> 1. from ruby downloads (https://rubyinstaller.org/downloads/) , I installed 3.0 version specifically as doc says: [Ruby+Devkit 3.0.6-1 (x64)](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.0.6-1/rubyinstaller-devkit-3.0.6-1-x64.exe)
> 2. Installed the above ruby with all the options.
> 3. Opened command prompt and ran this command (after all ruby installations): ridk enable
> 4. Closed Visual Studio code and opened back with administrator permission (press windows icon > search vs code > right click > run as administrator)
> 5. Opened respective project and ran: shopify theme dev (got another bundler version error)
> 6. Ran following command: gem install bundler
> 7. Then ran: shopify theme dev
> 
> And it worked
> 
> Try this and let me know

Yes, this also fixed my issue. I used the installer and installed the msys2 toolchain with the same installer. It gives another error
"Bundler version 2.2.33 is not supported"
To fix it I need to run `gem install bundler`

**Comment by khairuzzaman** [comment]
> @devatshopify @amcaplan @DungNgDinh @Haris014 @navdeep-soni I got it working finally (for windows). Here are the steps I followed. It might help someone.
> 
> 1. from ruby downloads (https://rubyinstaller.org/downloads/) , I installed 3.0 version specifically as doc says: [Ruby+Devkit 3.0.6-1 (x64)](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.0.6-1/rubyinstaller-devkit-3.0.6-1-x64.exe)
> 2. Installed the above ruby with all the options.
> 3. Opened command prompt and ran this command (after all ruby installations): ridk enable
> 4. Closed Visual Studio code and opened back with administrator permission (press windows icon > search vs code > right click > run as administrator)
> 5. Opened respective project and ran: shopify theme dev (got another bundler version error)
> 6. Ran following command: gem install bundler
> 7. Then ran: shopify theme dev
> 
> And it worked
> 
> Try this and let me know

Yes, this also fixed my issue. I used the installer and installed the msys2 toolchain with the same installer. It gives another error
"Bundler version 2.2.33 is not supported"
To fix it I need to run gem install bundler

**Comment by Smush1** [comment]
Thanks for the update @khairuzzaman
