### ISSUE TITLE
[Bug]:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=23.227.38.74:443 state=error: unexpected eof while reading (OpenSSL::SSL::SSLError)         from C:/Ruby32-x64/lib/ruby/3.2.0/net/protocol.rb:46:in `ssl_socket_connect'

### ISSUE THREAD

**Issue by kuww** [Shopify/cli#3243]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

shopify theme dev Normal operation

### Actual behavior

X An unexpected error occurred.
        To submit an issue include the stack trace.

? Send an anonymized error report to Shopify? (You chose: No, don't send)
C:/Ruby32-x64/lib/ruby/3.2.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=23.227.38.74:443 state=error: unexpected eof while reading (OpenSSL::SSL::SSLError)
        from C:/Ruby32-x64/lib/ruby/3.2.0/net/protocol.rb:46:in `ssl_socket_connect'

### Verbose output

```shell
2024-01-10T06:47:33.876Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-01-10T06:47:33.877Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.53.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2024-01-10T06:47:34.566Z: Request to https://accounts.shopify.com/oauth/introspection completed in 682 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"1a817907d188c4409f7fb2f928e3dd8d"
 - x-request-id: 28075578-86b1-496f-8d55-bbcbaee6903b
    
2024-01-10T06:47:34.572Z: The identity token is valid: true
2024-01-10T06:47:34.572Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2024-01-10T06:47:34.573Z: The current session is valid but needs refresh. Refreshing...
2024-01-10T06:47:34.574Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI4Pr4rAYQgLP5rAZSJggBEhDP6VEmtV9NUoIgCRZ3jX1SGhD4AfDLo7RM95LcIBcgDmtyEkARrrRDQtL1U32JBpntreTcw4_hhRpu0BFQcjRSh4gg76lIUUGqHDp07t9WDESHOefiHYjBYZ5vxwRvqTYu3mUP&refresh_token=atkn_CiEI4Pr4rAYQ4JSXrgaiARIKEPgB8MujtEz3ktwgFyAOa3ISQJq6d2zFQ8v1bky1ASMPO5_VXmdgL37hNZ0yH7mqBxtU6KdnnumTUuqiw6orc2jN9ZJwIwe041bBZlb4ZRMBwQ4&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.53.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2024-01-10T06:47:36.478Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI4Pr4rAYQgLP5rAZSJggBEhDP6VEmtV9NUoIgCRZ3jX1SGhD4AfDLo7RM95LcIBcgDmtyEkARrrRDQtL1U32JBpntreTcw4_hhRpu0BFQcjRSh4gg76lIUUGqHDp07t9WDESHOefiHYjBYZ5vxwRvqTYu3mUP&refresh_token=atkn_CiEI4Pr4rAYQ4JSXrgaiARIKEPgB8MujtEz3ktwgFyAOa3ISQJq6d2zFQ8v1bky1ASMPO5_VXmdgL37hNZ0yH7mqBxtU6KdnnumTUuqiw6orc2jN9ZJwIwe041bBZlb4ZRMBwQ4&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 1902 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"c10f6fb1235bcf6b0eeabc00ec230884"
 - x-request-id: 195c19dc-859c-4851-b188-a079a39b54cb
    
2024-01-10T06:47:36.484Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.53.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2024-01-10T06:47:36.489Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.53.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2024-01-10T06:47:36.491Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.53.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2024-01-10T06:47:36.492Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Fashimaryhumanhair.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.53.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2024-01-10T06:47:37.185Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=**** completed in 691 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"ce79ca84bbd62984b5b6f84da17a02ba"
 - x-request-id: 23420378-a1e8-4088-80a4-a8b412296d55
    
2024-01-10T06:47:37.413Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=**** completed in 918 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"0376aec7139d890f03e987c513bda8bc"
 - x-request-id: ed44c2af-7134-43f9-b6d5-91aa026ce629
    
2024-01-10T06:47:38.347Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=**** completed in 1853 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"4c61bcbff95a3db7052cc29e57c8a0b8"
 - x-request-id: c6170498-cd06-4111-bcde-47e584dc4c0a
    
2024-01-10T06:47:42.451Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Fashimaryhumanhair.myshopify.com%2Fadmin completed in 5956 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"af5e94ef4aef2ed0c0352d2f575d6663"
 - x-request-id: 177d0683-f493-421a-9a63-38e68780e417
    
2024-01-10T06:47:42.456Z: Setting session store...
2024-01-10T06:47:42.461Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2024-01-10T06:47:42.461Z: Getting session store...
2024-01-10T06:47:42.462Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2024-01-10T06:47:42.464Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-01-10T06:47:42.465Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.53.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json

2024-01-10T06:47:43.388Z: Request to https://accounts.shopify.com/oauth/introspection completed in 922 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"709ecb4dc1a93dda35c050d321335357"
 - x-request-id: ee60834c-bff5-484c-9370-1602359f51e4
    
2024-01-10T06:47:43.390Z: The identity token is valid: true
2024-01-10T06:47:43.391Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2024-01-10T06:47:43.392Z: Getting development theme...
termial proxy
  https-proxy-agent Creating new HttpsProxyAgent instance: 'http://127.0.0.1:10809/' +0ms
  https-proxy-agent Creating `net.Socket`: { ALPNProtocols: [ 'http/1.1' ], host: '127.0.0.1', port: 10809 } +1ms
  https-proxy-agent:parse-proxy-response got proxy server response: 'HTTP/1.1 200 Connection established' {} +0ms
  https-proxy-agent Upgrading socket connection to TLS +2ms
2024-01-10T06:47:44.170Z: Request to https://ashimaryhumanhair.myshopify.com/admin/api/unstable/themes/133716017334.json?fields=id%2Cprocessing completed in 774 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: 93a4e7ab-450b-497d-b702-553553f16d2c
    
╭─ success ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                  │
│  Preview your theme                                                                                                                              │
│    • http://127.0.0.1:9292 [1]                                                                                                                   │
│                                                                                                                                                  │
│  Next steps                                                                                                                                      │
│    • Customize your theme at the theme editor [2]                                                                                                │
│    • Share your theme preview [3] (https://ashimaryhumanhair.myshopify.com/?preview_theme_id=133716017334)                                       │
│                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[1] http://127.0.0.1:9292
[2] https://ashimaryhumanhair.myshopify.com/admin/themes/133716017334/editor
[3] https://ashimaryhumanhair.myshopify.com/?preview_theme_id=133716017334

2024-01-10T06:47:44.257Z: 
Running system process:
  · Command: ruby -v
  · Working directory: E:/a

2024-01-10T06:47:44.272Z: 
Running system process:
  · Command: bundle -v
  · Working directory: E:/a

2024-01-10T06:47:44.455Z: Creating directory at C:/Users/Administrator/AppData/Local/shopify-cli-nodejs/Cache/vendor/ruby-cli/2.35.0...
2024-01-10T06:47:44.457Z: Reading the content of file at C:/Users/Administrator/AppData/Local/shopify-cli-nodejs/Cache/vendor/ruby-cli/2.35.0/Gemfile...
2024-01-10T06:47:44.460Z:
Running system process:
  · Command: bundle install
  · Working directory: C:/Users/Administrator/AppData/Local/shopify-cli-nodejs/Cache/vendor/ruby-cli/2.35.0

2024-01-10T06:47:44.880Z: 
Running system process:
  · Command: bundle exec shopify theme serve E:/a --live-reload hot-reload --theme 133716017334 --overwrite-json undefined
  · Working directory: E:/a

┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ DEBUG GET https://ashimaryhumanhair.myshopify.com/admin/api/unstable/themes.json with X-Request-Id: 137d9eeb-a7ca-4c2a-968f-8c2364fdf798
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (15.51s) ━━━
X An unexpected error occurred.
        To submit an issue include the stack trace.

? Send an anonymized error report to Shopify? (You chose: No, don't send)
C:/Ruby32-x64/lib/ruby/3.2.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=23.227.38.74:443 state=error: unexpected eof while reading (OpenSSL::SSL::SSLError)
        from C:/Ruby32-x64/lib/ruby/3.2.0/net/protocol.rb:46:in `ssl_socket_connect'
        from C:/Ruby32-x64/lib/ruby/3.2.0/net/http.rb:1342:in `connect'
        from C:/Ruby32-x64/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
        from C:/Ruby32-x64/lib/ruby/3.2.0/net/http.rb:1237:in `start'
        from C:/Ruby32-x64/lib/ruby/3.2.0/net/http.rb:1817:in `request'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/http_request.rb:39:in `request'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/http_request.rb:19:in `get'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/api.rb:64:in `block in request'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/api.rb:89:in `request'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/admin_api.rb:95:in `rest_request'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/theme_admin_api.rb:38:in `rest_request'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/theme_admin_api.rb:18:in `get'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/theme.rb:182:in `fetch_themes'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/theme.rb:166:in `find'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/theme.rb:154:in `find_by_identifier'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/dev_server.rb:193:in `theme'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/dev_server.rb:293:in `syncing_theme_message'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/dev_server.rb:174:in `block in sync_theme'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/dev_server.rb:173:in `sync_theme'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/dev_server.rb:106:in `start'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/theme/dev_server.rb:66:in `start'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/project_types/theme/commands/serve.rb:50:in `call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/command.rb:27:in `call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/core/executor.rb:15:in `call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/core/monorail.rb:26:in `log'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/lib/shopify_cli/core/entry_point.rb:16:in `call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/bin/shopify:49:in `block in <top (required)>'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/gems/shopify-cli-2.35.0/bin/shopify:59:in `<top (required)>'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/bin/shopify:25:in `load'
        from C:/Users/Administrator/AppData/Local/shopify-gems-nodejs/Cache/ruby/3.2.0/bin/shopify:25:in `<main>'
```

### Reproduction steps

1.shopify theme dev  --verbose

### Operating System

windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

Current Shopify CLI version: 3.53.0

**Comment by woke24** [comment]
I have the same issue，headache

**Comment by xuShuang45** [comment]
If you are in China, this is caused by the domestic firewall. Please set the system proxy and try again. If you use windows powershell, you can use $Env:HTTP_PROXY = 'http://you proxy', $Env:HTTPS_PROXY = 'http://youproxy'

**Comment by woke24** [comment]
thanks，I use theme-kit now，It works perfect!



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 17, 2024 16:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Shopify/cli] [Bug]:in `connect_nonblock': SSL_connect returned=1errno=0 peeraddr=23.227.38.74:443 state=error: unexpected eof while reading(OpenSSL::SSL::SSLError)         fromC:/Ruby32-x64/lib/ruby/3.2.0/net/protocol.rb:46:in `ssl_socket_connect' (Issue#3243)




 
If you are in China, this is caused by the domestic firewall. Please set the system proxy and try again. If you use windows powershell, you can use $Env:HTTP_PROXY = 'http://you proxy', $Env:HTTPS_PROXY = 'http://youproxy'

**Comment by narutopden** [comment]
I am also facing this issue, is there any solution from Shopify?
