### ISSUE TITLE
[Bug]: Cloudflared binary postinstall script - fail on version check

### ISSUE THREAD

**Issue by appleseed-iii** [Shopify/cli#3267]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

on a Mac M3 the line 66 of `@shopify/plugin-cloudflare/scripts/postinstall.js` fails.

```node
const versionArray = execFileSync(binTarget, ['--version'], {encoding: 'utf8'}).split(' ');
```

I've tested this on a Mac M1 & it works fine. 

### Actual behavior

`const versionArray = execFileSync(binTarget, ['--version'], {encoding: 'utf8'}).split(' ')` should return the versionArray; however, it fails.

### Verbose output

```shell
shopify/plugin-cloudflare@3.53.0 postinstall /.../shopify-test/extensive-policy-app/node_modules/.pnpm/@shopify+plugin-cloudflare@3.53.0_@types+node@20.11.0_@types+react@18.2.47_typescript@5.3.3/node_modules/@shopify/plugin-cloudflare
> node scripts/postinstall.js

node:internal/errors:563
    ErrorCaptureStackTrace(err);
    ^

<ref *1> Error: spawnSync /.../shopify-test/extensive-policy-app/node_modules/.pnpm/@shopify+plugin-cloudflare@3.53.0_@types+node@20.11.0_@types+react@18.2.47_typescript@5.3.3/node_modules/@shopify/plugin-cloudflare/bin/cloudflared Unknown system error -86
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:876:24)
    at execFileSync (node:child_process:919:15)
    at install (file:///.../shopify-test/extensive-policy-app/node_modules/.pnpm/@shopify+plugin-cloudflare@3.53.0_@types+node@20.11.0_@types+react@18.2.47_typescript@5.3.3/node_modules/@shopify/plugin-cloudflare/scripts/postinstall.js:66:26)
    at file:///.../shopify-test/extensive-policy-app/node_modules/.pnpm/@shopify+plugin-cloudflare@3.53.0_@types+node@20.11.0_@types+react@18.2.47_typescript@5.3.3/node_modules/@shopify/plugin-cloudflare/scripts/postinstall.js:120:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawnSync /.../shopify-test/extensive-policy-app/node_modules/.pnpm/@shopify+plugin-cloudflare@3.53.0_@types+node@20.11.0_@types+react@18.2.47_typescript@5.3.3/node_modules/@shopify/plugin-cloudflare/bin/cloudflared',
  path: '/.../shopify-test/extensive-policy-app/node_modules/.pnpm/@shopify+plugin-cloudflare@3.53.0_@types+node@20.11.0_@types+react@18.2.47_typescript@5.3.3/node_modules/@shopify/plugin-cloudflare/bin/cloudflared',
  spawnargs: [ '--version' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

### Reproduction steps

1. follow shopify's getting started steps with pnpm to create the sample remix app https://shopify.dev/docs/apps/getting-started/create
2. after app setup `pnpm i` works unless postinstall scripts run. On the re-run of the `plugin-cloudflare` postinstall script the execFileSync fails. One reason postinstall scripts might run is if `.npmrc` includes `node-linker = hoisted`
3. Regardless of the configuration noted in step 2 above you can also recreate this issue by manually re-running the plugin-cloudflare postinstall script so that the version check runs (and fails :sob)

### Operating System

Mac OS Sonoma 14.2.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.53.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.11.0

### What language and version are you using in your application?

Node

**Comment by appleseed-iii** [comment]
I also put a re-creation here:

https://github.com/appleseed-iii/shopify-cli-postinstall

**Comment by appleseed-iii** [comment]
yea looks like shopify is using [2023.5.1](https://github.com/Shopify/cli/blob/main/packages/plugin-cloudflare/scripts/postinstall.js#L12)

but homebrew is using [2024.1.3](https://formulae.brew.sh/formula/cloudflared)

**Comment by appleseed-iii** [comment]
ok, rosetta fixes the issue completely. nice i wasn't aware of that

**Comment by isaacroldan** [comment]
That's a good catch, we check this specific error only when you try to run the tunnel (because we assume the first time the install always work). We should check for this error also when running the `--version` command.
