### ISSUE TITLE
[Bug]: Shopify CLI is broken by latest version of flori/json (v2.7.1) "[LoadError] cannot load such file -- json"

### ISSUE THREAD

**Issue by patmead** [Shopify/cli#3346]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

After authenticating, the CLI should be able to retrieve theme files using `shopify theme pull`

### Actual behavior

It fails with the error below, despite the  CLI not having been modified locally in any way.

### Verbose output

```shell
$ shopify theme pull

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- json
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- json
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- json
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require': cannot load such file -- json (LoadError)
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/context.rb:6:in `<top (required)>'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli.rb:133:in `<module:ShopifyCLI>'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli.rb:42:in `<top (required)>'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:9:in `require'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/load_shopify.rb:18:in `<top (required)>'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:45:in `require_relative'
	from ~/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:45:in `<main>'
```

### Reproduction steps

1. Install all dependencies as per https://shopify.dev/docs/themes/tools/cli/install
2. Install Shopify CLI using `npm install -g @shopify/cli @shopify/theme`
3. Verfiy using `shopify version`
4. Attempt to retrieve theme files with `shopify theme pull` (authenticate if required)

### Operating System

Arch Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.55.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

v21.6.1

### What language and version are you using in your application?

Liquid

**Comment by flortsch** [comment]
Still relevant.

**Comment by gil-roboute** [comment]
**Still relevant - executing 'shopify theme dev --store storename' presents the same issue of being unable to load JSON.**
```

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- json
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- json
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

/home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:15:in `require': cannot load such file -- json (LoadError)
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:15:in `require'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/context.rb:6:in `<top (required)>'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:15:in `require'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:15:in `require'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli.rb:133:in `<module:ShopifyCLI>'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli.rb:42:in `<top (required)>'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:15:in `require'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:15:in `require'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/load_shopify.rb:18:in `<top (required)>'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:52:in `require_relative'
	from /home/REDACTED/.npm-global/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:52:in `<main>'
```

**Comment by lucyxiang** [comment]
@gil-roboute we're working to remove Ruby as a dependency in the CLI, I appreciate the patience for now 🙏

**Comment by briandesp** [comment]
I just installed linux trying to learn it - can anyone tell me how to exactly downgrade the ruby-json package to the one that works propery? I am getting the same error as above.

**Comment by flortsch** [comment]
A few days ago, I got a ruby update on my Arch install. It seems that ruby and many sub-modules (such as the json module) where merged into the main ruby package. Also, ruby got updated to 3.2.4. I am now running shopify-cli 3.60.1 and I no longer have the json issue. Can someone confirm this as well?

**Comment by ultraammar** [comment]
Shopify CLI    3.66.1
OS             linux-amd64
Node version   v22.8.0
Ruby version   3.2.5

Still same issue

**Comment by Akayashuu** [comment]
I had almost the same problems but with `erb`, it seems that the system functions were overwritten by ruby-json/ruby-erb, to fix this I had to downgrade it and find the right version. (in fact i used the last version)

I'm using Arch, ruby 3.2.5, node 18.20.4 and the last version of the Shopify CLI, 

```sh
sudo downgrade ruby-json
```

**Comment by karreiro** [comment]
👋 Thank you, everyone, for reporting! I'm closing the issue as Ruby is no longer required in the latest version of Shopify CLI.
