### ISSUE TITLE
[Bug]: `materialize': Could not find racc-1.7.3, ffi-1.16.3 in locally installed gems (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by thosakwe** [Shopify/cli#3442]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

`npm run dev` should start the app development server. I should be able to work on my app, with changes being hot reloaded/uploaded, with the process running indefinitely in my terminal.

### Actual behavior

The process exits without printing an error message. When I run the terminal as verbose, I see that it seems to be caused by the Ruby dependencies of the Shopify CLI:

```
/usr/local/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:540:in `materialize': Could not find racc-1.7.3, ffi-1.16.3 in locally installed gems (Bundler::GemNotFound)
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:200:in `specs'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:266:in `specs_for'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:18:in `setup'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler.rb:162:in `setup'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/setup.rb:23:in `block in <top (required)>'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/ui/shell.rb:159:in `with_level'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/ui/shell.rb:111:in `silence'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/setup.rb:23:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/local/lib/ruby/site_ruby/3.2.0/rubygems.rb:1368:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
```

I encountered this error with a previous version of the CLI, but the error would be printed without me having to specify `--verbose`. I updated the CLI so that I could publish this issue, but it's the same error.

### Verbose output

```shell
Full log here: https://gist.github.com/thosakwe/d0ef3e22bdfee54064b94d6e5c519a52

(I had to truncate it because it exceeded GitHub's 65536 character limit)


/usr/local/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:540:in `materialize': Could not find racc-1.7.3, ffi-1.16.3 in locally installed gems (Bundler::GemNotFound)
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:200:in `specs'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:266:in `specs_for'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:18:in `setup'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler.rb:162:in `setup'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/setup.rb:23:in `block in <top (required)>'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/ui/shell.rb:159:in `with_level'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/ui/shell.rb:111:in `silence'
	from /usr/local/lib/ruby/site_ruby/3.2.0/bundler/setup.rb:23:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/local/lib/ruby/site_ruby/3.2.0/rubygems.rb:1368:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

ΓÇ║ Press d Γöé toggle development store preview: Γ£ö on
ΓÇ║ Press g Γöé open GraphiQL (Admin API) in your browser
ΓÇ║ Press p Γöé preview in your browser
ΓÇ║ Press q Γöé quit

Shutting down dev because of an error ...

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G2024-02-15T17:31:02.920Z: Killing process 23708: npm run dev
```
```


### Reproduction steps

1. Run `npm run dev` (which, in my case, just calls `shopify app dev`)

### Operating System

Windows 11, 5.4.72-microsoft-standard-WSL2, Ubuntu 20.04.2 LTS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.56.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

v20.8.0

### What language and version are you using in your application?

Ruby 3.2.1

**Comment by thosakwe** [comment]
Turns out I had 2 versions of Ruby:

- One installed via system package manager
- One installed via `rvm`

This led to `gem` and `bundle` pointing to different Ruby runtimes.

So `racc` and `ffi` were installed, just not to the same runtime that was being used for `npm run dev`.
