### ISSUE TITLE
[Feature]: Monorepo support with symlinked dependencies

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [Shopify/cli#3754]
### What area(s) will this request affect?

App, Extension

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Let it be possible to use symlinked dependencies in Checkout Extensions folders, or giev us the path to achieve something of similar effect.

### Motivation

We have a monorepo with Turborepo and Pnpm workspaces.
For teh new Checkout, we are trying to make a Shopify app to develop the Checkout Extensions.
Now, by default, PNPM workspaces work by symlinking the dependencies of our monorepo with the rest of the packages/apps. which means that our internal dependecies don't get installed directly but just referenced/symlinked.
The problem is, when i import our "@utils" package in the Extensions folder, everything seems to work, but the in the browser we get the error: 
```
ExtensionSandbox.latest.it.9d1a82060b7e9052c2ef.worker.js:2 Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://solomon-four-bored-sun.trycloudflare.com/extensions/42544d4a-d3e3-433e-9d1d-32977dc6af42/assets/invoice-form.js' failed to load.
    at it (https://extensions.shopifycdn.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.it.9d1a82060b7e9052c2ef.worker.js:2:261066)
    at MessagePort.h (https://extensions.shopifycdn.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.it.9d1a82060b7e9052c2ef.worker.js:2:237793)
3245.latest.it.8ba25d868d443ca21a08.js:2 ExtensionRenderError: NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://solomon-four-bored-sun.trycloudflare.com/extensions/42544d4a-d3e3-433e-9d1d-32977dc6af42/assets/invoice-form.js' failed to load.
    at app.latest.it.2a231cad34f8ca05418c.js:1:314468
    at async tc.renderAndMountExtension (app.latest.it.2a231cad34f8ca05418c.js:1:315258)
```

Is there any possible path to let us do this? Otherwise we have to duplicate code

**Comment by AndreaPontrandolfo** [comment]
it actually work, we had another error
