### ISSUE TITLE
[Bug]: <YOUR ISSUE TITLE>

### ISSUE THREAD

**Issue by zane-wky** [Shopify/cli#3953]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

I think the value of the metafield I defined should be returned

### Actual behavior

I got an error.
Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://additions-sharing-dry-contributor.trycloudflare.com/extensions/4cd1e515-5b02-4afd-b463-f94bbf4dc2c5/assets/checkout-ui.js' failed to load.
    at F (https://extensions.shopifycdn.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.en.9b5ee1ea3fb85742fd63.worker.js:1:129387)
    at MessagePort.p (https://extensions.shopifycdn.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.en.9b5ee1ea3fb85742fd63.worker.js:1:119473)

### Verbose output

```shell
I created a new application and followed the step-by-step documentation below
https://shopify.dev/docs/apps/build/checkout/display-custom-data?extension=react
Then I got an error.
Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://additions-sharing-dry-contributor.trycloudflare.com/extensions/4cd1e515-5b02-4afd-b463-f94bbf4dc2c5/assets/checkout-ui.js' failed to load.
    at F (https://extensions.shopifycdn.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.en.9b5ee1ea3fb85742fd63.worker.js:1:129387)
    at MessagePort.p (https://extensions.shopifycdn.com/shopifycloud/checkout-web/assets/ExtensionSandbox.latest.en.9b5ee1ea3fb85742fd63.worker.js:1:119473)

I made sure I didn't do any extra steps, then the store I chose was the developer store
```

### Reproduction steps

1.npm init @shopify/app@latest
2.cd .\test\
3. shopify app generate extension
4. In addition to naming, copy the two codes in the document into my code
5. shopify app dev
6. Press p and open a browser window to view the output

### Operating System

Windows10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.60

### Node version (run `node -v` if you're not sure)

16

**Comment by gonzaloriestra** [comment]
Hi! Thanks for creating the issue and sorry for the late response.

We are not able to reproduce it, have you encountered this issue again? There was a [Cloudflare outage](https://www.cloudflarestatus.com/incidents/lh6mzpz5ryn3) on May 30 that may be related.
