### ISSUE TITLE
[Bug]: Error in shopify dev

### ISSUE THREAD

**Issue by mwhr126** [Shopify/cli#3954]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

If you enter shopify theme dev --store https://test.myshopify.com/.

```
│ │ │
Preview the theme
│ - http://127.0.0.1:9292 │

Next Steps
Customize your theme in the theme editor
Share the theme preview
│ (https://test.myshopify.com/?preview_theme_id=0000) 

 Sync theme #〇〇〇〇〇〇 to test.myshopify.com
```

is now complete.

### Actual behavior

Because the following was displayed,

```
shopify theme dev --store https://test.myshopify.com/

✗ An unexpected error occurred.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```

I just entered this one.

```
export SHOPIFY_CLI_STACKTRACE=1   
shopify theme dev --store https://test.myshopify.com/
```

I get the following and shopify theme dev is not working properly.

```
<internal:dir>:411:in `glob': Operation timed out - /Users/test/Desktop/test-content/T/TT/materials/tagDI.rtfd (Errno::ETIMEDOUT)
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/root.rb:29:in `glob'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/root.rb:29:in `glob'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/theme.rb:24:in `theme_files'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/syncer/uploader.rb:63:in `delete_files!'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/syncer/uploader.rb:50:in `upload!'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/syncer.rb:171:in `upload_theme!'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `public_send'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `block in progress'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/project_types/theme/ui/sync_progress_bar.rb:10:in `progress'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/project_types/theme/commands/serve.rb:53:in `block in call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:189:in `sync_theme'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:118:in `start'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb:72:in `start'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/project_types/theme/commands/serve.rb:52:in `call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/command/sub_command.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/command.rb:26:in `call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui.rb:177:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:26:in `log'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:57:in `block (2 levels) in <main>'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:56:in `block in <main>'
        from /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:66:in `<main>'
```

### Verbose output

```shell
test@MacBook-Pro ~ % shopify theme dev --store https://test.myshopify.com --verbose

2024-05-30T16:19:10.991Z: Running command theme dev
2024-05-30T16:19:11.037Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2024-05-30T16:19:11.037Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store test.myshopify.com:
[]

2024-05-30T16:19:11.039Z: Getting session store...
2024-05-30T16:19:11.043Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "test.myshopify.com"
  }
}

2024-05-30T16:19:11.044Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-05-30T16:19:11.044Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.60.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-05-30T16:19:11.389Z: Request to https://accounts.shopify.com/oauth/introspection completed in 316 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"88a2a7ce1a61252d2563a3314c0d10a1"
 - x-request-id: d015a0cc-de68-4a7e-a2f6-8677e656aa19-1717085951
    
2024-05-30T16:19:11.395Z: The identity token is valid: true
2024-05-30T16:19:11.395Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2024-05-30T16:19:11.396Z: The current session is valid but needs refresh. Refreshing...
2024-05-30T16:19:11.397Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQIjr3isgYQrvXisgZSJggBEhDGUGZlYehCeLdQ6W5KUQ3QGhC-pz-E_KhKI7ICJVgRIytIEkCj7m8_dCuAiKi4Put-eQAGoyqFRF9ZkgCWXHBsRi0qzC-GWEhx67-MaSuk_JJsEqR9gPgAeb8xZpX0sRtf0MsM&refresh_token=atkn_CiEIjr3isgYQjteAtAaiARIKEL6nP4T8qEojsgIlWBEjK0gSQJ9xWt2rMWvxwCgCsRdEjvPFdhh5JT3rE4B_yqivO1BXs3cwPrYrAvG-CSKp0FQinIqRJsSAK2X8hoRvDTNQrQk&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.60.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-05-30T16:19:12.035Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQIjr3isgYQrvXisgZSJggBEhDGUGZlYehCeLdQ6W5KUQ3QGhC-pz-E_KhKI7ICJVgRIytIEkCj7m8_dCuAiKi4Put-eQAGoyqFRF9ZkgCWXHBsRi0qzC-GWEhx67-MaSuk_JJsEqR9gPgAeb8xZpX0sRtf0MsM&refresh_token=atkn_CiEIjr3isgYQjteAtAaiARIKEL6nP4T8qEojsgIlWBEjK0gSQJ9xWt2rMWvxwCgCsRdEjvPFdhh5JT3rE4B_yqivO1BXs3cwPrYrAvG-CSKp0FQinIqRJsSAK2X8hoRvDTNQrQk&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 637 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"320a7d18d379353156c7533b3111a50b"
 - x-request-id: ace8f3ee-61f9-4496-99d2-473be5e71df4-1717085951
    
2024-05-30T16:19:12.040Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.60.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-05-30T16:19:12.040Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.60.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-05-30T16:19:12.041Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.60.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-05-30T16:19:12.041Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Ftest.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.60.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-05-30T16:19:12.361Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=**** completed in 314 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"09f704e5f95eff00421da480dd712e29"
 - x-request-id: 59e271c1-0eeb-4d73-ad14-1d99a4f96cb0-1717085952
    
2024-05-30T16:19:12.376Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=**** completed in 327 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"4cda8b7ca709f1d0e6ef16b5c2ed8b23"
 - x-request-id: 70721d40-0d30-468b-9f36-589136e9f107-1717085952
    
2024-05-30T16:19:12.380Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Ftest.myshopify.com%2Fadmin completed in 325 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"0b2e746f3c5fbf609cbf10e8b808cd09"
 - x-request-id: 2956d258-d84f-4482-847a-5614879bf26d-1717085952
    
2024-05-30T16:19:12.388Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=**** completed in 335 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"846e3d2c5d66d36db12dc60637b39620"
 - x-request-id: b9f0b80a-2c9f-4b70-b3a8-217236b9d3cf-1717085952
    
2024-05-30T16:19:12.394Z: Setting session store...
2024-05-30T16:19:12.409Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2024-05-30T16:19:12.410Z: Getting session store...
2024-05-30T16:19:12.411Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2024-05-30T16:19:12.411Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-05-30T16:19:12.411Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.60.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-05-30T16:19:12.691Z: Request to https://accounts.shopify.com/oauth/introspection completed in 277 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"fbdb26999f4579b665efd79afea39167"
 - x-request-id: 6c4baff3-11b4-4cab-9e3c-481e9c59b24e-1717085952
    
2024-05-30T16:19:12.692Z: The identity token is valid: true
2024-05-30T16:19:12.693Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2024-05-30T16:19:12.710Z: 
Running system process:
  · Command: /usr/local/opt/ruby/bin/ruby -v
  · Working directory: /Users/test

2024-05-30T16:19:12.760Z: 
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle -v
  · Working directory: /Users/test

2024-05-30T16:19:13.140Z: Reading the content of file at /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/Gemfile...
2024-05-30T16:19:13.142Z: 
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle install
  · Working directory: /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby

2024-05-30T16:19:14.088Z: 
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle exec /usr/local/opt/ruby/bin/ruby /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify theme token --admin atkn_Cp8DCIDO4rIGEKCG47IGYpADCAESEJ35AYeFs0NprzOhr_RJ8K8aqAFodHRwczovL2FwaS5zaG9waWZ5LmNvbS9hdXRoL3BhcnRuZXJzLmNvbGxhYm9yYXRvci1yZWxhdGlvbnNoaXBzLnJlYWRvbmx5IGh0dHBzOi8vYXBpLnNob3BpZnkuY29tL2F1dGgvc2hvcC5hZG1pbi5ncmFwaHFsIGh0dHBzOi8vYXBpLnNob3BpZnkuY29tL2F1dGgvc2hvcC5hZG1pbi50aGVtZXMgDSinUzIQ1RUExM8uQNaQ9DJ88sHSfDokM2QxNWRmODktZjVkNy00M2IwLWEzMTktYTkzZWM2MjNhMTJiQgdBY2NvdW50ShB87lKVZ-xIsZTyBoMATLZDUlN7InN1YiI6ImZiZGIyNjQ5LWUzMjctNDkwNy04ZjY3LTkwOGQyNGNmZDdlMyIsImlzcyI6Imh0dHBzOi8vYWNjb3VudHMuc2hvcGlmeS5jb20ifWIQV4EplqcwSwu4WYE0jmAEC2oQSBTaWp2CRnmOLsjv9NXkvRJActWq7bknjRcE0uRKij-dBczxJ0e2apevg5WnUdSKqiyBKx7-hChomgVGnfUQww4C-eGCynj98Rtt7xV-LKSxAQ --sfr atkn_CqMCCIDO4rIGEKCG47IGYpQCCAESELYv5B99JUzwgz8yrdh-S0kaPmh0dHBzOi8vYXBpLnNob3BpZnkuY29tL2F1dGgvc2hvcC5zdG9yZWZyb250LXJlbmRlcmVyLmRldnRvb2xzINhSKKdTOiQzZDE1ZGY4OS1mNWQ3LTQzYjAtYTMxOS1hOTNlYzYyM2ExMmJCB0FjY291bnRKEHzuUpVn7EixlPIGgwBMtkNSU3sic3ViIjoiZmJkYjI2NDktZTMyNy00OTA3LThmNjctOTA4ZDI0Y2ZkN2UzIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5zaG9waWZ5LmNvbSJ9YhBXgSmWpzBLC7hZgTSOYAQLahBIFNpanYJGeY4uyO_01eS9EkC5If-aYbEe0rEwj2ZhwJS4zCQSDJeYPU7zU4g6p18H3FZ3NH2wepWa43ySMhApFOl-y4-vi1Cgyb8Ou2FkY6AD
  · Working directory: /Users/test

2024-05-30T16:19:15.548Z: Getting development theme...
2024-05-30T16:19:15.967Z: Request to https://test.myshopify.com/admin/api/unstable/themes/142028308706.json?fields=id%2Cname%2Crole%2Cprocessing completed in 414 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: 35fc3ba8-1c81-45a2-b4cf-142d56bb942e-1717085955
    
╭─ success ──────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                    │
│  Preview your theme                                                                                                │
│    • http://127.0.0.1:9292                                                                                         │
│                                                                                                                    │
│  Next steps                                                                                                        │
│    • Customize your theme at the theme editor                                                                      │
│    • Share your theme preview (https://test.myshopify.com/?preview_theme_id=142028308706)                     │
│                                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

2024-05-30T16:19:16.056Z: 
Running system process:
  · Command: /usr/local/opt/ruby/bin/ruby -v
  · Working directory: /Users/test

2024-05-30T16:19:16.077Z: 
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle -v
  · Working directory: /Users/test

2024-05-30T16:19:16.508Z: Reading the content of file at /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/Gemfile...
2024-05-30T16:19:16.512Z: 
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle install
  · Working directory: /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby

2024-05-30T16:19:17.464Z: 
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle exec /usr/local/opt/ruby/bin/ruby /usr/local/Cellar/shopify-cli/3.60.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify theme serve /Users/test --live-reload hot-reload --theme 142028308706 --overwrite-json undefined
  · Working directory: /Users/test

DEBUG GET https://test.myshopify.com/admin/api/unstable/themes.json with request_id: bba3e18d-76e2-4991-9095-fc67c9c29cd0-1717085959
* Syncing theme #142028308706 on test.myshopify.com
DEBUG GET https://test.myshopify.com/admin/api/unstable/themes/142028308706/assets.json with request_id: 0610feab-7d6e-4844-8ad3-f90ad737e44e-1717085959
                                                                                                                                                                             0%  
✗ An unexpected error occurred.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```

### Reproduction steps

1.shopify theme dev --store https://test.myshopify.com/
2.SHOPIFY_CLI_STACKTRACE=1
3.shopify theme dev --store https://test.myshopify.com/

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.60.1

### Node version (run `node -v` if you're not sure)

v22.2.0

**Comment by muchisx** [comment]
Any updates here? I'm having the exact same issue as above
