### ISSUE TITLE
[Bug] Shopify theme dev on arm64 `bundle install`

### ISSUE THREAD

**Issue by Densz** [Shopify/cli#4290]
Issue when trying to develop theme on my macbook m2.
It is working properly on my Macbook Intel, so maybe the issue comes from the processor chip.

```
shopify --version
@shopify/cli/3.59.0 darwin-arm64 node-v20.15.0
```

```

$ shopify theme dev --store=...


── external error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `bundle install`

Command failed with exit code 1: bundle install
zsh:1: command not found: chruby
--- ERROR REPORT TEMPLATE -------------------------------------------------------

LoadError: cannot load such file -- zlib
  <internal:/Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          <internal:/Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/fetcher.rb:7:in `<top (required)>'
          <internal:/Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          <internal:/Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/cli/install.rb:50:in `run'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/cli.rb:244:in `block in install'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/settings.rb:158:in `temporary'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/cli.rb:243:in `install'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/bin/bundle:25:in `load'
          /Users/dzheng/.rvm/rubies/ruby-3.3.1/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.5.9
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [arm64-darwin-23]
  Full Path   /Users/dzheng/.rvm/rubies/ruby-3.3.1/bin/ruby
  Config Dir  /Users/dzheng/.rvm/rubies/ruby-3.3.1/etc
RubyGems      3.5.9
  Gem Home    /Users/dzheng/.rvm/gems/ruby-3.3.1
  Gem Path    /Users/dzheng/.rvm/gems/ruby-3.3.1:/Users/dzheng/.rvm/rubies/ruby-3.3.1/lib/ruby/gems/3.3.0
  User Home   /Users/dzheng
  User Path   /Users/dzheng/.gem/ruby/3.3.0
  Bin Dir     /Users/dzheng/.rvm/gems/ruby-3.3.1/bin
Tools
  Git         2.45.2
  RVM         1.29.12 (latest)
  rbenv       rbenv 1.2.0
  chruby
```

## Bundler Build Metadata

```
Built At          2024-07-30
Git SHA           unknown
Released Version  false


## Bundler settings


path
  Set via BUNDLE_PATH: "/Users/dzheng/Library/Caches/shopify-gems-nodejs"
without
  Set via BUNDLE_WITHOUT: [:development, :test]


## Gemfile

### Gemfile

# NOTE: These are development-only dependencies
source "https://rubygems.org"

gem "bugsnag", "~> 6.22"
gem "listen", "~> 3.7.0"

# None of these can actually be used in a development copy of dev
# They are all for CI and tests
# `dev` uses no gems
group :development, :test do
  gem "pry-byebug"
  gem "byebug"
  gem "rubocop-shopify", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-rake", require: false
  gem "iniparse", "~> 1.5"
  gem "colorize", "~> 0.8.1"
  gem "bundler", ">= 2.3.11"
  gem "rake", "~> 12.3", ">= 12.3.3"
  gem "minitest", "~> 5.0"
end

group :test do
  gem "mocha", require: false
  gem "minitest-reporters", require: false
  gem "minitest-fail-fast", require: false
  gem "fakefs", ">= 1.0", require: false
  gem "webmock", require: false
  gem "timecop", require: false
  gem "rack", require: false
  gem "cucumber", "~> 7.0", require: false
end


### Gemfile.lock

<No /Users/dzheng/.nvm/versions/node/v18.17.1/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/Gemfile.lock found>

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=cannot+load+such+file+--+zlib&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in
there.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

_Originally posted by @Densz in https://github.com/Shopify/cli/issues/3662#issuecomment-2258209755_

**Comment by mgmanzella** [comment]
👋 thanks for reporting, we know ruby is pretty difficult to debug within the CLI when it doesnt work and are actively working to remove this dependency 

the CLI is compatible with the macbook m2, from the logs it looks like theres an issue with your ruby install. can you try uninstalling the CLI (ideally deleting all the files associated with shopify cli) and try to do a clean install of the latest version??

**Comment by karreiro** [comment]
Thanks for the heads up! I'm glad it worked, @Densz!

If that issue ever comes up again, try updating this line in your `.zshrc` file:

```bash
# from this
export SHOPIFY_RUBY_BINDIR=/usr/local/opt/ruby/bin/ruby

# to this
export SHOPIFY_RUBY_BINDIR=/usr/local/opt/ruby/bin
```

That should help with any future issues in selecting the desired Ruby :)

Thanks again for reporting!
