### ISSUE TITLE
[Bug]:  Error coming from `npm exec -- graphql-code-generator --config package.json`

### ISSUE THREAD

**Issue by Yamashou** [Shopify/cli#4653]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Function

### Expected behavior

I expect that when I run npm run deploy, the functions will be properly deployed as is. The build and type generation for each function are working correctly.

### Actual behavior

An error stating “Error coming from npm exec -- graphql-code-generator --config package.json” is occurring in all functions. Judging from the logs, I think the buildGraphqlTypes inside the CLI is causing the issue.

### Verbose output

Command failed with exit code 1: npm exec -- graphql-code-generator --config package.json
npm verbose cli /Users/xxx/.nvm/versions/node/v22.5.1/bin/node /Users/xx/.nvm/versions/node/v22.5.1/bin/npm
npm info using npm@10.8.2
npm info using node@v22.5.1
npm info config found workspace root at /Users/xx/go/src/github.com/vipweb
npm verbose title npm exec graphql-code-generator --config package.json
npm verbose argv "exec" "--" "graphql-code-generator" "--config" "package.json"
npm verbose logfile logs-max:10 dir:/Users/xx/.npm/_logs/2024-10-16T04_58_18_981Z-
npm verbose logfile /Users/xx/.npm/_logs/2024-10-16T04_58_18_981Z-debug-0.log
npm verbose stack Error:
npm verbose stack Run a command from a local or remote npm package
npm verbose stack
npm verbose stack Usage:
npm verbose stack npm exec -- <pkg>[@<version>] [args...]
npm verbose stack npm exec --package=<pkg>[@<version>] -- <cmd> [args...]
npm verbose stack npm exec -c '<cmd> [args...]'
npm verbose stack npm exec --package=foo -c '<cmd> [args...]'
npm verbose stack
npm verbose stack Options:
npm verbose stack [--package <package-spec> [--package <package-spec> ...]] [-c|--call <call>]
npm verbose stack [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm verbose stack [-ws|--workspaces] [--include-workspace-root]
npm verbose stack
npm verbose stack alias: x
npm verbose stack
npm verbose stack Run "npm help exec" for more info
npm verbose stack     at Exec.usageError (/Users/xx/.nvm/versions/node/v22.5.1/lib/node_modules/npm/lib/base-cmd.js:109:26)
npm verbose stack     at Exec.callExec (/Users/xx/.nvm/versions/node/v22.5.1/lib/node_modules/npm/lib/commands/exec.js:76:18)
npm verbose stack     at Exec.execWorkspaces
(/Users/xx/.nvm/versions/node/v22.5.1/lib/node_modules/npm/lib/commands/exec.js:37:18)
npm verbose stack     at async Npm.exec (/Users/xx/.nvm/versions/node/v22.5.1/lib/node_modules/npm/lib/npm.js:207:9)
npm verbose stack     at async module.exports
(/Users/xx/.nvm/versions/node/v22.5.1/lib/node_modules/npm/lib/cli/entry.js:74:5)
npm error code EUSAGE
npm error
npm error Run a command from a local or remote npm package
npm error
npm error Usage:
npm error npm exec -- <pkg>[@<version>] [args...]
npm error npm exec --package=<pkg>[@<version>] -- <cmd> [args...]
npm error npm exec -c '<cmd> [args...]'
npm error npm exec --package=foo -c '<cmd> [args...]'
npm error
npm error Options:
npm error [--package <package-spec> [--package <package-spec> ...]] [-c|--call <call>]
npm error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm error [-ws|--workspaces] [--include-workspace-root]
npm error
npm error alias: x
npm error
npm error Run "npm help exec" for more info
npm verbose cwd /Users/xx/go/src/github.com/vipweb/extensions/function-validation-purchase-limit
npm verbose os Darwin 23.6.0
npm verbose node v22.5.1
npm verbose npm  v10.8.2
npm verbose exit 1
npm verbose code 1

### Reproduction steps

1. npm run shopify generate extension (select function)
2. npm run deploy

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.68.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v22.5.1

**Comment by Yamashou** [comment]
I'm having trouble releasing it.
