### ISSUE TITLE
[Bug]: Error: Upload failed, could not reach the server

### ISSUE THREAD

**Issue by royvn** [Shopify/cli#4683]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

After running the `shopify theme dev --store=your-store-name` command, it uploads your development theme, allowing you to start working on it.

### Actual behavior

CLI stops and the Error appears after the success and theme preview links.

![Image](https://github.com/user-attachments/assets/159f21e1-dfc9-490b-9071-fe8a9083b91c)

### Verbose output

2024-10-18T13:48:30.071Z: Running command theme dev
2024-10-18T13:48:30.085Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2024-10-18T13:48:30.085Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store xxxxxxxxxxx.myshopify.com:
[]

2024-10-18T13:48:30.085Z: Getting session store...
2024-10-18T13:48:30.087Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "xxxxxxxxxxx.myshopify.com"
  }
}

2024-10-18T13:48:30.087Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-10-18T13:48:30.087Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:30.391Z: Request to https://accounts.shopify.com/oauth/introspection completed in 303 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"a27ae57a2d73d2dcb6f2fee835455c62"
 - server-timing: processing;dur=28, socket_queue;dur=1.976, edge;dur=0.021, util;dur=0.15, cfRequestDuration;dur=188.999891
 - x-request-id: 24d5dbf1-1285-48b7-b296-fb3c4eda4a71-1729259310
    
2024-10-18T13:48:30.398Z: The identity token is valid: true
2024-10-18T13:48:30.399Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2024-10-18T13:48:30.399Z: The current session is valid but needs refresh. Refreshing...
2024-10-18T13:48:30.401Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI2MnJuAYQ-IHKuAZSJggBEhDd5ucRQSxA1YM18PSctY3pGhBB9s-dvhVNSJ_rC3T7W_9BEkAmcHYNCZPrKkopsZdivw3VpPKK1T1igCxnLs5rKmbDH8jRmP_cAHbtD6gH0lndY1wWVDJdFv7syujPK_y_ijAL&refresh_token=atkn_CiEI2MnJuAYQ2OPnuQaiARIKEEH2z52-FU1In-sLdPtb_0ESQBITTqQyoHiUb1jBKb21mdqACojzXPs3B_kP5CzqGMBS51qclIvoKwgzRUg8YBx4iVcegPWjVG5C3ZjujM0rDAo&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:30.687Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI2MnJuAYQ-IHKuAZSJggBEhDd5ucRQSxA1YM18PSctY3pGhBB9s-dvhVNSJ_rC3T7W_9BEkAmcHYNCZPrKkopsZdivw3VpPKK1T1igCxnLs5rKmbDH8jRmP_cAHbtD6gH0lndY1wWVDJdFv7syujPK_y_ijAL&refresh_token=atkn_CiEI2MnJuAYQ2OPnuQaiARIKEEH2z52-FU1In-sLdPtb_0ESQBITTqQyoHiUb1jBKb21mdqACojzXPs3B_kP5CzqGMBS51qclIvoKwgzRUg8YBx4iVcegPWjVG5C3ZjujM0rDAo&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 286 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"1fd77b44c287a4cde297527e75bf47fe"
 - server-timing: processing;dur=78, socket_queue;dur=1.872, edge;dur=1.016, util;dur=0.1, cfRequestDuration;dur=202.999830
 - x-request-id: 4c6d6535-3b02-4ffb-99d8-9605aaeb0355-1729259310
    
2024-10-18T13:48:30.692Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:30.692Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:30.693Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:30.693Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Fxxxxxxxxxxx.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:30.958Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=**** completed in 266 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"831b9c3a71e32e677fe390e7a808c772"
 - server-timing: processing;dur=48, socket_queue;dur=2.174, edge;dur=1.021, util;dur=0.05, cfRequestDuration;dur=176.999807
 - x-request-id: aaaaf7fe-fabc-472d-a764-21590e280960-1729259310
    
2024-10-18T13:48:30.964Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=**** completed in 271 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"de17140aae130f610b78145c06d492af"
 - server-timing: processing;dur=46, socket_queue;dur=1.358, edge;dur=1.024, util;dur=0.35, cfRequestDuration;dur=180.999756
 - x-request-id: ec8e6863-53b9-423b-a8ed-97c427227725-1729259310
    
2024-10-18T13:48:30.967Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Fxxxxxxxxxxx.myshopify.com%2Fadmin completed in 274 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"a000165675020307c2e62430af9940f2"
 - server-timing: processing;dur=49, socket_queue;dur=1.616, edge;dur=1.02, util;dur=0.05, cfRequestDuration;dur=180.999994
 - x-request-id: f6889ff9-b27d-45e4-a8b2-84933a45cde5-1729259310
    
2024-10-18T13:48:30.971Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=**** completed in 279 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"fd1ad66d40e16d99289763cd0b122e54"
 - server-timing: processing;dur=46, socket_queue;dur=1.653, edge;dur=2.023, util;dur=0.15, cfRequestDuration;dur=184.000015
 - x-request-id: b2eb79fb-1040-41ff-b181-0124a4213434-1729259310
    
2024-10-18T13:48:30.976Z: Setting session store...
2024-10-18T13:48:30.983Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2024-10-18T13:48:30.983Z: Getting session store...
2024-10-18T13:48:30.984Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2024-10-18T13:48:30.984Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-10-18T13:48:30.984Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:31.239Z: Request to https://accounts.shopify.com/oauth/introspection completed in 254 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"ac58cfcede5311bcfbb92664964483f9"
 - server-timing: processing;dur=24, socket_queue;dur=1.355, edge;dur=1.03, util;dur=0.15, cfRequestDuration;dur=177.999735
 - x-request-id: d3a06ba7-bf42-4713-a465-6e9e7403dcd1-1729259311
    
2024-10-18T13:48:31.241Z: The identity token is valid: true
2024-10-18T13:48:31.241Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2024-10-18T13:48:31.242Z: Getting development theme...
2024-10-18T13:48:31.649Z: Request to https://xxxxxxxxxxx.myshopify.com/admin/api/unstable/themes/141749616877.json?fields=id%2Cname%2Crole%2Cprocessing completed in 403 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - server-timing: processing;dur=179, cfRequestDuration;dur=332.000256
 - x-request-id: 808cb089-c3f3-498a-b3a8-c4be75e3dd5b-1729259311
    
╭─ info ────────────────────────────────────────────────────────────────────────────────╮
│                                                                                       │
│  You're using the new version of `shopify theme dev`.                                 │
│                                                                                       │
│  Run `shopify theme dev --legacy` to switch back to the previous version.             │
│                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────╯

2024-10-18T13:48:31.713Z: Port 9292 is free
2024-10-18T13:48:31.722Z: Reading the content of file at .shopifyignore...
2024-10-18T13:48:31.722Z: Reading the content of file at assets/FFDINProforIIC-Black.woff2...
2024-10-18T13:48:31.722Z: Reading the content of file at assets/FFDINProforIIC-Bold.woff2...
2024-10-18T13:48:31.722Z: Reading the content of file at assets/FFDINProforIIC-Light.woff2...
2024-10-18T13:48:31.722Z: Reading the content of file at assets/FFDINProforIIC-Medium.woff2...
2024-10-18T13:48:31.722Z: Reading the content of file at assets/FFDINProforIIC.woff2...

2024-10-18T13:48:31.807Z: Request to https://xxxxxxxxxxx.myshopify.com/ completed in 110 ms
With response headers:
 - content-type: text/html; charset=utf-8
 - server-timing: processing;dur=20, db;dur=3, db_async;dur=7.135, asn;desc="50266", edge;desc="AMS", country;desc="NL", theme;desc="143001911533", pageType;desc="index", servedBy;desc="2qxc", requestID;desc="b9b1f2e7-c63f-43ff-856e-e80d465ebf4f-1729259311", cfRequestDuration;dur=66.999912
 - x-request-id: b9b1f2e7-c63f-43ff-856e-e80d465ebf4f-1729259311
    
2024-10-18T13:48:31.807Z: Getting storefront password for shop xxxxxxxxxxx.myshopify.com...
Warning: The pattern 'templates/*.json' does not include subdirectories. To maintain backwards compatibility, we have modified your pattern to templates/**/*.json to explicitly include subdirectories.
2024-10-18T13:48:31.979Z: Request to https://xxxxxxxxxxx.myshopify.com/password completed in 172 ms
With response headers:
 - content-type: text/html; charset=utf-8
 - server-timing: processing;dur=16;desc="gc:1", db;dur=4, db_async;dur=8.852, asn;desc="50266", edge;desc="AMS", country;desc="NL", pageType;desc="password", servedBy;desc="6hmn", requestID;desc="021395e3-387f-4f6a-8ea8-47b4de5bb29a-1729259311", cfRequestDuration;dur=151.999950
 - x-request-id: 021395e3-387f-4f6a-8ea8-47b4de5bb29a-1729259311
    
2024-10-18T13:48:31.980Z: Setting storefront password for shop xxxxxxxxxxx.myshopify.com...
2024-10-18T13:48:31.987Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2024-10-18T13:48:31.987Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store xxxxxxxxxxx.myshopify.com:
[]

2024-10-18T13:48:31.987Z: Getting session store...
2024-10-18T13:48:31.987Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "xxxxxxxxxxx.myshopify.com"
  }
}

2024-10-18T13:48:31.988Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-10-18T13:48:31.988Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:32.237Z: Request to https://accounts.shopify.com/oauth/introspection completed in 249 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"ac58cfcede5311bcfbb92664964483f9"
 - server-timing: processing;dur=22, socket_queue;dur=1.578, edge;dur=1.015, util;dur=0.0, cfRequestDuration;dur=173.999786
 - x-request-id: 24d33855-df2d-444b-9d2d-aadb3b0ccc9a-1729259312
    
2024-10-18T13:48:32.238Z: The identity token is valid: true
2024-10-18T13:48:32.238Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2024-10-18T13:48:32.239Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2024-10-18T13:48:32.239Z: Getting session store...
2024-10-18T13:48:32.240Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2024-10-18T13:48:32.240Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-10-18T13:48:32.240Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.68.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-10-18T13:48:32.460Z: Request to https://accounts.shopify.com/oauth/introspection completed in 220 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"ac58cfcede5311bcfbb92664964483f9"
 - server-timing: processing;dur=28, socket_queue;dur=1.389, edge;dur=1.023, util;dur=0.15, cfRequestDuration;dur=151.000023
 - x-request-id: f7f234aa-8992-4ef4-8bc5-88f8559bfca7-1729259312
    
2024-10-18T13:48:32.462Z: The identity token is valid: true
2024-10-18T13:48:32.462Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2024-10-18T13:48:32.684Z: Request to https://xxxxxxxxxxx.myshopify.com/?preview_theme_id=141749616877&_fd=0&pb=0 completed in 221 ms
With response headers:
 - content-type: text/html; charset=utf-8
 - server-timing: processing;dur=52, db;dur=4, db_async;dur=5.902, asn;desc="50266", edge;desc="AMS", country;desc="NL", theme;desc="141749616877", pageType;desc="index", servedBy;desc="6n4w", requestID;desc="49612161-2417-42eb-a1ad-abe83cd88ed9-1729259312", cfRequestDuration;dur=194.000006
 - x-request-id: 49612161-2417-42eb-a1ad-abe83cd88ed9-1729259312
    
2024-10-18T13:48:32.908Z: Request to https://xxxxxxxxxxx.myshopify.com/password completed in 223 ms
With response headers:
 - content-type: text/html; charset=utf-8
 - server-timing: processing;dur=11, db;dur=3, db_async;dur=11.743, asn;desc="50266", edge;desc="AMS", country;desc="NL", pageType;desc="password", servedBy;desc="p82n", requestID;desc="9b93dffb-2a1e-4981-8582-9b695ddcc820-1729259312", cfRequestDuration;dur=149.999857
 - x-request-id: 9b93dffb-2a1e-4981-8582-9b695ddcc820-1729259312
    
2024-10-18T13:48:33.193Z: Request to https://xxxxxxxxxxx.myshopify.com/admin/api/unstable/themes/141749616877/assets.json?fields=key%2Cchecksum completed in 284 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - server-timing: processing;dur=92, cfRequestDuration;dur=233.999968
 - x-request-id: c8216470-ad46-49df-abd7-b45d12ccff81-1729259312
    
Warning: The pattern 'templates/*.json' does not include subdirectories. To maintain backwards compatibility, we have modified your pattern to templates/**/*.json to explicitly include subdirectories.
2024-10-18T13:48:33.325Z: Ignoring theme file config/settings_data.json via .shopifyignore...
2024-10-18T13:48:33.329Z: Ignoring theme file sections/footer-group.json via .shopifyignore...
2024-10-18T13:48:33.330Z: Ignoring theme file sections/header-group.json via .shopifyignore...
2024-10-18T13:48:33.341Z: Ignoring theme file snippets/hmac-sha256-salt-key.liquid via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/404.json via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/cart.json via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/article.json via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/collection.json via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/blog.json via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/list-collections.json via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/page.brands.json via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/page.contact.json via .shopifyignore...
2024-10-18T13:48:33.360Z: Ignoring theme file templates/page.customer-service.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/page.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/page.styles.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/password.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/product.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/index.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/search.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/metaobject/store.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/account.club.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/account.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/account.logout.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/account.orders.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/account.password.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/account.retour.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/activate_account.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/addresses.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/order.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/register.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/reset_password.json via .shopifyignore...
2024-10-18T13:48:33.361Z: Ignoring theme file templates/customers/login.json via .shopifyignore...
2024-10-18T13:48:33.362Z: Files to be uploaded:
-assets/back-to-top.js
-assets/index-DimvNaNS.js
-assets/main-utilities.css
-locales/en-dev.default.json
-snippets/format-input.liquid
-snippets/format-textarea.liquid
2024-10-18T13:48:33.362Z: Uploading the following files:
-snippets/format-input.liquid
-snippets/format-textarea.liquid
-locales/en-dev.default.json
-assets/back-to-top.js
-assets/index-DimvNaNS.js
-assets/main-utilities.css
╭─ success ─────────────────────────────────────────────────────────────────────────────╮
│                                                                                       │
│  Preview your theme                                                                   │
│    • http://127.0.0.1:9292                                                            │
│                                                                                       │
│  Next steps                                                                           │
│    • Customize your theme at the theme editor                                         │
│    • Share your theme preview                                                         │
│      (https://xxxxxxxxxxx.myshopify.com/?preview_theme_id=141749616877)         │
│                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────╯

2024-10-18T13:48:33.388Z: 
Running system process:
  · Command: npm prefix
  · Working directory: /Users/royvn/Projects/shopify-xxxxxxxxxxx/dist

2024-10-18T13:48:33.487Z: Obtaining the dependency manager in directory .....
2024-10-18T13:48:33.566Z: 
Running system process:
  · Command: ruby -v
  · Working directory: /Users/royvn/Projects/shopify-xxxxxxxxxxx/dist

2024-10-18T13:48:33.766Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 186 ms
With response headers:
 - x-request-id: 557434ec-3179-46a7-b164-7594ac8e9486
    
2024-10-18T13:48:33.766Z: Analytics event sent: {
  "command": "theme dev",
  "time_start": 1729259310074,
  "time_end": 1729259313384,
  "total_time": 3310,
  "success": true,
  "cli_version": "3.68.1",
  "ruby_version": "2.6.10",
  "node_version": "20.18.0",
  "is_employee": false,
  "uname": "darwin arm64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/cli\"]",
  "env_shell": "zsh",
  "env_device_id": "af656900cae58487dea1d19479244abfb1c7c074",
  "env_cloud": "localhost",
  "env_package_manager": "pnpm",
  "env_is_global": true,
  "env_auth_method": "device_auth",
  "cmd_app_warning_api_key_deprecation_displayed": false,
  "cmd_all_timing_network_ms": 3007,
  "cmd_all_timing_prompts_ms": 0,
  "cmd_all_launcher": "unknown",
  "cmd_all_topic": "theme",
  "cmd_all_plugin": "@shopify/theme",
  "cmd_all_force": false,
  "cmd_all_verbose": true,
  "cmd_all_path_override": true,
  "cmd_all_path_override_hash": "6f670b85bb906dc28ff596586e566cbe2883e662",
  "cmd_all_timing_active_ms": 302,
  "cmd_all_exit": "ok",
  "user_id": "310afc4a-0260-4cb2-aa5e-301bd44071c3",
  "args": "--verbose",
  "env_plugin_installed_all": "[\"@shopify/cli\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2024-10-18T13:48:33.766Z: Completed command theme dev
2024-10-18T13:48:34.275Z: Request to https://xxxxxxxxxxx.myshopify.com/admin/api/unstable/themes/141749616877/assets/bulk.json completed in 912 ms
With response headers:
 - content-type: application/json
 - server-timing: processing;dur=223, cfRequestDuration;dur=881.000042
 - x-request-id: dd89c1fa-a152-446f-8623-ac8c4cbdf855-1729259313
    
Error: Upload failed, could not reach the server
    at bulkUploadThemeAssets (file:///Users/royvn/Library/pnpm/global/5/.pnpm/@shopify+cli@3.68.1/node_modules/@shopify/cli/dist/index.js:145204:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleBulkUpload (file:///Users/royvn/Library/pnpm/global/5/.pnpm/@shopify+cli@3.68.1/node_modules/@shopify/cli/dist/index.js:148757:17)
    at async uploadBatch (file:///Users/royvn/Library/pnpm/global/5/.pnpm/@shopify+cli@3.68.1/node_modules/@shopify/cli/dist/index.js:148747:9)
    at async Promise.all (index 0)
    at async Promise.all (index 1)

### Reproduction steps

1. Run `shopify theme dev`

### Operating System

macOS Sonoma (14.5)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.68.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

20.18.0

**Comment by royvn** [comment]
I tried the new CLI version 3.69.0. The error looks different now.
![Image](https://github.com/user-attachments/assets/5e9dbe30-8110-41a2-9877-2155e0565dac)

**Comment by supa-freak** [comment]
I have the same issue after updating to newest shopify cli version 3.69.2
Always getting Upload failed, could not reach the server

**Comment by supa-freak** [comment]
After debugging the bulkUploadThemeAssets() function, it seemed that actually the 207 is thrown wrongly in some cases, most distinctively it seems that certain upload reponses are status 207 even though they contain a perfectly fine response single object (one object in array, not what you would expect from a 207).
I dont know the internals well enough why the 207 is thrown here and why it would constitute a "cannot reach server" if there is a 207 which says "everything ok", but just commenting out that error 
```
// if (response.status !== 207)
  //   throw new AbortError("Upload failed, could not reach the server");
```
solves the issue and themes get updated fine.
So I would definitely file that as a bug (according to my limited competence here).

Would be good to hear a comment from the shopify theme, since I maybe that error is needed in other cases.

**Comment by royvn** [comment]
My current workaround is to use a different shop to work on with `shopify theme dev`. Then, I use the `shopify theme push` command to push the changes to the shop that’s not working.

**Comment by briandesp** [comment]
I am getting the exact same issues, i just upgraded the CLI.. so fustrating.

**Comment by royvn** [comment]
Looks like this is now fixed in version `3.70.0`. Connecting to the store works again 🎉.

**Comment by ignacio-schiavulli-dev** [comment]
The error has returned, it already happens to me in 2 stores
![Image](https://github.com/user-attachments/assets/20805f5a-862c-4330-af32-78c45c098c13)
