### ISSUE TITLE
[Bug]: Shopify checkout extension ui dev command on watch crashing after saving file

### ISSUE THREAD

**Issue by LordDashMe** [Shopify/cli#4727]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

The Shopify Checkout Extension dev command should work upon saving any checkout extension ui files.

### Actual behavior

The `shopify app dev` command is crashing when you save any checkout extension ui files.

### Verbose output

```
Error: App configuration is not valid
Validation errors in extensions/app-checkout-ext/shopify.extension.toml:

• [type]: Required

    at abort2 (file:///var/shopify-app/node_modules/@shopify/cli/dist/index.js:167152:63)
    at parseConfigurationObjectAgainstSpecification (file:///var/shopify-app/node_modules/@shopify/cli/dist/index.js:163460:14)
    at reloadExtensionConfig (file:///var/shopify-app/node_modules/@shopify/cli/dist/index.js:167167:25)
```

### Reproduction steps

1. The issue was related to this change about the clean up: https://github.com/Shopify/cli/commit/e801ce0565e2cb5b6adf69d45dff798fb56d36cb#diff-7b6cde814de4c516a4206ab570d073c39611b9d8af33f548944010b07b95d4fbR110

2. Even though the `type` is provided in the TOML file, it's getting remove because of that filter `configWithoutFirstClassFields()`

### Operating System

macOS Sonoma 14.6.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.69.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.20.0

**Comment by LordDashMe** [comment]
> Looking into this now, there'll be a patch with a fix soon 🙏

Hey @isaacroldan, all good! and thanks for the quick response. Please let me know if you need more info about the issue.
