### ISSUE TITLE
[Bug] Deploy with Docker throws error "InvalidShopError: Received invalid shop argument"

### ISSUE THREAD

**Issue by Kimblag** [Shopify/cli#487]
Hi, I'm facing an issue when we try to deploy with Docker. 

The current behavior is that we're getting this error "InvalidShopError: Received invalid shop argument" and if we try to load the app it shows a 502 bad Gateway Error. This is weird because locally it works with npm run dev.  

This is the message that we got.

```
serve
cross-env NODE_ENV=production node index.js

/app/node_modules/@shopify/shopify-api/dist/error.js:13
        var _this = _super.apply(this, tslib_1.spreadArray([], tslib_1.read(args), false)) || this;
                           ^

InvalidShopError: Received invalid shop argument
    at InvalidShopError.ShopifyError [as constructor] (/app/node_modules/@shopify/shopify-api/dist/error.js:13:28)
    at new InvalidShopError (/app/node_modules/@shopify/shopify-api/dist/error.js:31:42)
    at sanitizeShop (/app/node_modules/@shopify/shopify-api/dist/utils/shop-validator.js:25:15)
    at SQLiteSessionStorage.<anonymous> (/app/node_modules/@shopify/shopify-api/dist/auth/session/storage/sqlite.js:103:71)
    at step (/app/node_modules/tslib/tslib.js:144:27)
    at Object.next (/app/node_modules/tslib/tslib.js:125:57)
    at /app/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:114:16)
    at SQLiteSessionStorage.findSessionsByShop (/app/node_modules/@shopify/shopify-api/dist/auth/session/storage/sqlite.js:98:24)

Node.js v18.9.0

serve
cross-env NODE_ENV=production node index.js
```

![image](https://user-images.githubusercontent.com/94016613/190730142-aaf6c3b5-4a01-4456-a7e2-473220bb66ec.png)
![image](https://user-images.githubusercontent.com/94016613/190730698-4907b73d-ec17-4753-817f-0e1b6d8d454b.png)

We're using Shopify CLI 3.11.0 and Node.js v18.9.0.

**Comment by Kimblag** [comment]
Hi! We moved to Heroku, we were following this tutorial [Deploy your web app Shopify](https://shopify.dev/apps/deployment/web) step by step and the error is the same.
This error only appears in production, not in dev. We don't know how or were to add the `--verbose` to the command.

```
2022-09-22T20:58:38.879192+00:00 app[web.1]: /app/node_modules/@shopify/shopify-api/dist/error.js:13
2022-09-22T20:58:38.879227+00:00 app[web.1]: var _this = _super.apply(this, tslib_1.__spreadArray([], tslib_1.__read(args), false)) || this;
2022-09-22T20:58:38.879229+00:00 app[web.1]: ^
2022-09-22T20:58:38.879229+00:00 app[web.1]:
2022-09-22T20:58:38.879230+00:00 app[web.1]: InvalidShopError: Received invalid shop argument
2022-09-22T20:58:38.879237+00:00 app[web.1]: at InvalidShopError.ShopifyError [as constructor] (/app/node_modules/@shopify/shopify-api/dist/error.js:13:28)
2022-09-22T20:58:38.879239+00:00 app[web.1]: at new InvalidShopError (/app/node_modules/@shopify/shopify-api/dist/error.js:31:42)
2022-09-22T20:58:38.879239+00:00 app[web.1]: at sanitizeShop (/app/node_modules/@shopify/shopify-api/dist/utils/shop-validator.js:25:15)        
2022-09-22T20:58:38.879239+00:00 app[web.1]: at SQLiteSessionStorage.<anonymous> (/app/node_modules/@shopify/shopify-api/dist/auth/session/storage/sqlite.js:103:71)
2022-09-22T20:58:38.879240+00:00 app[web.1]: at step (/app/node_modules/tslib/tslib.js:144:27)
2022-09-22T20:58:38.879240+00:00 app[web.1]: at Object.next (/app/node_modules/tslib/tslib.js:125:57)
2022-09-22T20:58:38.879241+00:00 app[web.1]: at /app/node_modules/tslib/tslib.js:118:75
2022-09-22T20:58:38.879241+00:00 app[web.1]: at new Promise (<anonymous>)
2022-09-22T20:58:38.879242+00:00 app[web.1]: at Object.__awaiter (/app/node_modules/tslib/tslib.js:114:16)
2022-09-22T20:58:38.879243+00:00 app[web.1]: at SQLiteSessionStorage.findSessionsByShop (/app/node_modules/@shopify/shopify-api/dist/auth/session/storage/sqlite.js:98:24)
2022-09-22T20:58:38.879250+00:00 app[web.1]:
2022-09-22T20:58:38.879251+00:00 app[web.1]: Node.js v18.9.0
```

**Comment by ELBEQQAL94** [comment]
The same issue for me, Can you check your database?

**Comment by isaacroldan** [comment]
Hi @Kimblag !
I wasn't able to reproduce your issue but it looks like an error reading the info stored in the default database (in your app folder you'll find a `database.sqlite` file), In this database the app stores to which store it is connected. Could you open and review if that's correct? If your app is new and you don't have anything custom in that database, you can safely remove it and will be auto-generated clean.

Let me know if this helps
