### ISSUE TITLE
[Bug]: Bundle error when running the shopify PHP app

### ISSUE THREAD

**Issue by yehiasalam** [Shopify/cli#605]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Hi, 

I'm trying to generate an app extension for my application and deploy it on Shopify. I'm using the php template, the latest version of the cli, and the latest version of nodejs. However I'm getting "Your lockfile was created by an old Bundler that left some things out." when trying to deploy using `npm run deploy`.

### Actual behavior

Error while building.

### Stack trace

```shell
theme_extensions | Running theme check on your Theme app extension...

━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Command failed with exit code 1: bundle install
    Your lockfile was created by an old Bundler that left some things out.
    Because of the missing DEPENDENCIES, we can only install gems one at a time, instead of installing 8 at a time.
    You can fix this by adding the missing gems to your Gemfile, running bundle install, and then removing the gems from your Gemfile.
    The missing gems are:
    * mini_portile2 depended upon by nokogiri
    --- ERROR REPORT TEMPLATE -------------------------------------------------------

    
    NoMethodError: undefined method `full_name' for nil:NilClass

      warning << "* #{unmet_spec_dependency}, depended upon #{spec.full_name}, unsatisfied by #{@specs.find {|s| s.name == unmet_spec_dependency.name && !unmet_spec_dependency.matches_spec?(s.spec) }.full_name}"
                                                                                                                                                                                               ^^^^^^^^^^
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:123:in `each'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:122:in `each'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:100:in `call'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer/parallel_installer.rb:71:in `call'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:254:in `install_in_parallel'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:209:in `install'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:89:in `block in run'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:12:in `block in lock'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:9:in `open'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/process_lock.rb:9:in `lock'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:71:in `run'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/installer.rb:23:in `install'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli/install.rb:62:in `run'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:257:in `block in install'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/settings.rb:131:in `temporary'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:256:in `install'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'
      C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/exe/bundle:48:in `block in <top (required)>'
      C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
      C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/exe/bundle:36:in `<top (required)>'
      C:/Ruby31-x64/bin/bundle:32:in `load'
      C:/Ruby31-x64/bin/bundle:32:in `<main>'

    ```

    ## Environment

    ```
    Bundler       2.3.23
      Platforms   ruby, x64-mingw-ucrt
    Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x64-mingw-ucrt]
      Full Path   C:/Ruby31-x64/bin/ruby.exe
      Config Dir  C:/ProgramData
    RubyGems      3.3.23
      Gem Home    C:/Users/Yehia/AppData/Local/shopify-cli-nodejs/Cache/vendor/theme-check/1.10.3/ruby/3.1.0
      Gem Path    C:/Users/Yehia/AppData/Local/shopify-cli-nodejs/Cache/vendor/theme-check/1.10.3/ruby/3.1.0
      User Home   C:/Users/Yehia
      User Path   C:/Users/Yehia/.gem/ruby/3.1.0
      Bin Dir     C:/Users/Yehia/AppData/Local/shopify-cli-nodejs/Cache/vendor/theme-check/1.10.3/ruby/3.1.0/bin
    OpenSSL
      Compiled    OpenSSL 1.1.1n  15 Mar 2022
      Loaded      OpenSSL 1.1.1n  15 Mar 2022
      Cert File   C:/Ruby31-x64/ssl/cert.pem
      Cert Dir    C:/Ruby31-x64/ssl/certs
    Tools
      Git         2.29.2.windows.2
      RVM         not installed
      rbenv       not installed
      chruby      not installed
    ```

    ## Bundler Build Metadata

    ```
    Built At          2022-10-05
    Git SHA           250d9d485d
    Released Version  true
    ```

    ## Bundler settings

    ```
    path
      Set for your local app (C:/Users/Yehia/AppData/Local/shopify-cli-nodejs/Cache/vendor/theme-check/1.10.3/.bundle/config): "C:/Users/Yehia/AppData/Local/shopify-cli-nodejs/Cache/vendor/theme-check/1.10.3"
    ```

    ## Gemfile

    ### Gemfile

    
    source 'https://rubygems.org'
    gem 'theme-check', '1.10.3'
    ```

    ### Gemfile.lock

    ```
    <No C:/Users/Yehia/AppData/Local/shopify-cli-nodejs/Cache/vendor/theme-check/1.10.3/Gemfile.lock found>
    ```

    --- TEMPLATE END ----------------------------------------------------------------

    Unfortunately, an unexpected error occurred, and Bundler cannot continue.

    First, try this link to see if there are any existing issue reports for this error:
    https://github.com/rubygems/rubygems/search?q=undefined+method+%60full_name%27+for+nil+NilClass&type=Issues

    If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the
report template above in there.
    Fetching gem metadata from https://rubygems.org/........
    Resolving dependencies...
    Using ast 2.4.2
    Using bundler 2.3.23
    Using liquid 5.4.0
    Using racc 1.6.0
    Installing nokogiri 1.13.8 with native extensions
```

### Reproduction steps

1. Generate a new app `npm init @shopify/app@latest`  (Using the PHP template)
2. Generate the theme extension `npm run shopify app generate extension`
3. Run the `README.md` instructions on the webfolder
4. Run `npm run deploy` or `npm run dev`.

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.16.3

### Node version (run `node -v` if you're not sure)

v16.17.1

### What language and version are you using in your application?

PHP 8.1.6

**Comment by alvaro-shopify** [comment]
Hi @yehiasalam !. Thank you for reporting this issue. 
After taking a look at the log, it seems that you are trying to test a `theme extension`. This is another issue #594 that reported the same problem. We are working on its solution. As soon as we solve it I will update here the status.
Thanks.

**Comment by yehiasalam** [comment]
Hello @alvaro-shopify , any updates on this?
