### ISSUE TITLE
[Bug]: `theme dev` randomly stopping itself

### ISSUE THREAD

**Issue by lesterdefreitas** [Shopify/cli#728]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

`theme dev` should only stop if requested.

### Actual behavior

`theme dev` seems to randomly stop itself at random times.

### Reproduction steps

1. run `theme dev`
2. open dev theme editor and make some changes
3. after a random amount of time, cli will have stopped itself in terminal

### Operating System

Mac OS Ventura 13.0

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.21.0

### Shell

$bash

### Node version (run `node -v` if you're not sure)

v18.11.0

### What language and version are you using in your application?

Shopify liquid template language

**Comment by chrisberthe** [comment]
Yes @ethansaks, having to log in each time the process randomly stops.

**Comment by ethansaks** [comment]
I have a hunch that the authentication is expiring and that's causing theme serve to end.

**Comment by zebsola** [comment]
+1 Having the same issue, theme dev stops for me every 2-3 hours. Have to auth again to continue!

**Comment by blanklob** [comment]
There a timeset called `ThemeRefreshTimeoutInMinutes` in the Shopify auth using the CLI to authenticate to a store, its 90 minutes, this really need to change as soon as possible or add the --password flag to use the token generated by the theme Access App.

Check here:  https://github.com/Shopify/cli/blob/main/packages/theme/src/cli/commands/theme/dev.ts

**Comment by notrealdev** [comment]
same here

**Comment by notrealdev** [comment]
+1 Having the same issue, theme dev stops for me every 2-3 hours. Have to auth again to continue!

**Comment by josho** [comment]
still a thing. reading the thread and some others, sounds like a feature that works like a bug.

**Comment by josho** [comment]
> There a timeset called `ThemeRefreshTimeoutInMinutes` in the Shopify auth using the CLI to authenticate to a store, its 90 minutes, this really need to change as soon as possible or add the --password flag to use the token generated by the theme Access App.
> 
> Check here: https://github.com/Shopify/cli/blob/main/packages/theme/src/cli/commands/theme/dev.ts

the crux of the issue. it wouldn't be terrible except that there's also nothing watching for activity. so it's not a timeout to free resources, it's just a guaranteed grenade to end your dev session -- even in the middle of making changes.

**Comment by its-anas** [comment]
@isaacroldan I just updated the CLI from 3.28 to 3.30. I still didn't test if it is still getting logged out after some time. But when i try 'shopify theme dev --password XXXXXX' command i get this error:
![image](https://user-images.githubusercontent.com/84609280/210549657-3c3f96e9-0402-4e9c-9c7f-a2e3b318bb1f.png)

**Comment by its-anas** [comment]
@isaacroldan  I just updated the CLI from 3.28 to 3.30. I still didn't test if it is still getting logged out after some time. But when i try 'shopify theme dev --password XXXXXX' command i get this error:
![image](https://user-images.githubusercontent.com/84609280/210549857-efa5e622-938c-42c7-9f7f-92f89329f22a.png)

**Comment by its-anas** [comment]
Damn! Even 'Shopify theme dev' doesn't work now:
![image](https://user-images.githubusercontent.com/84609280/210550817-ad0e210a-be5b-4b66-9dbf-f905947b05a3.png)

**Comment by isaacroldan** [comment]
Hi @its-anas!
That's a different error, the problem is that the CLI is trying to connect to the wrong store. Specify what store do you want to use for `dev` with `shopify dev theme --store {storeID or storeName}`

**Comment by bertiful** [comment]
@isaacroldan there seems to still be an issue. I woke up this morning to a process that was still running, which is reassuring, but when I saved a file it threw `ERROR  » update sections/slideshow.liquid: ✗ Please login again with shopify login`.

**Comment by isaacroldan** [comment]
@bertiful @vfonic the CLI should do the reauth automatically, could you please check if your session still works after 2 hours without restarting manually? (you might notice in your terminal that the process is reestarted automatically and that should refresh the tokens)

I've tested this in windows and mac and worked for me, but there are some special cases where your session might get revoked (if you logout from web for instance)

**Comment by vfonic** [comment]
@isaacroldan I gave it a try and indeed, I'm getting the same error "✗ Please login again with shopify login"

<details><summary>`shopify theme dev --store={xxx} --verbose`</summary>

```
[2023-01-04 10:52:59] INFO  WEBrick 1.7.0
[2023-01-04 10:52:59] INFO  ruby 3.1.3 (2022-11-24) [x86_64-darwin21]
[2023-01-04 10:52:59] INFO  WEBrick::HTTPServer#start: pid=13461 port=9292
DEBUG Refreshing preview _secure_session_id cookie
DEBUG Proxying HEAD https://xxxxxxx.myshopify.com/?preview_theme_id=136749089014&_fd=0&pb=0
DEBUG `-> 302 request_id: 6fcffb02-17af-4562-afcd-97932240674b
DEBUG Proxying GET https://xxxxxxx.myshopify.com/?_fd=0&pb=0
DEBUG `-> 200 request_id: e50da946-208b-49f9-8050-5e5100e4b00e
DEBUG [HotReload] Connected to SSE stream
DEBUG Proxying POST https://xxxxxxx.myshopify.com/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG Proxying POST https://xxxxxxx.myshopify.com/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG Proxying POST https://xxxxxxx.myshopify.com/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG Proxying POST https://xxxxxxx.myshopify.com/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG Proxying POST https://xxxxxxx.myshopify.com/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG `-> 200 request_id: 057493a8-4c5d-4603-87fe-5ed1ce816d5c
DEBUG Proxying POST https://xxxxxxx.myshopify.com/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG `-> 200 request_id: fa9fbd88-6707-4168-8f9f-a7a7a70690c1
DEBUG `-> 200 request_id: 6694056e-34ab-4894-9614-3499ada177d7
DEBUG `-> 200 request_id: b0bb0e96-d89d-458b-8d85-30c35ce407d7
DEBUG `-> 200 request_id: 73ec71ab-cd62-4ab3-8936-880c1a459d96
DEBUG `-> 200 request_id: 7d8520e8-ef58-4e64-ad9e-4805a7c1270d
DEBUG Proxying GET https://xxxxxxx.myshopify.com/cart?view=drawer&timestamp=1672851097879&_fd=0&pb=0
DEBUG Proxying GET https://xxxxxxx.myshopify.com/apps/intercom-proxy?_fd=0&pb=0
DEBUG `-> 200 request_id: 4b63b088-e0b9-47b1-857f-f8f560281c15
DEBUG `-> 200 request_id: 228ec737-dc5e-4b73-b76e-8be54b5bffdf
DEBUG Proxying POST https://xxxxxxx.myshopify.com/.well-known/shopify/monorail/v1/produce?_fd=0&pb=0
DEBUG `-> 200 request_id: 8b2663c5-8fb8-45fe-9b7b-b01043de22ce
DEBUG [HotReload] Modified snippets/made-to-measure-modal copy.liquid
DEBUG update snippets/made-to-measure-modal copy.liquid
DEBUG PUT https://xxxxxxx.myshopify.com/admin/api/unstable/themes/136749089014/assets.json with X-Request-Id: 1f8568e2-d8a6-4f17-9e7e-fda966961e21
13:23:57 ERROR  » update snippets/made-to-measure-modal copy.liquid: ✗ Please login again with shopify login
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/context.rb:86:in `abort'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/context.rb:451:in `abort'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/identity_auth.rb:121:in `reauthenticate'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/admin_api.rb:96:in `block in rest_request'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:181:in `rescue in retry_after'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:171:in `retry_after'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/admin_api.rb:95:in `rest_request'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/theme/theme_admin_api.rb:38:in `rest_request'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/theme/theme_admin_api.rb:22:in `put'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/theme/syncer.rb:314:in `update'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/theme/syncer.rb:293:in `perform'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/theme/syncer.rb:156:in `block (3 levels) in start_threads'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/theme/syncer.rb:152:in `loop'
        /Users/viktor/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0/ruby/3.1.0/gems/shopify-cli-2.33.0/lib/shopify_cli/theme/syncer.rb:152:in `block (2 levels) in start_threads'
```
</details>

**Comment by zebsola** [comment]
@isaacroldan I, too, have the same issue -- times out and then I get an error when trying to save/sync a file: 
`ERROR  » update assets/base.css: ✗ Please login again with shopify login`

I'm on CLI v 3.30.2

(as a side note, it says to login again with "shopify login" but using that command gives the error `command login not found`)

**Comment by isaacroldan** [comment]
This PR should fix it https://github.com/Shopify/cli/pull/1013
We'll release a new version on monday 👍

**Comment by vfonic** [comment]
That was as fast as it gets! Thank you, Isaac! 🙏

**Comment by zebsola** [comment]
@isaacroldan  Sorry to revive this bug but with the new fix, while it doesn't log me out, does produce this error every time it refreshes the `theme dev`:

![Screenshot 2023-01-11 at 10 29 46 AM](https://user-images.githubusercontent.com/43549659/211913441-e076f152-a3d8-4289-b7bb-44a637c39ce4.jpg)

It seems like the theme dev command still times out after 2 hours, and automatically re-serves, but the port is busy or something at that moment (probably because it was taken for the previous serve?) and so errors with "The address ___ is already in use." Which means I have to manually re-do `theme dev` every 2 hours with a new port number.

**Comment by vfonic** [comment]
I can confirm that I have the same issue. The port/process doesn't get cleared/killed before the tool tries to start a new process on the same port.

**Comment by isaacroldan** [comment]
@zebsola @vfonic are you on windows? 
I'll try to reproduce and fix the issue. I appreciate all the reports 🙇

**Comment by vfonic** [comment]
No, I'm on macOS, Apple Silicon. I start the command from within the VS Code integrated terminal.

**Comment by zebsola** [comment]
Also on macOS and Apple Silicon, but using phpStorm IDE terminal.

**Comment by vfonic** [comment]
3 seconds is a lot IMO. The ideal solution would be to wait until the original process is killed, not some arbitrary number.

You could even try (re)starting the process several times if it fails on the first try.

You could also update the auth token in-place, instead of having to restart the process.

Just my $0.02.

**Comment by zebsola** [comment]
On Friday I actually noticed that it was successfully re-logging in with no issues on the same port. I will continue to monitor today. However, I'm getting this strange behavior where it gives an error, saying I need to login with "shopify login" (which, again, is not even a valid command) but yet immediately afterward syncs anyway. I tried logging out and then authorizing again, but still the same Error-then-Sync behavior. See screenshot.

![image](https://user-images.githubusercontent.com/43549659/212756669-2fd7ea21-1efc-4fa5-a7cd-a5b1b0ed2df0.png)

**Comment by zebsola** [comment]
@vfonic @isaacroldan 
Just got the port error again:
![image](https://user-images.githubusercontent.com/43549659/212772004-a7ebd33b-3490-4834-8176-16cf423d3b04.png)

**Comment by vfonic** [comment]
If the stack trace is correct, it seems like you're using v3.31.1. Latest CLI version is v3.33.0: https://github.com/Shopify/cli/releases

v3.33.0 doesn't seem to be the one with sleep delay AFAIK

**Comment by zebsola** [comment]
@vfonic Ah! Missed that there was any update.

Installing now. Keeping in mind what you said about the sleep delay not being part of this release, I'll still keep an eye for any port issues.

**Comment by zebsola** [comment]
Apologies to anyone subscribed to this thread for all my messages 😬 

@vfonic @isaacroldan 
I installed the newest CLI (which actually happens to now be 3.34.0 - guess the update you were referring to was pushed up?)

First thing after installing, when attempting to serve with theme dev, got the port error (and it wasn't even the port I was previously using)

![image](https://user-images.githubusercontent.com/43549659/212775802-a5f75e08-b3ae-41e1-8c47-af7dc2ee16c4.png)

**Comment by vfonic** [comment]
Try killing whatever process is running on port :9292 with fkill or whatever else you prefer to use:
https://github.com/sindresorhus/fkill-cli

The command should be `fkill :9292`
