### ISSUE TITLE
[Bug]: Cannot find missing Shopify CLI 2.x gems

### ISSUE THREAD

**Issue by gcaprio** [Shopify/cli#732]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

I'm migrating an application from Shopify-CLI 2.x to 3.x. My structure and toml files are basically the same as the app template. 

It should start up Vite & Rails and push my extension up for development.

### Actual behavior

What actually happens is I get an error about missing gems related to CLI2

### Stack trace

```shell
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:30 | frontend   | > dev
2022-11-07 22:20:30 | frontend   | > PORT=3001 vite
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:30 | frontend   |   vite v2.9.15 dev server running at:
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:30 | frontend   |   > Local:    http://localhost:59443/
2022-11-07 22:20:30 | frontend   |   > Network:  http://192.168.0.191:59443/
2022-11-07 22:20:30 | frontend   |   > Network:  http://169.254.204.132:59443/
2022-11-07 22:20:30 | frontend   |   > Network:  http://169.254.128.148:59443/
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:30 | frontend   |   ready in 340ms.
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:30 | frontend   |
2022-11-07 22:20:32 | backend    | => Booting Puma
2022-11-07 22:20:32 | backend    | => Rails 7.0.4 application starting in development
2022-11-07 22:20:32 | backend    | => Run `bin/rails server --help` for more startup options
2022-11-07 22:20:32 | backend    |
2022-11-07 22:20:32 | backend    | Puma starting in single mode...
2022-11-07 22:20:32 | backend    | * Puma version: 5.6.5 (ruby 3.1.2-p20) ("Birdie's Version")
2022-11-07 22:20:32 | backend    | *  Min threads: 5
2022-11-07 22:20:32 | backend    | *  Max threads: 5
2022-11-07 22:20:32 | backend    | *  Environment: development
2022-11-07 22:20:32 | backend    | *          PID: 24105
2022-11-07 22:20:32 | backend    |
2022-11-07 22:20:32 | backend    | * Listening on http://127.0.0.1:59434
2022-11-07 22:20:32 | backend    | * Listening on http://[::1]:59434
2022-11-07 22:20:32 | backend    | Use Ctrl-C to stop
2022-11-07 22:20:32 | backend    |

Could not find shopify-cli-2.29.0, bugsnag-6.24.2, listen-3.7.1, theme-check-1.11.0, concurrent-ruby-1.1.10, rb-fsevent-0.11.2, rb-inotify-0.10.1, liquid-5.4.0, nokogiri-1.13.9-x86_64-darwin, parser-3.1.2.1, ffi-1.15.5, ast-2.4.2 in locally installed gems
Run `bundle install` to install missing gems.
/Users/gcaprio/source/uapt-shopify-app-3.x/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

AbortSilent [Error]
    at execCLI2 (file:///Users/gcaprio/source/uapt-shopify-app-3.x/node_modules/@shopify/cli-kit/dist/node/ruby.js:46:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.action (file:///Users/gcaprio/source/uapt-shopify-app-3.x/node_modules/@shopify/app/dist/cli/services/dev.js:125:13)
    at async file:///Users/gcaprio/source/uapt-shopify-app-3.x/node_modules/@shopify/cli-kit/dist/private/node/ui/components/ConcurrentOutput.js:70:17
    at async Promise.all (index 1)
    at async runProcesses (file:///Users/gcaprio/source/uapt-shopify-app-3.x/node_modules/@shopify/cli-kit/dist/private/node/ui/components/ConcurrentOutput.js:67:13) {
  tryMessage: null,
  type: 1
}
```

### Reproduction steps

1. Follow the migration instructions here: https://shopify.dev/apps/tools/cli/migrate
2. run `npm run dev` in the root directory under ruby 3.1.2

### Operating System

macOS 12.6

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.21.0

### Shell

iterm2 w/ ZSH

### Node version (run `node -v` if you're not sure)

v16.14.2

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by gcaprio** [comment]
Sure thing @isaacroldan 👍 

> What extension types are you using?
I'm only using a theme extension with 1 app embed block and 4 app blocks

> Do you have Shopify CLI2 as a dependency of your ruby app?
No, I only have the shopify_app gem v20.2.0

**Comment by shauns** [comment]
Thanks for raising this -- we'll look into it. You shouldn't _need_ to specify that option.

**Comment by gcaprio** [comment]
thanks @k-ogasawara sadly when I do that I get an even bigger list of missing gems

**Comment by Poitrin** [comment]
I might have found a similar (?) way to reproduce the issue:
1. `pnpm create @shopify/app@latest --template=ruby`
2. `cd ...` (into new dir)
3. `export SHOPIFY_FLAG_STORE=....myshopify.com` (so that CLI will surely find the right dev store)
4. `pnpm run dev`

```
$ pnpm run dev

> issue-732@1.0.1 dev /Users/poitrin/src/github.com/Shopify/issue-732
> shopify app dev

✔ Dependencies installed

Looks like this is the first time you're running dev for this project.
Configure your preferences by answering a few questions.


Before you preview your work, it needs to be associated with an app.

✔ Create this project as a new app on Shopify? · Yes, create it as a new app
✔ App Name · issue-732
✅ Success! issue-732 has been created on your Partners account.
✅ Success! The tunnel is running and you can now view your app.

…

── external error

Error coming from `bin/rails server`

Command failed with exit code 1: bin/rails server
/Users/poitrin/.gem/ruby/3.1.2/gems/bundler-2.3.20/lib/bundler/resolver.rb:272:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'sprockets-rails' in locally installed gems. (Bundler::GemNotFound)
        from /Users/poitrin/.gem/ruby/3.1.2/gems/bundler-2.3.20/lib/bundler/resolver.rb:255:in `map!'
        from /Users/poitrin/.gem/ruby/3.1.2/gems/bundler-2.3.20/lib/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
        from /Users/poitrin/.gem/ruby/3.1.2/gems/bundler-2.3.20/lib/bundler/resolver.rb:50:in `start'
        from /Users/poitrin/.gem/ruby/3.1.2/gems/bundler-2.3.20/lib/bundler/resolver.rb:24:in `resolve'
   …
        from /Users/poitrin/.gem/ruby/3.1.2/gems/bundler-2.3.20/lib/bundler/setup.rb:20:in `<top (required)>'
        from <internal:/opt/rubies/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/opt/rubies/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/poitrin/src/github.com/Shopify/issue-732/web/config/boot.rb:6:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
