### ISSUE TITLE
[Bug]: CLI output Auth error after running npm run dev -- --reset

### ISSUE THREAD

**Issue by sja87** [Shopify/cli#772]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

After enter the "npm run dev" I expected to start the local development server. The first time I create the app everything works fine.

### Actual behavior

After stopping the server and try to enter "npm run dev" or "npm run dev -- --reset", I get a auth error.

I try to "shopify auth logout" and also try to clear my cookies and cache in my browser.

<img width="1474" alt="Bildschirm­foto 2022-11-14 um 14 27 25" src="https://user-images.githubusercontent.com/4973582/201672061-b3865fa6-6f4f-4aa4-8ba8-5d1049263b50.png">

### Stack trace

```shell
/Users/seb/Documents/Shopify/Apps/myfirstapp/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

AbortSilent [Error]
    at execCLI2 (file:///Users/seb/Documents/Shopify/Apps/myfirstapp/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:46:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.action (file:///Users/seb/Documents/Shopify/Apps/myfirstapp/node_modules/@shopify/app/dist/cli/services/dev.js:125:13)
    at async file:///Users/seb/Documents/Shopify/Apps/myfirstapp/node_modules/@shopify/cli-kit/dist/private/node/ui/components/ConcurrentOutput.js:70:17
    at async Promise.all (index 1)
    at async runProcesses (file:///Users/seb/Documents/Shopify/Apps/myfirstapp/node_modules/@shopify/cli-kit/dist/private/node/ui/components/ConcurrentOutput.js:67:13) {
  tryMessage: null,
  type: 1
}

Node.js v19.0.1
```

### Reproduction steps

1. npm run dev -- --reset

### Operating System

Mac OS 13.0.1 

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.22.1

### Node version (run `node -v` if you're not sure)

v19.0.1

### What language and version are you using in your application?

PHP 8.1

**Comment by isaacroldan** [comment]
Hi @sja87 , this is because the `theme app extension` needs access to your store, and by default when you create a development store from partners, the owner of that store is not the same owner as the partners organization (this is a known issue and we are working on it).

In the meantime, the workaround for this is: go to your store settings `{your_store_url}/admin/settings/account` and invite your partner account email as staff member of the store.

Let me know if that helps!

**Comment by sja87** [comment]
@isaacroldan Great! now it works
