### ISSUE TITLE
[Bug]: Using 'shopify_sessions' table as a foreign key reference

### ISSUE THREAD

**Issue by tamir-boaideas** [Shopify/cli#829]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Every time a store installs my app, I save a record in a 'settings' table with a foreign key constraint to the id column in the 'shopify_sessions' table. With MySQL as the database and online tokens, I need to be able to have that foreign key constraint, preferably with 'CASCADE' on delete.

### Actual behavior

Whenever the online token expires, I receive a foreign key constraint error.
I walked through the stack trace and realized that the issue is with the 'REPLACE' statement which attempts to delete the shop's row in 'shopify_sessions' and recreate it with the new token. 

Also, I tried to add the columns from my settings table directly into the shopify_sessions table but when the token refresh occurs, it deletes the row and doesn't repopulate my custom columns with the previous data.

I was able to accomplish what I needed by removing the foreign key constraint and using a manual data integrity safety approach, but that doesn't seem like the best approach.

### Stack trace

```shell
Error: Cannot delete or update a parent row: a foreign key constraint fails (`online`.`settings`, CONSTRAINT `settings_shop_foreign` FOREIGN KEY (`shop`) REFERENCES `shopify_sessions` (`id`))
     at PromiseConnection.query (/Users/tamir/workspace-server/App-Nodejs/app/web/node_modules/mysql2/promise.js:93:22)
     at MySQLSessionStorage.query (/Users/tamir/workspace-server/App-Nodejs/app/web/node_modules/@shopify/shopify-api/dist/auth/session/storage/mysql.js:194:32)
     at MySQLSessionStorage.<anonymous> (/Users/tamir/workspace-server/App-Nodejs/app/web/node_modules/@shopify/shopify-api/dist/auth/session/storage/mysql.js:39:51)
     at step (/Users/tamir/workspace-server/App-Nodejs/app/web/node_modules/tslib/tslib.js:144:27)
     at Object.next (/Users/tamir/workspace-server/App-Nodejs/app/web/node_modules/tslib/tslib.js:125:57)
     at fulfilled (/Users/tamir/workspace-server/App-Nodejs/app/web/node_modules/tslib/tslib.js:115:62)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Reproduction steps

1. Instantiate a blank Shopify CLI app template
2. Change the default DB to MySQL
3. Add a settings table with a 'shop' column as a foreign key that references the 'id' column on the 'shopify_sessions' table
4. Using online token, install the app and create a settings record for that store
5. Try to access the app after the token has expired and needs to be refreshed.

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.21.0

### Shell

Terminal

### Node version (run `node -v` if you're not sure)

v18.11.0

**Comment by tamir-boaideas** [comment]
Hi @shauns ,
Thank you for your response.
The problem is that the row shouldn't really be deleted since it's only the online token that needs to be refreshed.
If I set that FK, the row in shopify_sessions can't be deleted because it's beign referenced in another table.
If I understand correctly, Any FK referencing the shopify_sessions table isn't allowed?
Is there no way to ensure the integrity of data between the shopify_sessions table (which I cannot modify) and other tables in the database?
It feels like a bug to me.
Please let me know what you think about this,
I appreciate your help.
Tamir
