### ISSUE TITLE
[Bug]: Recently, the startup often reported an error, and occasionally it was normal.

### ISSUE THREAD

**Issue by bithaolee** [Shopify/cli#849]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension, Theme

### Expected behavior

Be able to start

### Actual behavior

throw an error

### Stack trace

```shell
yarn run v1.22.19
$ shopify app dev --tunnel-url=myproxyurl
✔ Dependencies installed

Using your previous dev settings:
- Org:          xxx
- App:          xxxxxxx
- Dev store:    xxxx.myshopify.com
- Update URLs:  Always

To reset your default dev config, run yarn dev --reset

✔ URL updated


Shareable app URL

  https://[mydomain]?shop=xxx.myshopify.com&host=c2hpcHByb3RlY3Rpb24ubXlzaG9waWZ5LmNvbS9hZG1pbg

My theme app extension name (Theme app extension)
Follow the dev doc instructions by deploying your work as a draft

2022-12-01 09:16:14 | frontend   |
2022-12-01 09:16:14 | frontend   | > dev
2022-12-01 09:16:14 | frontend   | > vite
2022-12-01 09:16:14 | frontend   |
2022-12-01 09:16:14 | frontend   |
2022-12-01 09:16:14 | backend    |
2022-12-01 09:16:14 | backend    | > dev
2022-12-01 09:16:14 | backend    | > cross-env NODE_ENV=development nodemon index.js --ignore ./frontend
2022-12-01 09:16:14 | backend    |
2022-12-01 09:16:14 | backend    |

/Users/xxx/Workspace/appname/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: connect ECONNREFUSED ::1:53485
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 53485
}

Node.js v18.12.1
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction steps

1. yarn dev --tunnel-url=myurl

### Operating System

MacOS Monterey 12.6.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

^3.19.0

### Shell

iterm2

### Node version (run `node -v` if you're not sure)

v18.12.1

### What language and version are you using in your application?

Node 18.12.1

**Comment by amcaplan** [comment]
Hi @bithaolee, thanks for opening an issue! I'm curious if there is any specific change in your app or extension code that you can identify that led to this error. I'm not seeing anything like this on a freshly generated app with a theme app extension.

**Comment by LucaIaconelli** [comment]
Hi @amcaplan Can you by any chance help me with this problem?

**Comment by GabeHarris** [comment]
> This issue seems inactive. If it's still relevant, please add a comment saying so. Otherwise, take no action. → If there's no activity within a week, then a bot will automatically close this. Thanks for helping to improve Shopify's dev tooling and experience.

It is still very relevant

**Comment by wem5637** [comment]
also seeing this issue

**Comment by usrx-rob** [comment]
I'm having this issue!

**Comment by Vijendra2016** [comment]
To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser
C:\Users\HP\AppData\Roaming\npm\node_modules\@shopify\cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

AbortError: invalid_target
    at tokenRequestErrorHandler (file:///C:/Users/HP/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/session/exchange.js:130:12)
    at Err.mapError (file:///C:/Users/HP/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/result.js:130:20)
    at requestAppToken (file:///C:/Users/HP/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/session/exchange.js:115:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exchangeAccessForApplicationTokens (file:///C:/Users/HP/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/session/exchange.js:46:23)
    at async executeCompleteFlow (file:///C:/Users/HP/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/session.js:114:20)
    at async ensureAuthenticated (file:///C:/Users/HP/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/session.js:48:22)
    at async ensureAuthenticatedAdmin (file:///C:/Users/HP/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/session.js:62:20)
    at async Dev.execute (file:///C:/Users/HP/AppData/Roaming/npm/node_modules/@shopify/theme/dist/cli/commands/theme/dev.js:39:30) {
  tryMessage: null,
  type: 0,
  nextSteps: undefined
}

Node.js v18.13.0

Thats issue i facing once i upgrade to shopify cli

**Comment by amcaplan** [comment]
Hi new commenters (@wem5637 @usrx-rob @Vijendra2016), thanks for reaching out.

I wouldn't expect new updates on this issue, because it's closed, as the original reporter didn't respond. I'd request, as mentioned above, that you add your reports to an open issue or open a new issue with all requested details, so we can handle this effectively.

It's difficult to know which of you are actually facing the same issue vs. a number of distinct issues with similar symptoms. That's why we need to know OS, terminal, Node version, CLI version, etc. as well as seeing the stack trace and repro steps.

**Comment by amcaplan** [comment]
I've locked as we need to treat further reports as new issues. I strongly encourage anyone facing this to open a new issue as discussed.
