### ISSUE TITLE
Internal Server Error after Migrating from Shopify CLI 2.x

### ISSUE THREAD

**Issue by llcoolcey** [Shopify/cli#889]
Hi,

I was using Shopify CLI 2.x before.

After installing Shopify CLI 3.x I get the following error after I run `shopify theme dev`:

```
Internal Server Error
invalid name: "mailerlite:forms:shown:XXXXXXXXXXXXX"
WEBrick/1.7.0 (Ruby/3.1.3/2022-11-24) at 127.0.0.1:9292
```

One theme is using MailerLite Newsletter snippet (The XXX is the ID of the form). I have removed the snippet from the theme, but still. And this happens whichever store I'm logged in to. I have also tried everything. Uninstalling. Logout. Login. Install again. Installing Shopify CLI 2.x also spits out same error.

When I run `shopify theme check` it shows errors after showing the Results:
 
```
Theme check failed with error:
/Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/theme-check-1.11.0/lib/theme_check/cli.rb:197:in `check': ThemeCheck::Cli::Abort
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/theme-check-1.11.0/lib/theme_check/cli.rb:123:in `run!'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/project_types/theme/commands/check.rb:27:in `call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/shopify_cli/command.rb:27:in `call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/shopify_cli/core/executor.rb:15:in `call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/shopify_cli/core/entry_point.rb:38:in `block in call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/shopify_cli/core/monorail.rb:26:in `log'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/lib/shopify_cli/core/entry_point.rb:37:in `call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/bin/shopify:49:in `block in <top (required)>'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/gems/shopify-cli-2.32.0/bin/shopify:59:in `<top (required)>'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/bin/shopify:25:in `load'
from /Users/ceyhun/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.32.0/ruby/3.1.0/bin/shopify:25:in `<top (required)>'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
from /opt/homebrew/Cellar/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
from /opt/homebrew/opt/ruby/bin/bundle:25:in `<main>'
```

What could be the issue?
I'd be thankful for your help.

**Comment by llcoolcey** [comment]
Deleting Cache solved it...
