### ISSUE TITLE
[Bug]: "output.initiateLogging is not a function" on npm run dev

### ISSUE THREAD

**Issue by polidario** [Shopify/cli#989]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The commands:

- npm run dev
- npm run shopify [other commands]

...should all work as expected.

### Actual behavior

Instead, it produces the following error:

```
myprojectexample\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: output.initiateLogging is not a function

at runCLI (file:///C:/.../node_modules/@shopify/cli/dist/index.js:8:10)
    at file:///C:/.../node_modules/@shopify/cli/bin/run.js:7:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1
```

### Reproduction steps

1. Open a Shopify app project created by `npm init @shopify/app@latest`
2. In the command line, run: `npm run dev` or `npm run shopify version`
3. Voila, error happens

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

Shopify CLI 3.23.0

### Node version (run `node -v` if you're not sure)

v18.12.1

**Comment by polidario** [comment]
[Fixed]

 `npm update` should fix the issue
